### ISSUE TITLE
Container Verify

### ISSUE THREAD

**Issue by Kmaczek** [autofac/Autofac#1019]
In relation to this: [Container validation #853](https://github.com/autofac/Autofac/issues/853) 

What I needed is to check right after container.Build() if all dependencies are resolvable.
Sometimes we know that only after some part of the code was used, because thats the moment when they are first time injected.

I wrote something like this:

```
public static List<string> Verify(this IContainer container)
{
    var errors = new List<string>();
    var registrations = container.ComponentRegistry.Registrations;

    using(var scope = container.BeginLifetimeScope())
    {
        foreach (var registration in registrations.SelectMany(x => x.Services))
        {
            try
            {
                if(registration is Autofac.Core.TypedService)
                {
                    var tSvc = registration as Autofac.Core.TypedService;
                    scope.Resolve(tSvc.ServiceType);
                }
                else if(registration is Autofac.Core.KeyedService)
                {
                    var kSvc = registration as Autofac.Core.KeyedService;
                    scope.ResolveNamed(kSvc.ServiceKey.ToString(), kSvc.ServiceType);
                }
            }
            catch (Autofac.Core.DependencyResolutionException ex)
            {
                errors.Add($"{ex.Message} {ex.InnerException}");
            }
        }
    }

    return errors;
}
```

Feel free to use it if it helps you at all, in my case its enough for this types of registered objects:
```
diBuilder.RegisterInstance(configuration).SingleInstance();
diBuilder.RegisterType<ConfigHelper>().SingleInstance();
diBuilder.RegisterInstance(mapper).SingleInstance();
diBuilder.RegisterModule<LoggingModule>();

diBuilder.RegisterType<PiContext>();
diBuilder.Register<Func<PiContext>>(x => 
{
     var context = x.Resolve<IComponentContext>();
     return () => context.Resolve<PiContext>();
});

diBuilder.RegisterType<EmailSummaryJob>().Named<IJob>(nameof(EmailSummaryJob));
```
Regards
Damian

**Comment by alistairjevans** [comment]
Damian,

If you read @tillig's comments in the original issue you reference, you'll see that while it's easy to do a basic pass on a simple set of registrations as you have created here, defining a container verification process that accounts for the myriad ways that registrations can be defined becomes extremely difficult once you try to account for all cases. You also can't compensate for errors that aren't due to a fault in the container registrations (what happens if a service connects to a database or something when it is resolved?).

My instinct is that verification of a container is best suited to individual implementations as you have here, that understand what is being verified, rather than trying to implement some kind of universal container verification process within Autofac itself.

Thanks,

Alistair
