### ISSUE TITLE
Handle internal types in Autofac

### ISSUE THREAD

**Issue by azsdaja** [autofac/Autofac#1036]
At the moment it's not possible in Autofac to register internal types by default:
```
No constructors on type 'MyInternalType' can be found with the 
constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'
```
A custom IConstructorFinder is described in this post: https://stackoverflow.com/questions/52793062/how-to-resolve-public-class-with-internal-constructor-on-autofac.
However, it forces the user to create bindings in incovenient way:
`builder.RegisterType<Customer>().FindConstructorsWith(new AllConstructorFinder()).AsSelf();`

Maybe it's because using _internal_ modifiers is not very popular among programmers, but for these that care more about encapsulation of module content it's hard now to use Autofac.

Please correct me if I omitted something.

**Comment by alistairjevans** [comment]
Personally, I find it's much more common to have internal classes, with public constructors, than public classes with internal constructors.  Autofac is fine with internal classes provided the constructors are public. 

The most common situation I'd encounter for adding an internal constructor to a public type would be for creating objects for unit testing, but then I'd be calling those constructors directly anyway rather than getting Autofac to do it.

If you do need to access internal constructors on a registered type, I will say that you don't technically have to create a new constructor finder object, you can just use a lambda function:

```
builder.RegisterType<Customer>().FindConstructorsWith(type => type.GetConstructors(BindingFlags.Instance | BindingFlags.NonPublic));
```

If you need to do it a lot, you can define your own extension method:

```
public static IRegistrationBuilder<TLimit, TReflectionActivatorData, TStyle>
        FindAllConstructors<TLimit, TReflectionActivatorData, TStyle>(
            this IRegistrationBuilder<TLimit, TReflectionActivatorData, TStyle> registration)
        where TReflectionActivatorData : ReflectionActivatorData
        {
            return registration.FindConstructorsWith(t => t.GetConstructors(BindingFlags.Instance | BindingFlags.NonPublic));
        }
```

**Comment by azsdaja** [comment]
Thanks for explanation. Honestly, I thought that the problem occurs also in case with _internal class with public constructor_, which also for me makes more sense. I have to recheck my code again.

**Comment by alistairjevans** [comment]
Cool; I'll close this issue, we can re-open it if you find a circumstance where Autofac won't load public constructors.
