### ISSUE TITLE
Captive dynamic scoped dependency should have its lifetime respected

### ISSUE THREAD

**Issue by blalonde** [autofac/Autofac#1046]
Autofac version 4.9.4

Consider 

``` c-sharp
using System;
using System.Collections.Generic;

using Autofac;

using FluentAssertions;

using Xunit;

namespace PowerShellProxyTests.Caching
{
    public class DummyTest
    {
        private class Single
        {
            private readonly HashSet<Guid> _hash = new HashSet<Guid>();

            private readonly Func<Scoped> _scoped;

            public Single(Func<Scoped> scoped)
            {
                this._scoped = scoped;
            }

            public bool HasInjectedScoped()
            {
                return this._hash.Add(this._scoped().Var);
            }
        }

        private class Scoped
        {
            public readonly Guid Var = Guid.NewGuid();
        }

        [Fact]
        public void Test()
        {
            var builder = new ContainerBuilder();

            builder.RegisterType<Single>().SingleInstance();
            builder.RegisterType<Scoped>().InstancePerLifetimeScope();

            using (var rootLifetime = builder.Build())
            {
                using (var nestedLifetime = rootLifetime.BeginLifetimeScope())
                {
                    var single = nestedLifetime.Resolve<Single>();
                    single.HasInjectedScoped().Should().BeTrue();
                }

                using (var nestedLifetime = rootLifetime.BeginLifetimeScope())
                {
                    var single = nestedLifetime.Resolve<Single>();
                    single.HasInjectedScoped().Should().BeTrue(); // fails
                }
            }
        }
    }
}
```

I would have thought the scoped lifetime would be respected, since the [doc](https://autofaccn.readthedocs.io/en/latest/resolve/relationships.html#dynamic-instantiation-func-b) notes that "Lifetime scopes are respected" when using a func.

If I replace InstancePerLifetimeScope by InstancePerDependency it works, although dependency is not scoped anymore. 

Any insight on this ?

**Comment by tillig** [comment]
[We have some docs on captive dependencies that explain this](https://autofac.readthedocs.io/en/latest/lifetime/captive-dependencies.html), though maybe we could add a bit more clarification to those docs on this point.

Lifetime scopes _are_ respected, but the thing you may be missing is that the dependencies of a service are resolved from the same lifetime scope as the service being resolved _or parent scopes_. If you have a singleton, that singleton is getting resolved from the root container. If the singleton has dependencies, those, too, will be resolved from the root container. That `Func<Scoped>` is tied to resolving something from the root container - there's no "ambient current lifetime scope" magic.

Even in a nested lifetime scope, the singleton gets resolved from the root container, then the `Scoped` (being "instance per lifetime scope") also gets resolved from the root container. Instance per lifetime scope means you just created a root-level singleton `Scoped`.

Logically speaking, that's the only way to handle such a thing.

Let's say for argument that the singleton did, somehow, respect the lifetime scope of `Scoped`.

First, you'd have a chicken/egg problem in the constructor of `Single`:
- Either there needs to be some "ambient" lifetime scope to which `Func<Scoped>` is attached; OR
- The `Single` object needs to be re-constructed every time the `Func<Scoped>` has to change, which means it's not a singleton anymore.

Then you have a threading problem - you have a singleton that can be used across lots of threads and have things injected in it, but the singleton isn't necessarily written properly with locking because it's not technically supposed to know about its lifetime scope. (Lifetime scope of something is a separate concern from the class logic.) If `Func<Scoped>` can change dynamically out from under `Single` you get some hard to troubleshoot behavior.

The real key to captive dependencies, as mentioned in the docs:

> The general rule to avoid captive dependencies:
>
> **The lifetime of the consuming component should be less than or equal to the lifetime of the service being consumed.**
>
>Basically, don’t let a singleton take an instance-per-request dependency because it’ll be held too long.
