### ISSUE TITLE
Can Service consumer's PropertyInfo be passed to service?

### ISSUE THREAD

**Issue by rhyous** [autofac/Autofac#1070]
I am implementing Autofac in an existing solution. I am looking to inject a class that has a name property and the name could be different.

Is there anyway to access a consumer's ParameterInfo from the Service's registration? 

The reason I ask is because I am looking for a solution that is Big O (1) in regards to coding time instead of Big O(N)

```
    public interface IEntityService
    {
        string Entity { get; }
    }

    public class EntityService : IEntityService
    {
        public EntityService(string name) { Entity = name; }
        public string Entity { get; }
    }

    public interface IConsumer
    {
    }

    public class Consumer : IConsumer
    {
        private readonly IEntityService _UserService;
        public Consumer(IEntityService userService)
        {
            _UserService = userService;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var builder = new ContainerBuilder();
            // cpi would be the consumer's ParameterInfo.
            // for Consumer, this would be the ParamterInfo for the consumer's "userService" parameter.
            builder.Register((ctx, pi, cpi) => new EntityService(cpi.Name.StripFromEnd("Service"))).As<IEntityService>();
            var container = builder.Build();

            var consumer = container.Resolve<IConsumer>();
            
        }
    }
```

If I could access the consumer's ParameterInfo, then by convention, I can name a parameter on the consumer correctly get the desired entity name injected in.

Note: I can do this from the Consumer using a keyed registration, but that isn't a maintainable solution because it requires N registrations where N is the number of consumers. i.e. Big O(N) registrations. This existing solution has hundreds of consumers.  If this could be done on the service, it would be Big O(1). Would you want to edit 100s of registrations to solve this with 1 registration?

If this feature isn't there, then this may be a feature request.

I am known to contribute code, so if this feature isn't there and I can be pointed in the right way of doing the work, and would not be too invasive, I may be able to do it.

**Comment by rhyous** [comment]
Looking at the code, there is a `ResolveRequest.cs` where the consumer's ParameterInfo could be stored (should it be nullable since it won't always be there) and `AutowiringParameter.cs` has the consumer's ParameterInfo as variable `pi`, so adding it to the resolve request, line 58 could become:
```
valueProvider = () => context.ResolveComponent(new ResolveRequest(service, registration, Enumerable.Empty<Parameter>(), pi));
```
It looks like `InstanceLookup.cs` may need to store this as it doesn't store the whole `ResolveRequest`, just parts of it.

That is as far as I've gotten, but it looks fairly doable so far.

**Comment by tillig** [comment]
As you've seen, I'm not sure if this is possible. But also... **I don't think we want to make it possible.**

It seems like this sort of a use case has a fairly limited scope. (Honestly, just brainstorming, I can't think of another reason this might be needed.)

But on a larger architectural scale, this means the **registrations "know" about the consumer/dependency relationship**, which goes against how DI is supposed to work. In the pseudocode example, the EntityService registration would have to _know_ that it's getting consumed by a certain type of consumer, with a certain naming convention for parameters, and if it was being consumed elsewhere... that wouldn't work.

It reminds me a bit of one of our FAQs about [how to pass a parameter to something in the middle of a resolve chain](https://autofac.readthedocs.io/en/latest/faq/injecting-global-parameters.html) and the answer is - you don't, because you shouldn't know/assume the resolve chain.

However, I'm pretty sure you could do something [like the way we show an example of log4net integration](https://autofac.readthedocs.io/en/latest/examples/log4net.html) where you have a module that dynamically adds a parameter to the registration based on the consumer's parameters/properties. That example uses the limit type of the thing being resolved to get a log4net instance for the type, but it's easy enough to go from the limit type to getting constructor parameters to getting the names of those parameters. Seems like it'd be simple enough to build on the example.

**Comment by rhyous** [comment]
Thanks. Here is what I did:

```
    public interface INamedFactory<T>
    {
        T Create(string name);
    }

    public class NamedFactory<T> : INamedFactory<T>
    {
        private readonly ILifetimeScope _Container;

        public NamedFactory(ILifetimeScope container)
        {
            _Container = container;
        }

        public T Create(string name)
        {
            return _Container.ResolveNamed<T>(name);
        }
    }
```

```
    
    // Register the Generic factory
    builder.RegisterGeneric(typeof(NamedFactory<>))
       .As(typeof(INamedFactory<>))
       .SingleInstance();

    // Register the EntityClients
    foreach (var entity in _EntityList.EntityNames)
    {
        builder.RegisterType<EntityClientAsync>()
               .Named<IEntityClientAsync>(entity)
               .SingleInstance();
    }
```

To use it was simple:

```
    public class DependentOnUserEntity: IDependentOnUserEntity
    {
        private readonly IEntityClientAsync _userEntity;

        public DependentOnUserEntity(INamedFactory<IEntityClientAsync> entityClientAsyncFactory)
        {
            _userEntity= entityClientFactory.Create("User");
        }
    }
```

**What I like:**
- It is very little code.
- It is easy to do
- Now any class that depends on a specific entity's EntityClientAsync can tell the factory exactly which Entity it needs an EntityClientAsync for.

**What I don't like.**
- Every class that referenced an EntityClientAsync had to be changed to reference a NamedFactory<EntityClientAsync>.
- Every class now depends on a factory, something it really doesn't need, it just needs the correct EntityClientAsync.

Despite those two dislikes, it is working and it isn't doing a "by convention" hack.
