### ISSUE TITLE
Autofac disposed error

### ISSUE THREAD

**Issue by kKen94** [autofac/Autofac#1084]
I have a problem: the service provider is disposed when arrives in the method.
Is this an issue or it is my fault?

I apologize if this is not an issue but i cannot access to my dbContext in no way

My service

```
public class BomService
{
    private readonly IServiceScopeFactory _scope;

    public BomService(IServiceScopeFactory scope)
    {
        _scope = scope;
    }

    public void ImportAsync(ImportRequestDto importSettings)
    {
         Task.Run(async () => await ImportFile.ImportAsync<Bom, CatalogContext>(_scope));
    }
}
```

```
public static async Task ImportAsync<T, TContext>(IServiceScopeFactory parentScope) where T : class where TContext : DbContext
{
     using var scope = parentScope.CreateScope();
     var repo = scope.ServiceProvider.GetService<IGenericRepository<T, TContext>>();
}
```

The error:

`Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed`

**Comment by tillig** [comment]
This appears to be `Autofac.Extensions.DependencyInjection` because Autofac itself doesn't have an `IServiceScopeFactory` and isn't an `IServiceProvider` so if there's an issue then it likely needs to be [in that repo](https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues).

However, this appears to be more of a "how do I...?" usage question - you have some custom code, it's not working, you need help. [As noted in the issue template, please ask these questions on StackOverflow and tag them `autofac`](https://stackoverflow.com) Also tag your question with the type of application (e.g., ASP.NET Core) you're working with, and try to put the code in your question as a unit test, something self-contained that could be copy/paste and run. It will help you get answers faster.
