### ISSUE TITLE
Async interceptors

### ISSUE THREAD

**Issue by drauch** [autofac/Autofac#1122]
As I recently run into the problem, I want to rethink https://github.com/autofac/Autofac/issues/856 . Castle.Core is not going to give us a solution and I think many Autofac users need one.

Would you care about a new Autofac.Extras package that provides the availability to intercept async methods?

I've sketched an approach here https://github.com/drauch/AsyncInterceptor and you can see in my test how one could use it here: https://github.com/drauch/AsyncInterceptor/blob/master/AsyncInterceptor.Tests/AsyncInterceptorBaseTest.cs

Is this something you would consider adding as an Extras package?

Best regards,
D.R.

**Comment by drauch** [comment]
Side note: I know you as people that put heavy focus on code quality, and I'm a huge fan of this style of software engineering. Consider my implementation a rough sketch which can be discussed and which probably needs refactoring.

**Comment by tillig** [comment]
I haven't had a chance to look yet, but I'd like to encourage the community to own their own extension packages and not necessarily push them all to be owned by the Autofac organization. We already have quite a lot to maintain and part of the benefit of the extensibility of Autofac is that folks can create and maintain these sorts of extensions outside official channels.

**Comment by tillig** [comment]
Which isn't to say we _definitely won't_ take something like this, but it'd be valuable to consider that if there's a need not addressed and there's someone who needs it bad enough to write the code... that person / team might be best suited to longer-term ownership.

**Comment by drauch** [comment]
I can relate to that post, I would be willing to maintain the Extras library. You can take your time to discuss whether this is something Autofac should support semi-officially by an Extras library or not and keep me posted. If you decide to not go with it, I'm not going to be cross about it.

**Comment by tillig** [comment]
This doesn't look like it actually needs Autofac at all - it's an abstract implementation of the `Castle.DynamicProxy.IInterceptor` interface, which could be used entirely outside any Autofac scenario. That might be generally useful... and it [looks like other folks think so, too](https://github.com/JSkimming/Castle.Core.AsyncInterceptor). That repo [gets linked from the official Castle.Core issue on async interceptors, too.](https://github.com/castleproject/Core/issues/145#issuecomment-476017070) Maybe you don't need to write or own any of this.

Since it both looks like it already exists _and_ isn't actually Autofac-specific anyway, I'm going to close this. I don't think it's something we'd want to take on at this time.

**Comment by drauch** [comment]
> This doesn't look like it actually needs Autofac at all
Indeed.

> Maybe you don't need to write or own any of this.
I've looked at the other implementations but they have their own shortcomings (also, to my up-to-date-then-knowledge, they had blocking code inside their interceptor implementation).

> Since it both looks like it already exists and isn't actually Autofac-specific anyway, I'm going to close this.
OK.
