### ISSUE TITLE
Add RegistrationSource base class to simplify custom implicit relationships

### ISSUE THREAD

**Issue by twsouthwick** [autofac/Autofac#1142]
I recently needed to implement my own implicit relationship and found it a bit more challenging than I expected. The challenges I hit were:

- Metadata order is not easily retrieved with public APIs
- Some of the type helpers are not available

I was able to work around these, but I think there is an opportunity for a simple, extensible API for simple use cases like this. This would be to create implicit relationships similar to `Lazy<T>`, `Owned<T>`, and others.

Here's an example API:

```csharp
  public abstract class RegistrationSource : IRegistrationSource
    {
        private static readonly MethodInfo CreateRegistrationMethod = typeof(RegistrationSource).GetTypeInfo().GetDeclaredMethod(nameof(CreateRegistrationInternal));

        private readonly Type _type;

        protected RegistrationSource(Type type)
        {
            _type = type;
        }

        public abstract bool IsAdapterForIndividualComponents { get; }

        public abstract string Description { get; }

        protected abstract object CreateRegistration<T>(IComponentContext ctx, ResolveRequest request)  where T : notnull;

        protected virtual IRegistrationBuilder<object, SimpleActivatorData, SingleRegistrationStyle> BuildRegistration(IRegistrationBuilder<object, SimpleActivatorData, SingleRegistrationStyle> registration);
    }
```

This is modeled after the `LazyRegistrationSource`. I have a working example at https://github.com/twsouthwick/Autofac/tree/simple-registration-source where `Lazy<T>`, `Meta<T>`, and `Owned<T>` all use this instead of duplicating code themselves.

I may have missed some aspect of this, but would like to start a discussion to add this API.

**Comment by alistairjevans** [comment]
I like this idea; there is definitely some duplication between the registration sources, which would be good to cut down on.

Some thoughts, having looked at the API, and your example implementation:

- Rather than call it `RegistrationSource`, perhaps call it `ImplicitRelationshipSource`, or something like that. This base class is only suitable for a specific simple subset of cases, rather than all source types; the name should probably suggest as much.
- The `CreateRegistration` method name is potentially confusing, because it doesn't actually create an `IComponentRegistration`, but the instance itself. This conflicts with other methods we have where `CreateRegistration` creates an `IComponentRegistration`. It may be better to call it `ResolveInstance`.
- I believe that if the base class is only going to be used for what are typically considered 'implicit relationships', then `IsAdapterForIndividualComponents` will (should?) always be true; perhaps simply make it virtual and default to true?
- In your example implementation, you resolve a new `IComponentContext` in all cases, however this is only necessary for the `Lazy<T>` relationship, which must capture a context to be used later; the other types don't need that, so that extra resolve would need to be moved 'down' into the `LazyRegistrationSource`.
- We would probably want some kind of validation in the abstract class constructor that requires the type supplied be an open generic with the right number of parameters.

On the whole I think this would be a handy addition; I'm trying to think of any risks of making it _easier_ for people to create their own implicit relationships, but I can't immediately think of any.

**Comment by tillig** [comment]
Agreed, I think this is a pretty good idea.

> We would probably want some kind of validation in the abstract class constructor that requires the type supplied be an open generic with the right number of parameters.

Is there any use case where there's an implicit relationship that wouldn't be generic?

I feel like an implicit relationship is somewhat like a decorator, in that you go from `T` to `Lazy<T>` and the `Lazy<>` sort of "decorates" the `T` by changing the lifetime scope. I'm curious if there's a possible relationship that isn't exposed by a generic type.

I mean, _likely not_, or at least, having that as a requirement here wouldn't be overly cumbersome. Just thinking out loud.

Otherwise, yeah, I think having a base class for these things that would also allow folks to more easily implement their own would be cool.

I would caution against opening up too many of the type helpers. I don't mind supporting Autofac API, but I'm afraid of having to also support a "shadow API" full of additional helpers and extension methods that are only there for internal implementations yet happened to be "convenient" to enable for others. Removing those once we open them up is just as breaking as changing a `ContainerBuilder` method, albeit with potential for less risk of someone consuming them.

I could see a potential need to organize those pubternal sort of helpers into a better namespace/location to more easily take stock of what we're allowing out. Not now, maybe v6 or something.

**Comment by twsouthwick** [comment]
Thanks for the feedback. I've addressed those concerns and will open a PR
