### ISSUE TITLE
Split RegistrationExtensions into partial classes

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Autofac#1153]
As noted in #1152, the `RegistrationExtensions` class, that contains all the extension methods for supporting our various registration modes and features has gotten pretty huge.

Proposal is to split it into separate files against the same partial class. For example:

- RegistrationExtensions.Generics.cs
- RegistrationExtensions.Decorators.cs
- RegistrationExtensions.Composites.cs
- etc

Will target for v6.

**Comment by RaymondHuy** [comment]
I can help on this one :)

**Comment by alistairjevans** [comment]
There's now been a lot of changes to `RegistrationExtensions` in the v6 branch, so you'll want to start from there rather than develop; otherwise merging will be painful.

**Comment by RaymondHuy** [comment]
yes I know, I am working on v6 branch :)

**Comment by eugbaranov** [comment]
Hi, just wondering if separately named static classes would be better?

E.g. standalone `DecoratorRegistrationExtensions` class instead of same `RegistrationExtensions` class in `RegistrationExtensions.Decorators.cs`?

**Comment by alistairjevans** [comment]
I understand the value in that, and if this was new work I'd be all for it, but if we do that for `RegistrationExtensions` then it's more breaking change that people will have to adapt to when they take v6 (for example if they invoke the class manually from their own extension method, a rename will be needed).

I'm not sure that placing it in separate classes gives us enough benefit over partial classes to justify that amount of breaking change.

**Comment by eugbaranov** [comment]
Fair enough - I just was under the impression that this breaking change would be negligible (and trivial to fix) in comparison with other breaking changes v6 have already.

Also, calling extension methods in this way arguably is not the best practice.

**Comment by alistairjevans** [comment]
The other breaking changes are less likely to hit a wide percentage of users; they tend to exist in custom registration sources or constructor selectors, which you will usually only create if you really know what you're doing.

However I expect a lot of people may create simple wrappers or similar for registration behaviour in their app (I know I have), and things not being best practice has never stopped people before...

**Comment by tillig** [comment]
Agreed, I think the majority case is folks using the registration extensions rather than the internals that have changed. The breaker with the extension methods is really less about "I can update Autofac in _my app_ and recompile" and more about "I take a dependency on something that integrates with Autofac and I can't recompile _that thing_, but _that thing_ is linked against `RegistrationExtensions` static methods for extensions."

For example, _hypothetically speaking_ if we haven't changed the interface or extension methods in v6 that are commonly used, our integration libraries may not actually need to be recompiled against v6 - they may "just work" (we'll have to test that). That'd be a nice change from when we had to recompile everything down the whole stack for v5.

**Comment by RaymondHuy** [comment]
I have just split this class in this PR (https://github.com/autofac/Autofac/pull/1158) Can you check if it's satisfied or we need to split more :)

**Comment by alistairjevans** [comment]
Looks like we're good; each file is nice and small now; thanks!
