### ISSUE TITLE
Autofac 5.x issues with project with .NET 2.0 library reference

### ISSUE THREAD

**Issue by Jaben** [autofac/Autofac#1167]
## Describe the Bug

Strange issue: when we upgraded to Autofac 5.2 (from Autofac 4.9.4) on a project that uses an old .NET 2.0 library (it uses COM+ and requires 32bit if that matters) -- and it won't work anymore.

## Steps to Reproduce

Sorry -- I don't have a NET 2.0 lib to test.

## Expected Behavior

Not throw an exception.

## Exception with Stack Trace

![image](https://user-images.githubusercontent.com/448726/87482772-1e5e0800-c600-11ea-81bf-cc10bfa9ccb7.png)

## Dependency Versions

Autofac: 5.2

## Additional Info

Works fine on Autofac 4.9.4

Thank you for all your hard work on the great and excellent Autofac!

**Comment by tillig** [comment]
Autofac 5.0 was a major release with several breaking changes, including, but not limited to - the lowest .NET we support is .NET 4.6.1. [Here are the release notes.](https://github.com/autofac/Autofac/releases/tag/v5.0.0)

We no longer support anything below that (and, honestly, neither does Microsoft). The .NET 2.0 mention sorta worries me on another level - WCF was .NET 3.5, which wasn't a different runtime, per se, but would mean you still may run into weird compatibility problems regardless.

If you can provide us a repro where it's using .NET 4.6.1 or higher, we can look into it; otherwise, the best we can offer you until you can upgrade to a later .NET is to stay on Autofac 4.9.4.

For reference, Autofac 6.0 will drop .NET 4.6.1 specific support and be entirely `netstandard2.0` and `netstandard2.1`, which is still .NET 4.6.1 compatible but there are some NuGet edge cases around it.

I'm going to mark this issue as pending input - we will need a repro as noted. If you are unable to provide that, we'll close the issue in a few days.

**Comment by Jaben** [comment]
The project is .NET 4.6.1 -- but I think there are compatibility issues with the older library. That project will have to remain stuck on Autofac 4 until dependencies get upgraded/removed.

Thanks for fast response!
