### ISSUE TITLE
Support IHasParameter<T> to propertyinject a parameter instead of using reflection and NamedParameter or TypedParameter when resolving classes

### ISSUE THREAD

**Issue by BrayanKhosravian** [autofac/Autofac#1216]
## Problem Statement

I didnt read the full source code of autofac tbh and this is more like an idea.
During development I found a very simple way to inject a parameter without using any reflection and I want to share this idea.

I implemented that by wrapping an `IContainer`.

## Desired Solution

The issue with this solution is that we will get a `NullReferenceException` when we try to access the Parameter from the constructor of the service as the parameter is property injected after instantiating the service.
But I think when we would assign the parameter first and the call `IStartable.Start()` then the client could access the property and all other dependencies in that Start method.

```cs
interface IHasParameter<T>
{
	public T Param { get; set; }
}

public class SomeComponentWithParameter : IHasParameter<SomeComponentWithParameter.Parameter>
{
	public Parameter Param { get; set; }

	public class Parameter
	{
		public Parameter(string text, int number)
		{
			Text = text;
			Number = number;
		}

		public string Text { get; }
		public int Number { get; }
	}
}

class IoC
{
	private readonly IContainer _container;

	public IoC(IContainer container)
	{
		_container = container;
	}

	public void ResolveWithParameter<TService, TParameter>(TParameter parameter)
	{
		var service = _container.Resolve<TService>();

		if (service is IHasParameter<TParameter> hasParameter)
			hasParameter.Param = parameter;

	}
}
```

**Comment by tillig** [comment]
Thanks! I'm not sure we can do much with this at the Autofac level for a couple of reasons:

**People don't want ties to the DI framework.** There's a bit of effort involved in ensuring that the code folks write for their apps doesn't actually have to reference the DI framework itself. It's one reason we don't really support attribute-based registration like MEF had. This is important because...

**This works without reflection because Autofac 'knows about it'.** The magic here is the part where it checks `if (service is IHasParameter<TParameter> hasParameter)` and then something _just knows_ that by virtue of the interface being there, that also means the object has a property of a certain name/type/quantity. To know everything about this interface without reflection, it'd have to be an interface provided by Autofac... which means folks consuming it would have ties to the DI framework (which most don't want).

It'd also mean you have to "implement" that interface for every property you have on an object that you might need to populate. Any time you add a new property, don't forget to add the interface or it won't work.

Once you start thinking about that, you start thinking about scale. How do you provide more than one property value when resolving? What about properties of mixed types, like a string property and an int property?

`public void ResolveWithParameters<TService, TParameter1, TParameter2, TParameter3>(...)`

In the end, after you work all the way through this... you have to use reflection to get the job done.

**However, if this works really well for you, that's awesome!** We try to make things extensible for you so you can put stuff like this in your own codebase.

If you do keep it, I'd recommend looking at extension methods instead of decorators around the container. It will be easier to add new functionality independently and will be easier to isolate and test.

```c#
public static class ContainerExtensions
{
	public TService ResolveWithParameter<TService, TParameter>(this IContainer container, TParameter parameter)
	{
		var service = container.Resolve<TService>();
		if (service is IHasParameter<TParameter> hasParameter)
			hasParameter.Param = parameter;
		return service;
	}
}
```

**Comment by BrayanKhosravian** [comment]
Thank you for your response, the clear explanation and your thoughts!
I think I learned a lot!

And I think this statement has the most weight `There's a bit of effort involved in ensuring that the code folks write for their apps doesn't actually have to reference the DI framework itself`.
And I didnt think that far.

But I have to say that with my suggestions it won't be necessary to think about how to pass multiple parameters to a resolving class as we would always pass an instance of one class which wraps all values/parameters.

And thanks for mentioning extension methods.
