### ISSUE TITLE
RegisterAssemblyTypes - not working correctly  (.netCore 5)

### ISSUE THREAD

**Issue by kilroyFR** [autofac/Autofac#1243]
hey there, i am using autofac for years now in .net; 
recently updated to .net5.

So far i never had any issues registering assembly types (using the autofac integrated mechanism).

So far i have code that look like this.

```
    public static void Main(string[] args)
    {
      var main = new ScheduledTask();

      main.CreateHostBuilder(args);
      // Register types (IOC) in addition to SERVICES/IDbContext/IDbContextFactory
      main.HostBuilder.ConfigureContainer<ContainerBuilder>((hostingContext, container) => 
      { 
        var path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

        Directory.GetFiles(path, $"*.SERVICES.dll").Select(Assembly.LoadFile).ToList();
        var assemblies = AppDomain.CurrentDomain.GetAssemblies().Where(q => q.GetName().Name.ToUpper().EndsWith($".SERVICES"));

// NOT WORKING
// THIS CODE CORRECTLY SCANS DLLS and FIND ENTRIES but these does not match 
// ex : the CardAccountServices service is not being resolved
        foreach (var assembly in assemblies)
        {
          // Application Domain Services ONLY
          container.RegisterAssemblyTypes(assembly)
            .Where(t => t.Name.ToUpper().EndsWith("SERVICES"))
            .AsImplementedInterfaces();
        }  

        // WORKING
        // If i register "manually", uncommenting  next command line, registration for that service is correctly done and can be later resolved
        //container.RegisterType<CardAccountServices>().As<ICardAccountServices>();
      });
      main.Run(args);
    }
```

My CreateHostBuilder() is very classic and looks like this : 

```
 public IHostBuilder CreateHostBuilder(string[] args)
    {
      HostBuilder = Host.CreateDefaultBuilder(args);

      var configuration = new ConfigurationBuilder()
      .AddCommandLine(args)
      .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
      .AddEnvironmentVariables()
      .Build();

      HostBuilder.ConfigureAppConfiguration((hostContext, config) =>
      {
        config.Sources.Clear();
        config.AddConfiguration(configuration);
      });

      // Start as Windows Service
      HostBuilder.UseWindowsService();

      // Autofac
      HostBuilder.UseServiceProviderFactory(new AutofacServiceProviderFactory());

      // Logging
      HostBuilder.ConfigureLogging(logging =>
      {
        logging.ClearProviders();
        logging.AddSerilog(dispose: true);
      });

      // Main service
      HostBuilder.ConfigureServices((hostContext, services) =>
      {
        services.AddHostedService<TService>();
      });

      return HostBuilder;
    }
```

**Comment by kilroyFR** [comment]
When inspecting container, i am getting this for the (deferred) registrations : 

![image](https://user-images.githubusercontent.com/31513956/103660607-160ed600-4f6e-11eb-9656-e789e063e378.png)

For the container.RegisterType() i can see them listed in the container.

![image](https://user-images.githubusercontent.com/31513956/103660461-e6f86480-4f6d-11eb-96e0-7681a5ae9433.png)


The function is called in a delegate (in configureContainer), the way it's generally performed on .netCore

**Comment by kilroyFR** [comment]
cross posted on autofac dependancy injection too (but i think it's more an autofac issue).
Never had any problems on .net 4.x (loading assembly then scanning using autofac feature).

**Comment by tillig** [comment]
Please don't cross post. I answered there, too - ask questions on Stack Overflow, report issues we can reproduce and have been absolutely determined to be Autofac problems here.

**Autofac doesn't do any assembly loading** - if the type isn't found, it's because it's not loaded. You need to do some troubleshooting on your own outside of the Autofac piece - try using reflection to get the type and its dependencies out of the scanned assembly yourself, for example. If something is missing and can't be found (like if the interface isn't in a loaded assembly) then Autofac won't just fix that for you - that's your code. Also look at [assembly load context](https://docs.microsoft.com/en-us/dotnet/framework/deployment/best-practices-for-assembly-loading) - LoadFile is different than LoadFrom, for example, and a lot happens with Fusion and assembly loading to magically load the right assemblies... None of which is Autofac. [We can only scan types that won't throw an exception](https://github.com/autofac/Autofac/blob/e662b6bace37a569eec1e42335336b3fe015855c/src/Autofac/Util/AssemblyExtensions.cs#L27) and we don't let failures bubble up.

**Comment by kilroyFR** [comment]
Just wanting to inform that the problem has been fixed using `LoadFrom `instead of `LoadFile` to load assemblies (using the Load assembly feature to load assembly that are not directly referenced).
Works like a charm (as it was on 4.x).

PS : yes sorry for double post
