### ISSUE TITLE
CLS Compliance warnings for version 6.1.0.0

### ISSUE THREAD

**Issue by donovan-ecargo** [autofac/Autofac#1245]
## Bug background

When referencing a public class from the Autofac library, such as `Module`, the compiler generates warnings stating that base type 'Module' is not CLS-compliant.

Full list that can create the CLS-compliance warnings encountered:

1. Module
2. ContainerBuilder
3. IComponentContext
4. IModule
5. IContainer

## MRE that generates CLS compliance warnings

```c#
using Autofac;
using System;
using ClassLibrary1;

[assembly:CLSCompliant(true)]
namespace ConsoleAppAutofacRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var module = new MyModule();
            Console.WriteLine("Hello World! " + module);
        }
    }
}

namespace ClassLibrary1
{
    public class MyModule : Module
    {
        public MyModule()
        {
            var builder = new ContainerBuilder();
        }
    }
}
```

## Expected Behavior

Ideally the public types shouldn't raise CLS warnings

## Exception with Stack Trace

Message from MRE should be:

```text
  Program.cs(20, 18): [CS3009] 'MyModule': base type 'Module' is not CLS-compliant
```

## Dependency Versions

Autofac: 6.1.0.0

**Comment by tillig** [comment]
As of Autofac 6.0 we're no longer CLS compliant because [DiagnosticSource, used for our new diagnostics support](https://github.com/autofac/Autofac/commit/8f01e366d6fbe449d0a08befaaafd399ff588a87#diff-79ef6bf26b0da222caa56959e0aeb186be47f79af506026d9ee9b194b2783dfa) is not CLS compliant. There is no plan to bring that back. I'll have to add that to the list of breaking changes in 6.0 if it's not already there.

**Comment by donovan-ecargo** [comment]
Thanks, I apologize if I missed it in the breaking changes list

**Comment by tillig** [comment]
No worries, it wasn't there. I just added it. Sorry if that was confusing. I meant to add it and just forgot. :(
