### ISSUE TITLE
Keyed registrations resolved incorrectly under load in Web API

### ISSUE THREAD

**Issue by edking** [autofac/Autofac#1249]
## Describe the Bug

The problem I have seen appears to be dependent on the class/interface hierarchy. I have tried to strip it down as much as I can. Under most circumstances, the attached class hierarchy resolves just fine.  But, under certain high load conditions, the database references will resolve to the wrong database.  That is, when it goes wrong, I'll get an instance of Service2(DB1) or an instance of Service1(DB3).

This is not a high frequency behavior. It only seems to occur under load, and even then only about 0.1% of the time.  Changing the class hierarchy such that IProvideOtherStuff no longer inherits from IProvideStuff makes the problem no longer occur.

## Steps to Reproduce

```C#
public interface IProvideStuff
{
}

public interface IProvideOtherStuff : IProvideStuff
{
}

public interface IDoStuff
{
}

public interface IDoSomeStuff : IDoStuff
{
}

public interface IDoOtherStuff : IDoStuff
{
}

public class Service1 : IProvideStuff
{
  public Service1(IDatabase dba, IDatabase dbb);
}

public class Service2 : IProvideOtherStuff
{
  public Service2(IDatabase dba);
}

public class Worker1 : IDoSomeStuff
{
  public Worker1(IProvideStuff svc1);
}

public class Worker2 : IDoOtherStuff
{
  public Worker2(IProvideOtherStuff svc2)
}

public class Controller1
{
  public Controller1(IDoSomeStuff worker);
}

public class Controller2
{
  public Controller2(IDoOtherStuff worker);
}

///  registrations
// ...

public class Registrar
{
  public void RegisterStuff(ContainerBuilder builder)
  {
    builder.Register<IDatabase>(c => new Database(DatabaseKey.DB1.ToString()))
           .Keyed<IDatabase>(DatabaseKey.DB1)
           .InstancePerLifetimeScope();
    builder.Register<IDatabase>(c => new Database(DatabaseKey.DB2.ToString()))
           .Keyed<IDatabase>(DatabaseKey.DB2)
           .InstancePerLifetimeScope();
    builder.Register<IDatabase>(c => new Database(DatabaseKey.DB3.ToString()))
           .Keyed<IDatabase>(DatabaseKey.DB3)
           .InstancePerLifetimeScope();

    builder.Register<Service1>(c => new Service1(c.ResolveKeyed<IDatabase>(DatabaseKey.DB1),c.ResolveKeyed<IDatabase>(DatabaseKey.DB2)).As<IProvideStuff>();
    builder.Register<Service2>(c => new Service2(c.ResolveKeyed<IDatabase>(DatabaseKey.DB3)).As<IProvideOtherStuff>();
    builder.RegisterType<Worker1>.As<IDoSomeStuff>();
    builder.RegisterType<Worker2>.As<IDoOtherStuff>();

    builder.Register(c => new Controller1(c.Resolve<IDoSomeStuff>()));
    builder.Register(c => new Controller2(c.Resolve<IDoOtherStuff>()));
  }

  private enum DatabaseKey
  {
    DB1,
    DB2,
    DB3
  }
}

```

## Dependency Versions

Autofac: 6.1.0
Autofac.WebApi2 6.0.1

**Comment by tillig** [comment]
It appears that text file is C# code that contains the repro. It appears you somewhat ignored the new issue template here, which shows you how to put the code into proper markdown blocks so we can more easily help you.

Can you revisit the issue template and fill that out for us, including all repro code in proper markdown? Thanks.

**Comment by edking** [comment]
Thanks!  I added the code to the original post.  (I had originally attached it just because of the length.)

**Comment by tillig** [comment]
I went ahead and finished the update to the ticket template. Much as it seems pedantic, it does make it easier to scan/read the issues and find stuff.

I don't see anything here that raises any red flags. It doesn't seem like there's any accidental `AsImplementedInterfaces()` registrations going on here, which would have been my first guess.

My second guess would be that there are potentially other things in the app that you're not considering but affect things. For example, I've seen issues where folks have assembly scanning register some things and sometimes during app startup the list of enumerated assemblies shows up in a different order and yields a different set of registrations/overrides. Or [the set of assemblies changes after IIS restart](https://autofaccn.readthedocs.io/en/latest/faq/iis-restart.html) and things change (which can also happen under load as w3wp scales out, etc.).

It may be worth you trying to run it [using our new diagnostics](https://autofaccn.readthedocs.io/en/latest/advanced/debugging.html#diagnostics). It will generate **a lot of data** but it might be valuable for seeing what the actual resolution chain looks like when you get values you think you shouldn't be getting. To reduce the sheer quantity of data, you might create a custom tracer that only dumps data if one of the types you're interested in is part of the resolve chain. [Start with `DefaultDiagnosticTracer` and override/filter from there.](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Diagnostics/DefaultDiagnosticTracer.cs)

But, like I said, I don't see anything here that's obvious, and since we can't directly repro it (i.e., you didn't provide any sort of unit test or mechanism where we can actually see the issue) there's not much we can actually _do_. I'll leave it open pending additional info for a while, but, unfortunately, we may be limited in our abilities to do anything from this end.

**Comment by edking** [comment]
This is a low frequency, intermittent problem which only occurs under Production-level load.  We have never seen the issue anywhere except for our Production environment.  I will see what I can do about creating enough load to recreate the problem, and collect diagnostics, outside of a Production server.

**Comment by tillig** [comment]
This has been pending some input since January. Since we're going on almost a year without any updates and no way to repro or fix it, I'm closing the issue. If we get something we can repro and fix, we can reopen.
