### ISSUE TITLE
Module-defintions are not respected

### ISSUE THREAD

**Issue by DMDTT** [autofac/Autofac#1251]
## Describe the Bug

Class/interface is defined in AssemblyB. If AssemblyA has an autofac-module which defines the behaviour of Class of AssemblyB the scopes like e.g. SingleInstance() is not respeced

## Steps to Reproduce

Definition of a scope of a type in an assembly which does not provide the type (has it not implemented)

## Expected Behavior

The instance should be the same, no matter where it's scope is defined?
**OR**

The behaviour is intended, as the assembly scanning (external lib is scanned later) of external assembly overwrites the scanning of type-Class1 as there is no module definition.

## Dependency Versions

Autofac: 6.1

### Program.cs
```c#
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using Autofac;
using AutofacLifetimeIssueExternalLib;

namespace AutofacLifetimeIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            ContainerBuilder container = new ContainerBuilder();
            var files = Directory.GetFiles(AppDomain.CurrentDomain.BaseDirectory);

            foreach (var assembly in files.Where(x => 
                x.EndsWith("AutofacLifetimeIssue.dll") || 
                x.EndsWith("AutofacLifetimeIssueExternalLib.dll")).Select(Assembly.LoadFrom))
            {
                container.RegisterAssemblyTypes(assembly).PublicOnly().AsImplementedInterfaces();
                container.RegisterAssemblyModules(assembly);
            }

            var container2 = container.Build();
            Console.WriteLine(container2.Resolve<IClass1>().GetHashCode());
            Console.WriteLine(container2.Resolve<IClass1>().GetHashCode());
        }
    }
}
```

### Class1
```c#

using System;

namespace AutofacLifetimeIssueExternalLib
{
    public interface IClass1
    {
    }

    public class Class1 : IClass1
    {
    }
}
```

### IocModule Executing Assembly
```c#
using Autofac;
using AutofacLifetimeIssueExternalLib;

namespace AutofacLifetimeIssue
{
    public class IocModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            //builder.RegisterType<Class1>().As<IClass1>().SingleInstance();
        }
    }
}
```

### IocModule External Assembly
```c#
using Autofac;

namespace AutofacLifetimeIssueExternalLib
{
    public class IocModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterType<Class1>().As<IClass1>().SingleInstance();
        }
    }
}

```

**Comment by tillig** [comment]
Let me make sure I understand what I see:

1. Get the list of files from the app directory, which aren't in any guaranteed order and aren't sorted.
2. Select two different assemblies by name and load them, again not in a guaranteed order. It's also unclear what the name of the current application assembly is so one of these could be re-loading the app assembly instead of just referencing the current assembly directly.
  a. If it's the `AutofacLifetimeIssue.dll` then register all public types as implemented interfaces (it doesn't appear there are any?) and then register an empty module.
  b. If it's the `AutofacLifetimeIssueExternalLib.dll` then register all public types as implemented interfaces and then register a module that will override the `IClass1` definition and make it a singleton.
3. Resolve `IClass1` twice and write some hash codes to the console.

What actually comes out from the console wasn't included, so I'm not sure what you're seeing to compare with what you're expecting. I will say:

- [`Directory.GetFiles` docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=net-5.0) specifically note that "The order of the returned file names is not guaranteed; use the Sort method if a specific sort order is required." Thus, you aren't actually guaranteed to get the same result each time you run this code because the files may or may not be returned in the same order.
- Last in wins. Always. If you register a service `IClass1` and then register a module that _also_ has `IClass1` in it, the registration from the module will override the previous registration.
- `GetHashCode` here for a quick check is probably fine, but [hash code equality doesn't mean object equality](https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=net-5.0). If you're ever doing this "for real," check `Object.ReferenceEquals` to ensure the objects are actually the same.
- I'd personally avoid doing a `LoadFrom` on the current executing assembly. It's already loaded and I've run into no end of trouble with weirdness in the past around loading assemblies in different contexts and having the same _named type_ actually end up referencing _two different things_. That may not be happening here, but... just be careful. The current assembly is `typeof(Program).Assembly`. I'd use that if I were you.

So... what are you actually seeing and what do you expect? As in, what do you see _in the output here_ and what _are you expecting_? Is it different than what I described with "last in wins?"

**Comment by DMDTT** [comment]
@tillig thanks for your reply, in fact the order of the module/assembly scan is the "problem"

 Is it different than what I described with "last in wins?"
--> indeed not, so everything is fine, and this issue could be closed
