### ISSUE TITLE
Enable injecting service from parent lifetime in case of a circular dependent type

### ISSUE THREAD

**Issue by basvdlinden** [autofac/Autofac#1256]
## Problem Statement

Circular dependent type = Type that both implements and requires the same interface. (See Additional Context). 

Registering and resolving such type results in a circular dependency exception. There are scenario's where it is desired that the parent lifetime should provides an instance to satisfy the required dependency. This provides more advanced scenario's then using a decorator. E.g.:
- Decorating multiple interfaces using a single type.
- Resolving an undecorated service using Name/Keyed resolve.
- Decoration per lifetime scope using InstancePerLifetimeScope.

Currently it is not straightforward to achieve this behavior.

## Desired Solution

- Supply a ```ParentLifetimeScopeParameter<T>```
- After an opt-in, automatically resolve dependency from parent lifetime when a circular component is detected.

## Alternatives You've Considered

1) Using a decorator. A decorator also wraps named and keyed services. A decorator also wraps new registration in child lifetime. A decorator only allows for one interface can be decorated.

2) Passing the parent lifetime to the constructor of a Module and then register using a lambda that resolves the service using the parent lifetime. This introduces maintainability issues, because the parent lifetime needs to be passed around in order to provide it to the module _(This also resulted in a Memory Leak using Autofac 6.0.0 where the Module was kept in memory and thus the lifetime)_

3) Register a ```ParentLifetimeScopeAccessor```: [StackOverflow](https://stackoverflow.com/questions/51047600/how-to-resolve-from-autofac-parent-scope-without-passing-it-around-multiple-time) and provide a ```ParentLifetimeParameter``` that resolves the ```ParentLifetimeScopeAccessor``` to resolve the service.

## Additional Context

A circular dependent type:
```csharp
    interface IService
    {
        void Do();
    }

    class Service : IService
    {
        private readonly IService _service;

        public Service(IService service) => _service = service;

        public void Do() => _service.Do();
    }
```

When used as follows:
```csharp
var builder = new ContainerBuilder();
builder.RegisterType<Service>().As<IService>();
var lifetime = builder.Build();
lifetime.Resolve<IService>();
```
The result is: "Circular component dependency detected: AutofacSample.Service -> AutofacSample.Service -> AutofacSample.Service.". The [Circular-dependency documentation](https://autofaccn.readthedocs.io/en/latest/advanced/circular-dependencies.html) doesn't mention this version of circular dependency.

**Comment by tillig** [comment]
I think I need to understand more about the use case before I could say whether or not we'd support it. We do allow circular dependencies [if it's constructor/property or property/property](https://autofaccn.readthedocs.io/en/latest/advanced/circular-dependencies.html) binding, like if the dependency is injected via a property on at least one end of the relationship.

The example you provided with `IService` depending on itself - even injecting from a parent lifetime scope, the problem we'd run into is eventually you'd still have an unfulfilled dependency.

```c#
var builder = new ContainerBuilder();
builder.RegisterType<Service>().As<IService>();
using var container = builder.Build();

// Challenge 1: What comes out of the container?
// `Service` requires an `IService` injected into
// its constructor. Is it injecting itself into itself?
// Is it two different instances that get resolved
// and inject into each other?
var service = container.Resolve<IService>();

// Challenge 2: What happens as it goes up the stack?
// Here we register a different `IService` implementation
// so `Service`, from the parent lifetime scope, can
// fulfill the constructor requirement for `IService`
// in the `Service2` class. But `Service` still needs an
// `IService` also - where does that come from?
using var scope = container.BeginLifetimeScope(b => b.RegisterType<Service2>().As<IService>());
var service2 = scope.Resolve<IService>();
```

I also see a challenge with obeying lifetime scopes, which is pretty important. Let's say `Service` takes more than just an `IService` dependency.

```c#
public class Identifier
{
  public Guid Id { get; } = Guid.NewGuid();
}

public class Service : IService
{
  private readonly IService _service;
  private readonly Identifier _id;
  public Service(IService circular, Identifier id)
  {
    this._id = id;
    this._service = service;
  }
  public Guid Id => this._id.Id;
  public IService Circular => this._service;
}
```

Now we register things.

```c#
var builder = new ContainerBuilder();
builder.RegisterType<Service>().As<IService>();
builder.RegisterType<Identifier>().InstancePerLifetimeScope();
using var container = builder.Build();
using var scope = container.BeginLifetimeScope();
var service = scope.Resolve<IService>();

// As a general rule, a thing's dependencies come from
// the same lifetime scope as the thing. For example, a
// singleton gets its dependencies from the root container
// even if it's resolved from a child lifetime scope. This is
// to avoid child scope dependencies being disposed out
// from under the singleton.
//
// So what happens here?
var child = service.Id;
var parent = service.Circular.Id;
Assert.Equal(child, parent);
```

If a circular dependency is allowed to somehow come from the parent scope, then its dependencies also end up coming from the parent scope even though you'd expect them to come from the same scope as the original thing you're resolving.

It becomes really messy really quick.

So: I think I'd like to focus on the use cases and see if there are other ways to solve them.

**Case 1**: Decorating multiple interfaces using a single type

I'm not sure I totally understand why you'd want to do this. If all the interfaces you're decorating are assumedly different, the decorator would need to implement them all; and the challenge would be in figuring out which constructor to use because you'd need one constructor per interface being decorated, all in the same decorator class. Decorator is pretty much 1:1, not many:1.

If the use case is something like aspect-oriented programming, where you add logging or something to a bunch of different things "as a decorator," that's _interception_ and [we do support type interceptors](https://autofaccn.readthedocs.io/en/latest/advanced/interceptors.html).

**Case 2**: Resolving an undecorated service using Name/Keyed resolve.

It's pretty easy to provide the key during a direct resolve operation, and you can [use attribute filters](https://autofaccn.readthedocs.io/en/latest/advanced/metadata.html) if you need to filter automatically. I'm not clear how having additional circular dependency support would solve this.

**Case 3**: Decoration per lifetime scope using InstancePerLifetimeScope.

You can totally register a decorator into a lifetime scope.

```c#
var builder = new ContainerBuilder();
builder.RegisterType<Service>().As<IService>();
using var container = builder.Build();

// This isn't decorated.
var undecorated = container.Resolve<IService>();

using var scope = container.BeginLifetimeScope(b => b.RegisterDecorator<ServiceDecorator, IService>());

// This is decorated.
var decorated = scope.Resolve<IService>();
```

However, as [the docs mention](https://autofaccn.readthedocs.io/en/latest/advanced/adapters-decorators.html)...

> **You cannot specify a lifetime scope on a decorator.** The lifetime of a decorator is tied to the lifetime of the thing it decorates. The service and all decorators get disposed at the same time. If you decorate a singleton, all the decorators are also going to be singletons. If you decorate something that’s instance per request (e.g., in a web app) the decorators will also live for the whole request.

So, again, due to the way things need to get dependencies and obey scoping, there wouldn't be `InstancePerLIfetimeScope` on a decorator - you'd need to register _the thing being decorated_ as `InstancePerLifetimeScope`... but doing that should work.

If that's not what you mean here, maybe you can clarify.

**Comment by basvdlinden** [comment]
Thanks a lot for the elaborate explanations. I see now that I should have included the goal.

The improvement I am proposing is NOT about enabling cyclic dependencies. But about enabling a more advanced way of applying decoration services on other services registered in parent lifetimes.

Here a **simplification** of a solution we use in a product that I am working on:
- We use lifetime scopes as layers for flexible configuration of data storage. The services have dedicated I*Name*Source and I*Name*Target interfaces. I*Name*Source for getting data and I*Name*Target for writing data.
- We have lifetime scopes for e.g.: Unavailable -> Persistence -> Cache, where -> is a parent-child lifetime scope relation.
- For all data types we register unavailable implementations of I*Name*Source and I*Name*Target in the unavailable layer.
- Depending on access configuration we register persistence implementation of I*Name*Source and I*Name*Target in the Persistence layer.
- Depending on the type of data we register cache implementations of I*Name*Source and I*Name*Target in the cache layer.
- The persistence and cache implementations are circular dependent types. They implement the I*Name*Source and I*Name*Target interfaces and also have the same interfaces as constructor parameters. The I*Name*Source and I*Name*Target constructor parameters are resolved from parent lifetime scope.
- Example: The access configuration results in omitting I*Name*Target registration from the Persistence lifetime scope. The client resolves a I*Name*Target from the cache lifetime scope. This results in a Cache -> Unauthorized object graph. If the client wants to write data to I*Name*Target it will get a access denied exception.

I hope this explains the use-case. Making the registration for persistence and cache use the parent lifetime scope was not straight forward. 
- Idea 1 was: By having a ```ParentLifetimeScopeParameter<T>``` this would be easy. The software doesn't have to pass around parent lifetime scopes.
- Idea 2 was: If a "circular dependent type" always results in a "Circular component dependency detected" exception, then it could also be a trigger for resolving the interface from the parent lifetime scope (if option is enabled and if parent lifetime scope is available).

For a long time we used the solution where we where passing the parent lifetime to the constructor of the registration Modules. I was actually forces to find a different solution. The reason was that we upgraded to autofac 6.0.0. We had similar memory problems as described here: [link](https://github.com/autofac/Autofac.Owin/issues/25). That is when I implemented a ```ParentLifetimeScopeParameter<T>``` combined with ```ParentLifetimeScopeAccessor```: [StackOverflow](https://stackoverflow.com/questions/51047600/how-to-resolve-from-autofac-parent-scope-without-passing-it-around-multiple-time).

**Comment by tillig** [comment]
I have to admit this is a lot to unpack and I'm not totally following. It seems like a design problem if you have interfaces `INameSource` and `INameTarget` set up as circular dependencies. It doesn't sound like something Autofac should fix - it sounds like you need to change the architecture of the application and dependencies so it doesn't do this.

I think I'm stuck on the notion of respecting lifetime scope as a real key tenet of how things get injected and handled. The concept that something in a child lifetime scope could somehow generate a _circular_ dependency on something in a parent lifetime scope brings up all sorts of challenges. Disposal, as one example, becomes really tricky. I can think of some other things that get tricky, but, honestly, while we could go into all of it (perf issues? tracking what got injected where so the now-broken lifetime scope hierarchy remains somewhat consistent elsewhere?) it doesn't make sense.

I'm not really sold on the "inject the parent scope of the current scope" thing, either. We actually _very intentionally_ don't provide this sort of parent-to-child linking because it's extremely easy to introduce memory leaks. (I actually did that back in the... I think it was Autofac 3.x days. I tried to make it so you could dispose a parent scope and have all child scopes automatically cleaned up. It was... not good. For a lot of people.)

While I recognize you have an issue to solve here, **I don't think Autofac is going to be the place that solves it**. I would _strongly_ recommend looking at the way the app is architected and see if there are ways to change the structure/hierarchy such that you don't need these sorts of solutions; or, if you just can't figure it out, you'll need to create an application-specific mechanism to manage it, which it sounds like you're already working on.

**Comment by basvdlinden** [comment]
Closed. I am happy to explain further...

The solution is working fine. It just took some time to find an clean way to deal with the parent lifetime scope. I thought it could help others if it the ```ParentLifetimeScopeParameter<T>``` would be available to them.

A decorator, which is registered with ```RegisterDecorator()```, has to be implemented in an identical cyclic way. The other service that needs to be injected in the decorator can also come from a parent lifetime scope. So I don't see why the solution described above is more problematic than using the RegisterDecorator().

**Comment by tillig** [comment]
Decorators obey the lifetime scope of the thing being decorated. They're not tying two lifetime scopes together. There's also no circular dependency. The decorator depends on the thing being decorated, but not the other way around.

Circular dependencies are a nasty problem in DI already. Adding the complexity of crossing lifetime scopes... that's not territory I think we're interested in going.

If you think you can solve it...

- Without a major internals overhaul
- Ensuring people aren't going to shoot themselves in the foot with this (because we not only develop this for free in our unpaid time, we also support it for free in our unpaid time)
- Where it will behave as expected (no surprises that most devs of fairly basic skill levels won't understand or be able to troubleshoot - again, support)
- Where it won't affect performance or memory usage (keeping references, extra tracking, extra traversing through scopes, etc)

...then we'd be happy to entertain a pull request. However, I don't think we can have our cake and eat it, too, on this one. It'll require extra tracking and traversal (perf problems), it's going to cause some interesting challenges where folks won't expect that something from a child scope somehow got injected into a parent scope (support problems), and it doesn't sound like something that easy to maintain and ensure it continues working as we take the overall container forward.

To that end, it's not something that the Autofac team (of, like, three active people doing all the dev and support) will be taking on. I'm sorry that's the case, but on the list of features, bugs, and other things we're trying to manage, this sort of edge case feature that adds a ton of extra complexity just doesn't make the cut on the priority list.

**Comment by basvdlinden** [comment]
Thanks for your time! I fully support that reasoning.

For the record. Here a bare example of the solution I ended up using. 
```csharp
static class Program
{
    // Library
    internal interface IParentLifetimeScopeAccessor
    {
        ILifetimeScope ParentLifetimeScope { get; }
    }

    internal sealed class ParentLifetimeScopeAccessor : IParentLifetimeScopeAccessor
    {
        private readonly ILifetimeScope _lifetimeScope;

        public ParentLifetimeScopeAccessor(ILifetimeScope lifetimeScope)
        {
            _lifetimeScope = lifetimeScope;
            _lifetimeScope.ChildLifetimeScopeBeginning += OnChildLifetimeScopeBeginning;
        }

        public ILifetimeScope ParentLifetimeScope { get; private set; }

        private void OnChildLifetimeScopeBeginning(object sender, LifetimeScopeBeginningEventArgs e) =>
            e.LifetimeScope.Resolve<ParentLifetimeScopeAccessor>().ParentLifetimeScope = _lifetimeScope;
    }

    public class ParentLifetimeParameter<TService> : ResolvedParameter
    {
        public ParentLifetimeParameter() : base(
            (paramInfo, context) => paramInfo.ParameterType.IsAssignableFrom(typeof(TService)),
            (paramInfo, context) => context.Resolve<IParentLifetimeScopeAccessor>().ParentLifetimeScope.Resolve<TService>())
        { }
    }

    public static IContainer BuildExtension(this ContainerBuilder builder)
    {
         builder.RegisterType<ParentLifetimeScopeAccessor>()
            .AsSelf()
            .As<IParentLifetimeScopeAccessor>()
            .InstancePerLifetimeScope();

        var liftime = builder.Build();
        liftime.Resolve<ParentLifetimeScopeAccessor>();
        return liftime;
    }
    // End Library

    public interface IService
    {
        void Calculate();
    }

    public class Service : IService
    {
        public void Calculate() => Console.WriteLine("Calc");
    }

    public class Decorator : IService
    {
        private readonly IService _parent;

        public Decorator(IService parent)
        {
            _parent = parent;
        }

        public void Calculate() => _parent.Calculate();
    }

    static void Main()
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<Service>().As<IService>();
        var lifetime = builder.BuildExtension();

        using (var childLifetime =
            lifetime.BeginLifetimeScope(b => b.RegisterType<Decorator>()
                                             .WithParameter(new ParentLifetimeParameter<IService>())
                                             .As<IService>()))
        {
            childLifetime.Resolve<IService>().Calculate();
        }
    }
}
```
