### ISSUE TITLE
Simulating "abstract factory" with Autofac?

### ISSUE THREAD

**Issue by zvrba** [autofac/Autofac#1264]
## Problem Statement
When multiple components are registered to expose the same service, it'd be very convenient that registrations are tried in order until constructor arguments match. An example of what I'd like to work

```
    public class AutofacAbstractFactoryTest
    {
        [Fact]
        public void AbstractConstructorResolutionByArgumentType() {
            var cb = new ContainerBuilder();
            cb.RegisterType<ConcreteImpl1>().As<AbstractImpl>();
            cb.RegisterType<ConcreteImpl2>().As<AbstractImpl>();

            using var c = cb.Build();
            
            var i1 = c.Resolve<AbstractImpl>(new TypedParameter(typeof(ConcreteData1), new ConcreteData1()));
            Assert.IsType<ConcreteImpl1>(i1);
            Assert.IsType<ConcreteData1>(i1.D);
            Assert.Equal(1, ((ConcreteData1)i1.D).X);

            var i2 = c.Resolve<AbstractImpl>(new TypedParameter(typeof(ConcreteData2), new ConcreteData2()));
            Assert.IsType<ConcreteImpl2>(i2);
            Assert.IsType<ConcreteData2>(i2.D);
            Assert.Equal(2, ((ConcreteData2)i2.D).X);

        }

        abstract class AbstractData
        {
            public abstract int X { get; }
        }
        class ConcreteData1 : AbstractData
        {
            public override int X => 1;
        }
        class ConcreteData2 : AbstractData
        {
            public override int X => 2;
        }

        abstract class AbstractImpl
        {
            public AbstractData D { get; }
            protected AbstractImpl(AbstractData d) { D = d; }
        }
        class ConcreteImpl1 : AbstractImpl
        {
            public ConcreteImpl1(ConcreteData1 d) : base(d) { }
        }
        class ConcreteImpl2 : AbstractImpl
        {
            public ConcreteImpl2(ConcreteData2 d) : base(d) { }
        }
    }
```

Resolving `i1` fails with an exception. Resolving `i2` works as `ConcreteImpl2` was the last one registered and hence default. 

## Desired Solution

If Autofac tried ALL registrations against provided parameters, resolution would succeed.

## Alternatives You've Considered

None yet, any suggestions?

**Comment by tillig** [comment]
Much as this sounds like something interesting in this case, there are some challenges with it that mean we probably won't be looking into it.

**Last in wins.** In the current behavior, the last registration in wins. Which is to say, you can _expect_ that the thing you registered last is what will be resolved _or_ there will be an error. You can _count on that_.

```c#
builder.RegisterType<TypeA>().As<IService>();
builder.RegisterType<TypeB>().As<IService>();
//...
// This will be TypeB or an error.
var x = container.Resolve<IService>();
```

There's a lot of code out there (and internals here) that _assume that behavior_. If it changed, that'd be a lot of breaking code in the wild and a lot of stuff to change internally to make that happen.

Even if you considered an "opt in" mechanism to avoid the breakage, that'd be a super major change. How would that work? Do you have a separate call? Or do you opt in on a registration?

```c#
// Is it this?
builder.EnableSomeSortOfFallback<IService>();

// Or is it this?
builder.RegisterType<TypeA>().As<IService>(enableFallbackThing: true);

// And if it's the latter, what happens if we don't opt in on all of them?
builder.RegisterType<TypeB>().As<IService>(enableFallbackThing: false);
```

**Lifetime scope conflicts.** Let's say you have two services with this fallback mechanism...

```c#
builder.RegisterType<TypeA>().As<IService>();
builder.RegisterType<TypeB>().As<IService>().SingleInstance();
```

How would lifetime scope be handled? If `TypeB` can't be resolved, do you keep the single instance lifetime scope override and fall back to the `TypeA` component? Or do you let the whole registration fall back, lifetime scope and all, even though the override supposedly took care of also updating the scope?

**Troubleshooting**: If something goes wrong in this situation, or something is behaving unexpectedly, how do you know? You _think_ you should be getting `TypeB` because you overrode that registration, but instead you're getting `TypeA`. Why? How do you know? How do you fix it? What happens if someone somewhere else changes something in the app that causes `TypeB` to stop resolving but doesn't tell you - now `TypeA` gets resolved (with no error) and the app behavior changes in a way where you can't figure out why it changed? How do you solve that?

**Lambda registrations.** Not everything is registered with reflection. Do we _try_ to resolve lambdas and only fall back if they fail? What if it's _supposed_ to fail and cause the app to blow up?

```c#
builder.RegisterType<TypeA>().As<IService>();
buidler.Register(ctx => {
    var config = ctx.Resolve<IConfiguration>();
    var connectionString = config["connectionString"];
    if(String.IsNullOrEmpty(connectionString))
    {
      throw new InvalidOperationException("Connection string missing - check configuration!");
    }
    return new TypeB(connectionString);
  }).As<IService>();
```

**Multi-service component registrations.** You can register things with multiple interfaces.

```c#
builder.RegisterType<TypeA>().As<IService1>().As<IService2>().SingleInstance();
builder.RegisterType<TypeB>().As<IService1>().As<IService3>();
builder.RegisterType<TypeC>().As<IService2>();
// ...
// Type C fails and falls back to Type A:
var is2 = container.Resolve<IService2>(); // TypeA

// What do you get here?
var x = container.Resolve<IService1>();
```

Let's say you resolve `IService2. `TypeC` fails to resolve and falls back to `TypeA`. `TypeA` is registered as a singleton because it _must_ share the data store it holds between `IService1` and `IService2` implementations. Which is to say, if `TypeA` backs `IService2`, it _also must_ back `IService1`. However, `TypeB` is more flexible, which is why `TypeC` takes over for `IService2` in that case.

What do you expect to get when resolving `IService1`? Do you get `TypeA` because it's registered to support _both `IService1` and `IService2`_? If so, that means the expected override of `TypeB` for `IService1` isn't happening even though it'd resolve right. Do you get `TypeB` because the override will work and resolve? If so, that means you have an inconsistent backing data store because the overrides didn't work as expected.

**The point isn't to get answers to these questions, it's to show that it's not a simple thing.** It _seems_ like a simple thing to explain, but in the larger scheme of things, it's actually not that easy to implement or support. There'd be a lot of time dedicated to getting this right, and then the folks who use it would need to be supported through troubleshooting and documentation, usage questions, etc. I anticipate it'd be a fairly small number of folks actually in need of this feature since, again, the vast majority are going to want to be able to override and have a consistent experience - either the override works or it errs out.

Given that, I don't think the complexity of designing the feature + the amount of work required to implement + the amount of work required to support the feature balances out to something we'll take on. Sorry.

**Comment by zvrba** [comment]
Hi,

Thanks for the detailed post.

Two quick things.

1. Wrt registration: one could have `RegisterOverload<AbstractService>(params Type[] concreteService)` and this would behave "flexibly" ONLY for AbstractService and types mentioned in that particular call. Also, isn't the point of DI supposed to be to "not know" what concrete types you get, so the points you raise seem kind of "let's defend tight coupling". But OK, I can accept them and don't want to argue more about them.

2. More importantly, can you suggest a quick workaround? Should I resolve to `IEnumerable<AbstractService>` and do manual ctor matching with reflection? Is there something in Autofac that'd make coding this easier?

Once again, thanks.

**Comment by tillig** [comment]
> so the points you raise seem kind of "let's defend tight coupling"

You don't know what you get at the consumer side, but on the wiring-up side, you should have some predictability. I also can't vouch for the design decisions in every codebase out there - we've seen a lot of things where... I wouldn't necessarily do it that way, but it's there. So we need to keep supporting both the folks who aren't designing perfectly and those that are, and we need to do that with the limited resources we have. I think we have... three unpaid active maintainers for all of Autofac and the integration libraries at the moment?

I do not have a real workaround for this, sorry. It's not something Autofac does out of the box or considers a use case. If you resolve `IEnumerable<AbstractService>` it will try to resolve everything, not just the ones that work.

You could do something like:

```c#
var items = scope.Resolve<IEnumerable<Lazy<AbstractService>>>();
foreach(var item in items)
{
  try
  {
    var resolved = item.Value;
    return resolved;
  }
  catch
  {
    // Resolving the Lazy<T> and failing gets you here.
  }
}
```

But I can't tell you if that'd work (I haven't tried it or compiled it) and I don't know necessarily what you'd get if you started passing parameters. It's an idea, but I wouldn't bet my career on it.
