### ISSUE TITLE
Decorators usage problem

### ISSUE THREAD

**Issue by Hovo563** [autofac/Autofac#1270]
## Problem Statement

Suppose I have Repository,CachedRepository  classes which implements IRepository interface, CachedRepository is decorator for Repository. and in my code I have different usage of IRepository, in one place I want to have Repository class instance and in other place CachedRepository class instance, How can I configure autofac in Asp.Net Core 3 to get expected result. As I understand autofac does not support the real usage of decorator pattern. Am I right ? 

## Desired Solution

It will be nice to somehow configure decorators usage

**Comment by tillig** [comment]
It seems like you possibly [haven't read all the docs](https://autofaccn.readthedocs.io/en/latest/advanced/adapters-decorators.html#simplified-syntax), in particular the section about more complex decoration:

>If you want to manually instantiate your decorators or do more complex decorator creation, that’s also possible.
>
> ```c#
> builder.RegisterDecorator<ICommandHandler>(
>    (context, parameters, instance) => new ComplexDecorator(instance)
> );
> ```
>
> In the lambda, context is the IComponentContext in which the resolution is happening (so you could resolve other things if needed); parameters is an IEnumerable<Parameter> with all the parameters passed in; and instance is the service instance being decorated. Keep in mind that if you have multiple decorators being chained, instance may be a decorator instance rather than the root/base thing being decorated.

This comment somewhat troubles me:

> autofac does not support the real usage of decorator pattern

This somewhat indicates that maybe you should do some research on what the decorator pattern is. Autofac has decorator support, it follows the pattern, but it sounds like you have some incorrect assumptions on exactly how that should be handled that differ from the Autofac implementation.

Decorators are applied, in general, to _services_ not to _components_. As a refresher...

```c#
builder.RegisterType<Component>().As<IService>();
```

The component is the concrete type, the service is the thing being exposed/resolved.

This is an important distinction because the service is how you decouple your knowledge of the thing _backing the service_ and the _service itself_. If you _swap_ the `Component` for something else, the thing being resolved is still `IService` - the consumers _don't know_ that it was swapped out. It's abstraction, and it's important.

While you _can_ decorate at a component level (see that above section from the docs), doing that somewhat indicates you have a design problem - your system "needs to know" what the backing component is in order to decorate it conditionally, which means you're breaking the [Liskov substitution principle](http://en.wikipedia.org/wiki/Liskov_substitution_principle). In fact, the whole design where _sometimes_ you need one kind of repository but _sometimes_ you need that other kind, but you don't differentiate by interface... that's also a design problem. [There's a whole FAQ on why this is not good.](https://autofaccn.readthedocs.io/en/latest/faq/select-by-context.html)

If you have additional "how do I do this?" questions, please post them [to StackOverflow](https://stackoverflow.com) and tag them `autofac`. This wasn't a bug or an enhancement, and we all monitor how-to questions over there. Thanks!
