### ISSUE TITLE
IAsyncDisposable registered via RegisterInstance does not get disposed if it was never resolved

### ISSUE THREAD

**Issue by sandersaares** [autofac/Autofac#1284]
## Describe the Bug

`DisposeAsync()` is not called on an instance registered via `RegisterInstance()` if the instance is never resolved.

Works as expected for synchronous `Dispose()`.

## Steps to Reproduce

```c#
class Program
{
    static async Task Main(string[] args)
    {
        var builder = new ContainerBuilder();

        builder.RegisterInstance(new SynchronouslyDisposable());
        builder.RegisterInstance(new AsynchronouslyDisposable());

        var container = builder.Build();

        // If resolved, disposal works as expected for both.
        //var instance1 = container.Resolve<SynchronouslyDisposable>();
        //var instance2 = container.Resolve<AsynchronouslyDisposable>();

        await container.DisposeAsync();
    }
}

class SynchronouslyDisposable : IDisposable
{
    public void Dispose()
    {
        Console.WriteLine("SynchronouslyDisposable was disposed.");
    }
}

class AsynchronouslyDisposable : IAsyncDisposable
{
    public ValueTask DisposeAsync()
    {
        Console.WriteLine("AsynchronouslyDisposable was disposed.");
        return default;
    }
}
```

Output:

```
SynchronouslyDisposable was disposed.
```

Expected output:

```
AsynchronouslyDisposable was disposed.
SynchronouslyDisposable was disposed.
```

## Expected Behavior

Instances registered with `RegisterInstance` get disposed when the container/scope gets disposed, regardless of whether they implement `IDisposable` or `IAsyncDisposable` and regardless of the number of times they were resolved.

## Dependency Versions

Autofac: 6.2.0
.NET 5.0

**Comment by tillig** [comment]
Looks like we have [a test for the sync disposal](https://github.com/autofac/Autofac/blob/79bfeeffbf753a86c7907cc58abc204602ff4014/test/Autofac.Specification.Test/Lifetime/ProvidedInstanceTests.cs#L107) but not async. We should probably fix this up.

That said, [per the documentation](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)...

> It is typical when implementing the IAsyncDisposable interface that classes will also implement the IDisposable interface. A good implementation pattern of the IAsyncDisposable interface is to be prepared for either synchronous or asynchronous dispose.

Which is _not_ to say we shouldn't fix this, just that it might be good to implement both `IAsyncDisposable` _and_ `IDisposable` rather than _only_ `IAsyncDisposable`. That's the short-term workaround here. Of course, [Microsoft doesn't follow their own advice](https://github.com/Azure/azure-sdk-for-net/blob/9ee228648bcd83987b67d7207b140a3e8f8af2b6/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClient.cs#L20), so there's that. 😄

**Comment by alistairjevans** [comment]
```csharp
/// <inheritdoc/>
        protected override async ValueTask DisposeAsync(bool disposing)
        {
            if (disposing)
            {
                await _rootLifetimeScope.DisposeAsync().ConfigureAwait(false);
                
                // 🙄
                // Registries are not likely to have async tasks to dispose of,
                // so we will leave it as a straight dispose.
                ComponentRegistry.Dispose();
            }

            // Do not call the base, otherwise the standard Dispose will fire.
        }
```

Shakes fist at past me.
