### ISSUE TITLE
NamedParameter value is not used when resolving the same type in Register<> lambda as the type of the original Resolve<>

### ISSUE THREAD

**Issue by chrisbbe** [autofac/Autofac#1290]
## Describe the Bug

`Resolve<>` of service throws circular dependency exception as later `Register<>` lambda down the pipe do not take into account the `NamedParameter` value to break the circle when lambda needs to resolve the same service as the original `Resolve<>` requested.

## Steps to Reproduce

```c#
public class Tests
{
    public class A
    {
        public A(B? b = null)
        {
        }
    }

    public class B
    {
    }

    private readonly IContainer _container;

    public Tests()
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<A>().SingleInstance();

        builder.Register(ctx =>
        {
            var a = ctx.Resolve<A>(new NamedParameter("b", null!));
            return new B();
        }).As<B>().SingleInstance();

        _container = builder.Build();
    }

    [Fact]
    public void NotWorking()
    {
        _container.Resolve<A>();
    }

    [Fact]
    public void Working()
    {
        _container.Resolve<B>();
        _container.Resolve<A>();
    }
}
```

## Expected Behavior

`Resolv<A>` should cause the `Register<B>` lambda expression to resolve `A` with the named parameter as specified, breaking the circular dependency.

## Dependency Versions

Autofac 6.3.0

**Comment by tillig** [comment]
I'm on vacation with only phone access but I'm guessing the issue is trying to provide an explicit null value as a parameter. Parameters _that can provide values_ along with the contents of the container are used to determine which constructor to use. By trying to provide null, the system will say, "OK, this parameter can't provide a value but the container can, so I'll try that."

Assuming I'm right, I don't think that's something we want to fix. The ability to detect if a parameter can provide a non-null value and fall back to the container is a pretty significant behavior t would yield some unexpected breaking changes if altered.

I might instead recommend registering A with a lambda that has the intelligence you want; or not having an optional constructor parameters and instead using two different constructors along with a constructor selector.

**Comment by alistairjevans** [comment]
I'd also point out that there's a reason you have to specify the null-forgiving operator with `new NamedParameter("b", null!)`. We don't believe that constructor should accept null.

There's an argument that the actual issue here is that the `NamedParameter` constructor should throw an `ArgumentNullException`, so you don't get all the way to a circular reference error.

Instead of passing null to A, I've often found the no-op object pattern useful. Have you considered extracting an interface for B, and creating a class called `NoOpB`, which effectively does nothing (hence no-op) or returns default safe values? It has the advantage of decoupling `A` from even needing to understand if `B` is actually in use, and can result in cleaner code.
