### ISSUE TITLE
IRegistrationSource->RegistrationsFor with KeyedService

### ISSUE THREAD

**Issue by rozbo** [autofac/Autofac#1313]
## Problem Statement

I want put many object to container with the same type and same interface, but different Name ,and the timing and count of these objects are **uncertain**, so I try to use the `IRegistrationSource` to do that,
```c#
public class ConsumerA {
    public ConsumerA([KeyFilter("A")]IAgent agent) {
        Console.WriteLine(agent.Id);
    }
}
public class HandlerRegistrationSource : IRegistrationSource {
    public IEnumerable<IComponentRegistration> RegistrationsFor(Service service,
        Func<Service, IEnumerable<ServiceRegistration>> registrationAccessor) {
        var swt = service as IServiceWithType;
        return Enumerable.Empty<IComponentRegistration>();
// if want the Agent and Name with "A", but where I can get Keyed "A"
    }

    public bool IsAdapterForIndividualComponents { get; } = false;
}
```
But, in this case, it missed the name info, and just a Type

## Desired Solution
I want it can be a type like `KeyedService`, not `TypeService`, so that I can get the ServiceKey.

## Alternatives You've Considered

Is middware can do this ?

**Comment by rozbo** [comment]
May be there is bug.
cause when I use 
```c#
    public ConsumerA(ILifetimeScope lifetimeScope) {
        var agent = lifetimeScope.ResolveKeyed<IAgent>("A");
    }
```
The `RegistrationsFor` param  typeof `service`  is `KeyedService`, this is what I want!

----
So, is the auto inject with param a bug?

**Comment by alistairjevans** [comment]
It looks you're missing a call to `WithAttributeFiltering()` when registering `ComponentA`. If you check our docs on resolving with attribute filters (https://autofac.readthedocs.io/en/latest/advanced/keyed-services.html#resolving-with-attributes), it states that due to attribute filtering having a non-zero impact on performance, you must explicitly opt-in to it. 

Once you correct the registration, the `service` argument becomes `KeyedService`.
