### ISSUE TITLE
AsClosedTypesOf registers Self besides the closed generics

### ISSUE THREAD

**Issue by wallymathieu** [autofac/Autofac#1322]
## Describe the Bug

While trying to diagnose dependency registration issues at work, we noticed that the registration builder method AsClosedTypesOf registers self besides the closed generics.

## Steps to Reproduce

```c#
// types defined in Autofac tests:
public interface ICommand<T> { void Execute(T data); }
public class CloseCommand : ICloseCommand { public void Execute(object data) { } }
public interface ICloseCommand : ICommand<object> { }
// note that ScanningRegistrationTests is defined in the AutoFac tests project:
public class ScanningRegistrationTests
{
    // The test of the behavior
    [Fact]
    public void AsClosedTypesOfShouldNotRegisterSelf()
    {
        var cb = new ContainerBuilder();
        cb.RegisterAssemblyTypes(typeof(ICloseCommand).GetTypeInfo().Assembly)
            .AsClosedTypesOf(typeof(ICommand<>));
        var c = cb.Build();

        c.AssertNotRegistered<CloseCommand>();
    }
}
```

## Expected Behavior

We expected the method AsClosedTypesOf to register types so that we resolve closed generic types such as `Message<string>` or `ICommand<string>`. 

We did not expect to resolve the implementation type (what you want if you use the builder AsSelf() ).

## Dependency Versions

Autofac: >= 5 

## Additional Info

This might have been introduced in #507

**Comment by tillig** [comment]
Can you provide a little more here, like what the `CloseCommand`, `ICommand<>`, `ICloseCommand`, and other related type signatures look like? We don't need constructors or whatever, but I don't know if `CloseCommand` implements some interface or another so I don't know why things are or aren't expected. Also include access modifiers like `public` or `internal`.

```c#
// We need these:
public class CloseCommand : ICommand, ICommand<string> { }
```

Thanks!

**Comment by tillig** [comment]
If I had to guess, you're on a pretty old version of Autofac, you're updating, and this is unexpected? I see you didn't list that in the context but that you did list "Autofac >= 5" is affected. The referenced issue #507 was from back in 2014. A _lot_ has changed since Autofac 5.

(Am I right, that this is a surprise to you caught during an upgrade scenario?)

With respect to this, I see the chain:

`CloseCommand : ICloseCommand` and `ICloseCommand : ICommand<object>`. So that means `CloseCommand : ICommand<object>` which makes `CloseCommand` a closed implementation of `ICommand<>`.

In fact, we have [a unit test here](https://github.com/autofac/Autofac/blob/78c47f5e4c9d422a634fa40e3c4ef149f0ae1580/test/Autofac.Test/TypeExtensionsTests.cs#L34) that _ensures_ we find non-generic closed classes as being closed implementations of generic interfaces:

```c#
public interface ICommand<T> { }
public class SaveCommand : ICommand<SaveCommandData> { }

[Fact]
public void IsClosedTypeOfReturnsTrueForClosedClasses()
{
  Assert.True(typeof(SaveCommand).IsClosedTypeOf(typeof(ICommand<>)));
}
```

The [`IsClosedTypeOf` method](https://github.com/autofac/Autofac/blob/78c47f5e4c9d422a634fa40e3c4ef149f0ae1580/src/Autofac/TypeExtensions.cs#L68) is [what gets used when you call `AsClosedTypesOf`](https://github.com/autofac/Autofac/blob/78c47f5e4c9d422a634fa40e3c4ef149f0ae1580/src/Autofac/Features/Scanning/ScanningRegistrationExtensions.cs#L119)

Based on that, I think this is functioning as designed. I'm sorry if it's unexpected; it appears to have been that way - based on that referenced issue and a little spelunking through Git - for upwards of at least eight years. Changing it to _not_ behave this way would be pretty breaking for folks who have come to expect this behavior and rely on it, so I don't think we'll be fixing it. There's also not a lot of value for us to own or maintain an "opt-out" for this behavior since, again, the current behavior has been around for quite some time and is unlikely to be something most people are going to need.

As you can see, though, the `AsClosedTypesOf` extension is basically just LINQ - if you want a custom version of `AsClosedTypesOf` that determines what a "closed type" is based on your specific criteria, you could probably reasonably easily create that and own it in your own code.

**Comment by wallymathieu** [comment]
I've tested it in Autofac 6 where you have the issue as well.

**Comment by tillig** [comment]
I understand. What I'm saying is:

- This behavior has been around for a long time.
- The way you describe it working is intentional.
- My _guess_ is that you're upgrading from a very old Autofac version and this caught you by surprise, but you haven't confirmed that.

The net result is the same - this is functioning as designed, not a bug, and we don't intend to fix it because it's not broken.

**Comment by wallymathieu** [comment]
It was not during an upgrade scenario. We tried to review why we got too many resolved services when using the above method.

**Comment by wallymathieu** [comment]
Thanks for the answer @tillig , this just caught us by surprise. Perhaps we should add some more docs to the methods in order to clarify the intended behaviour?

**Comment by tillig** [comment]
I think it's more a difference in understanding what a "closed type" is in respect to "open generics." However, if you think there's a concise way to clarify that, we're always open to pull requests. [Here's the source for the documentation on assembly scanning.](https://github.com/autofac/Documentation/blob/master/docs/register/scanning.rst) I _don't_ think trying to clarify that in IntelliSense documentation is wise; if it gets long enough to scroll, it's too much. IntelliSense needs to be about a sentence long.

**Comment by wallymathieu** [comment]
Thanks for the time @tillig 😄
