### ISSUE TITLE
Initialize components with Autofac 6.4.0 with IComponentRegistration

### ISSUE THREAD

**Issue by vulovicv23** [autofac/Autofac#1332]
I migrated from .net 4.6 to .net 4.8 and upgraded Autofac to version 6.4.0. The bellow snippet worked before, but after upgrading, this cannot be done since ResolveComponent method requires ResolveRequest. And ResolveRequest accepts in constructor: Service service, ServiceRegistration serviceRegistration, IEnumerable<Parameter> parameters, IComponentRegistration? decoratorTarget = null

In the bellow snippet, Container is IContainer Container.

Does anybody has a solution for this?

```
//initialize fully initialized in cache first
List<IComponentRegistration> componentRegistrations = Container
    .ComponentRegistry.Registrations.Where(r =>
        typeof(IInitializable).IsAssignableFrom(r.Activator.LimitType) &&
        typeof(IFullyInitializedInCacheRepository<>)
            .IsAssignableFrom(r.Activator.LimitType))
    .ToList();
    
var resolvedInstances = componentRegistrations.Select(x => Container.ResolveComponent(x, new List<Parameter>())).ToList();

resolvedInstances.ForEach(x => ((IInitializable)x).Initialize());
```

**Comment by tillig** [comment]
[There are several ways you can run code at container build to initialize components. Check out the documentation.](https://autofac.readthedocs.io/en/latest/lifetime/startup.html)

**Comment by vulovicv23** [comment]
@tillig anything more specific you can tell me about this? Since I went through documentation mutliple times and didn't find what I was looking for?

**Comment by tillig** [comment]
You probably noticed when you opened the ticket that we try to direct "how do I...?" questions to Stack Overflow. The reason is that we rely on the help of the community to answer questions like this. You may not realize, but there isn't a dedicated large team of people maintaining and supporting Autofac and all the extensions - it's me and basically two other people in our unpaid free time. On Stack Overflow there's a whole community of folks that can help answer questions (and we all _also_ monitor there), which allows issues to focus on reproducible bugs and feature development.

If you need me, personally, to code up an example, I can do that but you'll have to wait possibly a very long time since I need to prioritize bugs and features over questions.

An additional source of inspiration may be our test suite showing testing for build callbacks and startables. It may give you some ideas about how to change things.
