### ISSUE TITLE
Failed to use property injection on attribute

### ISSUE THREAD

**Issue by li-zheng-hao** [autofac/Autofac#1346]
## Describe the Bug

Failed to use property injection on attribute

## Steps to Reproduce

1. call addRedisManager when app start up
```c#
public static IServiceCollection AddRedisManager(this IServiceCollection service)
 {
      service.AddSingleton<IRedisManager, RedisManager>();
      return service;
 }
```
2. register my custom attribute by autofac:
```c#
builder.RegisterType<NeedCacheAttribute>().PropertiesAutowired();
```
3. my custom attribute code:
```c#
public class NeedCacheAttribute:Rougamo.MoAttribute
{
    public string CacheKey { get; set; }
    // inject this property，but it is null when running
    public IRedisManager _RedisManager { get; set; }
    public NeedCacheAttribute(string customKey="")
    {
        CacheKey = customKey;
        // _RedisManager= IocHelper.GetNewILifeTimeScope().Resolve<IRedisManager>();
    }
}
```
4. use this attribute in service layer method:
```c#
 [NeedCache]
public Users Query(string key)
{
    var res = _dal.Where(it=>it.UserName==key).First();
    return res;
}
```
5. call Query method from controller layer:
```c#
 [HttpGet]
  public Users BatchQuery(string key="userA")
  {
      return _userService.Query(key);
  }
```

## Dependency Versions

- Autofac: 6.4.0
- Rougamo.Fody:1.1.2

## additional info

Property injection works fine in other classes：
```c#
public class UserService:IUserService
{
    // it works
    public IRedisManager red { get; set; }
}
```

**Comment by alistairjevans** [comment]
Normal attributes will not be automatically resolved from DI, or property-injected, but you're using some custom AOP library to inject code into the method, so not sure how it handles DI. I'd suggest looking to that library first for "how do I inject dependencies into my attribute"

You probably noticed in the issue template that we try to direct "how do I?..." questions to Stack Overflow and use issues for bugs or feature requests. We do that because more community members can help on SO and there is not a big team supporting Autofac so "free consulting and troubleshooting" questions will end up deprioritized.

**Comment by li-zheng-hao** [comment]
thanks reply
