### ISSUE TITLE
Support for ```required``` properties

### ISSUE THREAD

**Issue by TonyValenti** [autofac/Autofac#1355]
## Problem Statement
Traditionally, Autofac creates objects by calling one of their constructors.  The constructor accepts dependencies and then assigns/initializes values.

Starting in C#11, dependencies can also be expressed using the ```required``` keyword.  When a property is ```required```, if the constructor that was called does not have the ```[SetsRequiredMembers]``` attribute, the property must have a value set immediately following construction.

Currently AutoFac does not support this core enhancement to object construction.

## Desired Solution
When Autofac constructs an object, the constructor should be examined for ```[SetsRequiredMembers]```.  If it is not found, all writable properties containing the ```RequiredMemberAttribute``` attribute should be injected.

```csharp
    public class Foo1 { 
        //This should be injected
        public required Dependency? Dep { protected get; init; }
    }

    public class Foo2 {
        //This should not
        public required Dependency? Dep { protected get; init; }

        [SetsRequiredMembers]
        public Foo2() {
            this.Dep = null;
        }

    }
```

## Additional Context
Because C#11 introduces this core-level enhancement to object construction, the above rules should always be enabled.

The following code will be helpful in implementing this enhancement:
```csharp
    public class PS : IPropertySelector {
        public static IPropertySelector Instance { get; }

        private static string RequiredAttributeName { get; }
        private static string SetsRequiredMembersAttributeName { get; }

        static PS() {
            Instance = new PS();

            //The type names are stored as strings so that this can also be used with legacy .NET platforms
            RequiredAttributeName = "System.Runtime.CompilerServices.RequiredMemberAttribute";
            SetsRequiredMembersAttributeName = "System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute";
        }

        public bool NeedsPropertyInjection(ConstructorInfo constructorInfo) {
            var SetsRequiredMembers = constructorInfo.GetCustomAttributesData().Any(x => string.Equals(x.AttributeType.FullName, SetsRequiredMembersAttributeName, StringComparison.InvariantCultureIgnoreCase));

            var ret = !SetsRequiredMembers;

            return ret;

        }

        public bool InjectProperty(PropertyInfo propertyInfo, object instance) {
            var ret = propertyInfo.CanWrite
                && propertyInfo.GetCustomAttributesData().Any(x => string.Equals(x.AttributeType.FullName, RequiredAttributeName, StringComparison.InvariantCultureIgnoreCase))
                ;

            return ret;

        }
    }
```

**Comment by alistairjevans** [comment]
Generally in favour of the feature to reduce user confusion when combined with the NRT analyser, I'm guessing it will determine that any required properties are non-null.

Got some random questions/thoughts though of the top of my head...

- Currently you have to invoke `PropertiesAutowired` on a registration to apply any property injection behaviour. Are you suggesting this is still the case? Or would this be applied to all registrations automatically? 

- Is there a compiler-generated attribute that indicates "this type has required properties"?

- Does this feature combine with nullable reference types in any interesting ways? If someone has a `required ServiceA?` property, does that mean it _must_ be populated? Or is still a bit optional?

- Do we _only_ apply this to `required` attributes? Or do non-required properties become optional injection automatically?

Just trying to tease out some of the detail on this one...

**Comment by TonyValenti** [comment]
Hi @alistairjevans -
**RE ```PropertiesAutowired```:**
I believe that required properties should always be injected and should essentially be treated like "Constructor 2.0"

**RE compiler-generated attribute**:
Yes.  See the code above.  There are two attributes that work together:
```
            RequiredAttributeName = "System.Runtime.CompilerServices.RequiredMemberAttribute";
            SetsRequiredMembersAttributeName = "System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute";
```

**RE nullable reference types**:
A required property _MUST be set although ```null``` is a valid value to set it to.  I believe that if the nullable reference type is annotated, then autofac should throw an exception if it cannot provid a value since null is an invalid value in that case.

**RE: Do we only apply this to required attributes?**
This should be thought of as part of maintaining compatibility with the current .net object construction methodologies and should not be optional.  The current ```PropertiesAutowired``` should continue to exist and operate as is since it provides similar (but not identical) capabalities.

**Comment by tillig** [comment]
It might be worth finding out what, if anything, the Microsoft container is going to do here. They sometimes make unspoken/undocumented assumptions on how things will work. If we do something different we'll need a way to "switch to MS compatible behavior" (see: lifetime scopes aren't hierarchical).

**Comment by alistairjevans** [comment]
@tillig, looks like the answer to that is not yet known: https://github.com/dotnet/runtime/issues/76854

I think I'm a little reluctant to enable property-autowiring "by default", mostly due to user confusion from the different behaviour between 'required' properties and 'optional' properties.

Say I have two properties on a component, of type `A` and `B`. Type `A` is marked as `required`, and `B` is not. I *always* register a service of type `A`, but `B` is condtionally registered (e.g. by tenant). 

When I resolve my component, in this scenario `A` would always be populated, and `B` would never be, however if I call `PropertiesAutowired()` on the registration, then `B` *will* sometimes be populated, but the behaviour of `A` will be the same. 

This feels like it will absolutely result in users raising issues where "this property is set, but this one isn't, even though it's registered...".

So it still feels like property injection needs to be opt-in somehow...there probably is a small number of changes we could make that gives us a decent compromise:

- We can check for the `RequiredMemberAttribute` on a type when we build the registration; if it is present, but `PropertiesAutowired` has not been called, we can throw a suitably informative exception.

- When executing `AutowiringPropertyInjector.InjectProperties`, if a property is marked as `required`, but is excluded by a custom property selector, we can throw an exception.

- If we fail to resolve a service for a property marked with `RequiredMemberAttribute`, we throw an exception.

- Optionally, to enable users who genuinely want this behaviour *everywhere*, we could add a `ContainerBuilder.GlobalPropertiesAutowired()` method that injects `PropertiesAutowired()` onto every registration. Technically this is already possible with a registered event handler, but a shortcut may be useful.

**Comment by TonyValenti** [comment]
Related to this, how would I enable ```PropertiesAutowired``` on ```AnyConcreteTypeNotAlreadyRegisteredSource```?

**Comment by tillig** [comment]
@TonyValenti good point with ACTNARS.

@alistairjevans My gut says both that you're right, inconsistent behavior will be a problem. But I also think if a property is marked required then it's part of object initialization so it probably has to happen.

This seems particularly to affect reflection-based construction (individual types, open generics) since the compiler would ostensibly stop a lambda from returning an incomplete object.

I haven't thought this totally through, but I wonder if part of the constructor locator process needs to also locate required properties and add those to a list of always-initialized properties. Not full autowired properties, but also not something you have to opt into. If props autowiring is opted in, then the set of properties to wire is the _union_ of required and whatever else can be populated.

If a required property can't be filled in, a similar exception to the constructor exception gets thrown, but with an explanation about it being a property.

I think this could be cached like we cache constructors to save a bit on perf, but it's definitely going to be a non-zero hit since, at a minimum, we'll always have to check the cache for the (likely empty) list of required properties.

I'm reluctant to make a final decision until we know what M.E.DI is doing simply because the path of least resistance is to be compatible.

**Comment by tillig** [comment]
I added a comment to that dotnet issue. I don't know if they'll even address it, looks like it's been there for a bit with no other commentary. We may need to make a decision here and then just post to them what we did as a way to try to inform what they do, then hope for compatibility.

**Comment by TonyValenti** [comment]
Thanks @tillig -
I'm really hopeful this gets implemented. Being able to have required properties be injected would enable me to remove a ton of code in my application. 

I have a set of base classes that are extended 3-4 levels deep. Currently, Every constructor at every level of the inheritance chain has to collect and forward parameters to its base constructor.  That's nothing unique to me, I'm just particularly affected by it.

Anyways, injecting to required properties would allow me to remove close to 1600 constructors in my code base and enable me to remove about 600 auxiliary classes.

I really hope this gets some traction.

**Comment by GitClickOk** [comment]
**_Just adding to the thread what I wrote in the original "required properties proposal" in C#, it explains very well some benefits:_**

With **required** properties, we end up creating an alternative way to specify a constructor without bloat the ctor with a lot of parameters.
```csharp
public class Person
{
    public required string FirstName { get; init; }
    public required string MiddleName { get; init; }
    public required string LastName { get; init; }
}
```
Now, assuming Dependency Injectors can understand what I am asking, we can change code like this
```csharp
public class SomeClass
{
    private readonly IDbContext _dbContext;
    private readonly ILogger _logger;
    private readonly IOptions _options;

    public SomeClass(IDbContext dbContext, ILogger logger, IOptions options)
    {
        _dbContext = dbContext;
        _logger = logger;
        _options = options;
    }
}

public class SomeDerivedClass : SomeClass
{
    private readonly IMailService _mailService;

    public SomeDerivedClass(IDbContext dbContext, ILogger logger, IOptions options, IMailService mailService)
        :base(dbContext, logger, options)
    {
        _mailService = mailService;
    }
}
```
in this instead:
```csharp
public class SomeClass
{
    public required IDbContext DbContext { get; init; }
    public required ILogger Logger { get; init; }
    public required IOptions<AppSettings> Options { get; init; }
}

public class SomeDerivedClass : SomeClass
{
    public required IMailService MailService { get; init; }
}
```

This is a LOT of less boilerplate error-prone code! And the "required" is the key here.  I know that currently it is partially supported by Dependency Injectors (property injection), but it is rarely used and I think if the Injector finds a "required" property it will be better than using a settable property.

**Comment by tillig** [comment]
I don't think we need to be sold on the value of the feature. At this point it's more a question of how it should work and how we can remain compatible with M.E.DI. I'm almost more concerned about that compatibility issue because trying to retrofit compatibility has caused us a lot of trouble in the past. Folks, for whatever reason, choose Autofac as the underlying container and then complain when it isn't identical to the Microsoft container.

**Comment by TonyValenti** [comment]
Hi @tillig -
What is the right way to get input from MS regarding this?  I can really use this feature and want to do whatever is necessary to drive this enhancement forward.

**Comment by tillig** [comment]
@TonyValenti if I had a way, I'd have used it. I don't have any more visibility or leverage into their process than you do. I commented on the issue linked earlier, that's all I can do. You can comment there, too, if you like.

Working through things that may affect every user of a container or framework is not a fast process.

**Comment by TonyValenti** [comment]
@tillig - We have a response from Microsoft!

https://github.com/dotnet/runtime/issues/76854

**Comment by alistairjevans** [comment]
@TonyValenti; initial PR up for required property support in #1364. Take a look, and if you wanted to take it for a spin that would be appreciated.

**Comment by TonyValenti** [comment]
Is there a way for me to install a preview or beta build from nuget?

I would LOVE to give this a spin.

**Comment by alistairjevans** [comment]
You can grab a nupkg from the PR build artifacts; packages don't go into myget before they merge.

https://ci.appveyor.com/project/Autofac/autofac/builds/46073806/artifacts

**Comment by TonyValenti** [comment]
This. Works. Beautifully.

**Comment by TonyValenti** [comment]
When do you think this will be merged and released?

**Comment by alistairjevans** [comment]
Since this will trigger a breaking change, we will want to incorporate as many other breaking deprecations as we can before it goes out. 

So the answer is "don't know".

**Comment by alistairjevans** [comment]
@TonyValenti, required properties shipped: https://github.com/autofac/Autofac/releases/tag/v7.0.0

**Comment by TonyValenti** [comment]
@alistairjevans Thank you!

**Comment by alistairjevans** [comment]
@TonyValenti, sounds like a reasonable proposal; suggest you raise a PR in the documentation repo.

**Comment by TonyValenti** [comment]
@alistairjevans Thanks!  PR Submitted.
