### ISSUE TITLE
[Feature-Request] Add `IServiceProvider` to `ILifeTimeScope`

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac#1367]
## Problem Statement

`MediatR` now directly requires `IServiceProvider`. So for `Autofac` to work with `MediatR`, a reference to AEDI is now required.

## Desired Solution

I figured that `IServiceProvider` is not part of MEDI but lives in `System.ComponentModel` as you can see [here](https://learn.microsoft.com/en-us/dotnet/api/system.iserviceprovider?view=net-7.0). A potential solution would be to let `ILifetimeScope` implement it.

## Alternatives You've Considered

No alternatives given in this case, other than always having the requirement to use AEDI (even for console applications)

## Additional Context

I am not sure if this would be a big change. IMO we would need move the interface from AEDI into this package. `IServiceProvider` only provides a single function, wish would translate to `ILifeTimeScope.ResolveOptional(serviceType)`.

I also do believe that the interface has been moved and was original part of MEDI but this is not the case anymore.

What do you think about it @tillig & @alistairjevans?

**Comment by tillig** [comment]
I lean towards "no" because, as you see [in `AutofacServiceProvider`](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacServiceProvider.cs), while `IServiceProvider` is in `System.ComponentModel`, the MEDI folks have added new interfaces like `ISupportRequiredService` and `IServiceProviderIsService` to "extend" the functionality of `IServiceProvider`.

Even if we moved the `IServiceProvider` implementation into `ILifetimeScope`, we'd still need to maintain these other extended features through the `AutofacServiceProvider` adapter. It might buy us something specifically for `MediatR` with one fewer package reference, but it splits the implementation of the complete MEDI compatible `IServiceProvider` with extensions into two places instead of just keeping it in the adapter.
