### ISSUE TITLE
Generic module/extension for enabling global property injection

### ISSUE THREAD

**Issue by alexmg** [autofac/Autofac#382]
_From [travis.illig](https://code.google.com/u/travis.illig/) on July 10, 2012 01:41:45_

From the discussion here: https://groups.google.com/forum/?fromgroups#!topic/autofac/-SC8XzuzxHE Creating a module for log4net (or other logging) integration that enables the logger to be injected via both constructor or property is a common thing. It also may not necessarily be a function connected only to logging - other object types may need to be registered as globally injectable property values.

Add a generic module or registration extension method that enables a registered type to be injected as a property value without every other consuming registration having to specify PropertiesAutowired().

For example:
builder.RegisterType<Foo>().As<IFoo>().EnableGlobalPropertyInjection();

or

public abstract class PropertyInjector<T> : Module
(like from this gist: https://gist.github.com/3066496 )
builder.RegisterModule<MyPropertyInjector>();

_Original issue: http://code.google.com/p/autofac/issues/detail?id=382_

**Comment by tillig** [comment]
I think this sounds like an interesting extension that could be added as a separate package owned/maintained by someone in the community - perhaps in conjunction with #644? Regardless, we're somewhat at capacity for extra packages and since it sounds like it can be managed in a separate module, this is a good opportunity for a community-owned extension.
