### ISSUE TITLE
Method not found: 'Void Autofac.RegistrationExtensions.RegisterModule(Autofac.ContainerBuilder, Autofac.Core.IModule)'

### ISSUE THREAD

**Issue by mrichman** [autofac/Autofac#520]
I'm using Autofac 3.3.1 and Autofac.Configuration 3.2.1 installed via NuGet:

```
<package id="Autofac" version="3.3.1" targetFramework="net451" />
<package id="Autofac.Configuration" version="3.2.1" targetFramework="net451" />`
```

Why would I get this exception?

```
Method not found: 'Void Autofac.RegistrationExtensions.RegisterModule(Autofac.ContainerBuilder, Autofac.Core.IModule)'
```

**Comment by julealgon** [comment]
So you are not going to fix this is that it? I'm stuck now because Autofac MVC4 integration was built using Autofac 3.1 which is before this change, so I can't update to the latest autofac version without migration my solution to MVC5 to use Autofac MVC5...

This is kinda insane. If it is a breaking change, you should update the major version to warn all external libraries about it.

**Comment by tillig** [comment]
We have no plans to back-port functionality to older versions, sorry.
