### ISSUE TITLE
Get current tenant identifier

### ISSUE THREAD

**Issue by rosslyn-benfoster** [autofac/Autofac#536]
Using `Autofac.Extras.Multitenant` it's not clear how I can actually make the tenant identifier available to the rest of my application.

I could take a dependency on `ITenantIdentificationStrategy` and re-execute `TryIdentifyTenant` but since we're already doing this within the multi tenant container I'm not keen on this approach.

Of course, I could set up a dependency for each tenant like so:

```
        mtc.ConfigureTenant("tenant1", cfg =>
        {
            cfg.Register(c => new TenantInstance("tenant1"));
        });
```

But then I'd have to do this for every tenant which kind of sucks.

It would be nice if we had a `ConfigureTenants` method that allows us to do something when _any_ tenant scope is created e.g.

```
        mtc.ConfigureTenantContainer((id, cfg) =>
        {
            cfg.Register(new TenantInstance(id));
        });
```

This configuration could be applied prior to the "specific" tenant configuration.

**Comment by JoshMcCullough** [comment]
I agree that it feels weird to setup the MT container, point it to the strategy, assume that the container is resolving the tenant behind the scenes, but then not be able to access it. To register the dependency as you suggested just seems a bit strange, as my expectation was that I could get it from the MT container since it had already done that work. However, since the tenant resolution will only happen at most twice per tenant, it's not a big deal to do as you suggest. But it feels unnatural IMO. (BTW thanks for all your hard work on Autofac!)
