### ISSUE TITLE
CollectionRegistrationSource registers collections even if the underlying type is not registered

### ISSUE THREAD

**Issue by ccbristo** [autofac/Autofac#609]
Autofac will resolve IEnumerable&lt;IWhatever&gt; as an empty sequence of IWhatever even if IWhatever is not registered.  This is inconsistent with calling Resolve&lt;IWhatever&gt; which throws a ComponentNotRegisteredException. The same behavior applies to the other known collection types (ReadOnlyCollection, Array, IList, etc...)

It is possible that this is an expected behavior, but it caught me by surprise.

Failing test can be seen here: https://github.com/ccbristo/Autofac/blob/InjectCollectionOfUnknownElementType/Core/Tests/Autofac.Tests/Features/Collections/CollectionRegistrationSourceTests.cs

Edit: Fixed generic type names (hopefully)

**Comment by tillig** [comment]
This is correct behavior because it is more likely when resolving IEnumerable<T> or IList<T> that you're trying to get a list of handlers or behaviors to do something with and getting the empty collection allows you to skip the null check - you can go right into the foreach loop.

[It is documented as such on our official doc site.](http://autofac.readthedocs.org/en/latest/resolve/relationships.html#enumeration-ienumerable-b-ilist-b-icollection-b)

**Comment by ccbristo** [comment]
It's even in bold in the docs! Ouch. Not sure how I missed that part.

Thanks for getting back to me so quickly.
