### ISSUE TITLE
DependencyResolutionException thrown when using Lazy<T> while T not registered

### ISSUE THREAD

**Issue by zabulus** [autofac/Autofac#630]
I have a startable service A, that depends on service B. Service B registration performs later, after activation and starting of service A. 
I have in my ctor:
```C#
A(Lazy<B> b)
```
And in late called functions I have:
```C#
this.b.Value.DoSomething()
```
For now Autofac throws exception while trying to register type A before type B.
Nevertheless, I can force such registration via 
```C#
Register(x => new A(new Lazy<B>(() => x.Resolve<B>())
```
Is this exception throw is by design?

**Comment by tillig** [comment]
Can you post a small repro so we can be sure we understand the exact problem? That is, it's OK if you just use "A" and "B" for classes, but post the full class and the registration code so we can see it fail.

**Comment by zabulus** [comment]
```C#
class A
    {
        Lazy<B> b;

        public A(Lazy<B> b)
        {
            this.b = b;
        }

        public void LateMethod()
        {
            this.b.Value.DoSomething();
        }

    }

    class B
    {
        public void DoSomething()
        {
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            IContainer container;
            A a;
            {
                ContainerBuilder bld = new ContainerBuilder();
                //bld.RegisterType<A>(); // 1
                //bld.Register(x => new A(new Lazy<B>(() => x.Resolve<B>()))); // 2

                container = bld.Build();
                a = container.Resolve<A>(); // throws Autofac.Core.DependencyResolutionException
            }
            {
                ContainerBuilder bld = new ContainerBuilder();
                bld.RegisterType<B>();

                bld.Update(container);
            }

            a.LateMethod();
        }
    }
```
If uncomment line 1, Autofac throws the exception at RegisterType call. 
If uncomment line 2, it also throws exception related to not storing x parameter in lambda. But at least it throws at LateMethod call.

Hope I made it clearer now.

**Comment by tillig** [comment]
In both cases it throws because you don't have `B` registered at the time you resolve `A`.

In the first case, all you have is `bld.RegisterType<A>()` after which you try to resolve `A`. Since Autofac doesn't know how to generate a `Lazy<B>` from a component that's not registered, it correctly throws the exception. The message tells you as much:

    `Cannot resolve parameter 'System.Lazy`1[MyNamespace+B] b' of constructor 'Void .ctor(System.Lazy`1[MyNamespace+B])'.`

Note that the `Lazy<B>` creation method has to be populated at the time of resolution - the thing that goes in `new Lazy<B>()` - so registering `B` after the fact doesn't help.

In the second case, the problem is happening because of the `x.Resolve<B>()` call. You get a *different* exception in this case that tells you the problem:

    This resolve operation has already ended. When registering components using lambdas, the IComponentContext 'c' parameter to the lambda cannot be stored. Instead, either resolve IComponentContext again from 'c', or resolve a Func<> based factory to create subsequent components from.

However, you still won't be able to accomplish what you want because even if you try to resolve a `Func<B>` to populate the `Lazy<B>`, `B` still isn't registered by the time you try to resolve `A`, so you will still get the exception.

**You need to have all the components registered at the time you want to resolve, even if you are using a `Lazy<T>` or other deferred resolution.**

If you move the `a = container.Resolve<A>();` down **after** the `bld.Update(container);` then the first scenario works.

Once the first scenario works, you don't need the second manually-created `Lazy<B>` scenario to work because Autofac will do that for you.
