### ISSUE TITLE
Autofac.Extras.Moq doesn't allow control of delegate factories

### ISSUE THREAD

**Issue by spenceee** [autofac/Autofac#636]
There is no way to control or moq behaviour of delegate factories within the Autofac.Extras.Moq package.  I've tried numerous ways to mock the delegate factory (so I can provide a specific behaviour) but I either can't control the constructor, or I get a cast exception that the concrete func can't be casted to a Moq.IMocked<func>.

Have I missed something or is this unsupported?

**Comment by tillig** [comment]
I hate to ask this, but would you mind filing this over [in the Autofac.Extras.Moq repo](https://github.com/autofac/Autofac.Extras.Moq/issues)? We split things up a while back.

(This also may be a good question to try out [on StackOverflow](http://stackoverflow.com) first since we have a lot more people able to answer questions out there.)

**Comment by spenceee** [comment]
No worries tillig.  I've already got the stack overflow question open, so I'll reopen the q on the right repo.

**Comment by tillig** [comment]
Ahhh, if you already have an SO question open, I'll probably close this out over on the Moq repo, too. All the Autofac devs and contributors are all on SO already and it's better to track a question in a single spot with the wider audience. :)
