### ISSUE TITLE
Update Dnx version to beta4

### ISSUE THREAD

**Issue by davidfowl** [autofac/Autofac#639]

**Comment by alexmg** [comment]
The changes for the upgrade have been made. I'm just trying to fix the CI build on AppVeyor at the moment. It fails trying to upload the symbol package for Autofac.Dnx to the artifacts and the error message isn't particularly helpful.

e.g. https://ci.appveyor.com/project/Autofac/autofac/build/4.0.0.37

I might build locally and push directly to MyGet instead of going via CI build.

**Comment by alexmg** [comment]
I've started a discussion on the AppVeyor help forum.

http://help.appveyor.com/discussions/problems/2068-error-packaging-artifacts-the-remote-server-returned-an-error-500-internal-server-error

I would prefer to upload packages created on a fresh build machine if possible. I'll give them a chance to respond before pushing packages directly from a local build.

**Comment by alexmg** [comment]
I have pushed 4.0.0-alpha2 packages for Autofac and Autofac.Dnx to NuGet.

@davidfowl Do you know if anyone has been successfully pushing symbols to symbolsource.org? I got the error below in the build. Decided not to let that stop me pushing the packages across to NuGet though. :smile: 

> Publishing Autofac.4.0.0-alpha2-43.symbols.nupkg to https://nuget.symbolsource.org/MyGet/autofac...Skipped (Package submission failed: Unknown custom metadata item kind: 7 Exception: System.Exception: Error while processing project: 'Autofac'. ---> System.Exception: Error while processing version: '4.0.0-alpha2-43'. ---> System.Exception: Error while processing compilation: 'Release' 'Unsupported,Version=v0.0'. ---> Microsoft.Cci.Pdb.PdbDebugEx (...). See http://www.symbolsource.org/Public/Home/Help for possible reasons. Fiddler may help diagnosing this error if your client discards attached detailed information.)
