### ISSUE TITLE
Attribute Registration

### ISSUE THREAD

**Issue by droyad** [autofac/Autofac#650]
I've built and am using a [library](https://github.com/droyad/Autofac.AttributeRegistration) that will register types by attributing them with the appropriate Lifestyle. The library still needs some tweeks and additions to cover most scenarios. I see this feature as not replacing convention based registrations, rather covering the exceptions to the rule. 

I'd love to merge this into the main Autofac code base (or add-on). If the maintainers think this fits, I'll organise a PR.

**Comment by tillig** [comment]
Looks pretty cool!

Rather than move it around or transfer ownership, I think it would be fine if you wanted to maintain it where it is. We already have quite a bit we maintain and we love it when the community creates extensions like this to help address their needs.

If you run into an issue where you can't do something you want to do in your extension, let us know and we'll see if we can open up APIs to enable you to get things done.

Thanks again for sharing!
