### ISSUE TITLE
System.Array.Empty() method not found exception during setup

### ISSUE THREAD

**Issue by damienpontifex** [autofac/Autofac#660]
In my static method to build the Autofac container and register types, I receive this exception when my application is deployed to Azure. Also, the application runs fine locally, so not sure if it is an Autofac issue or Azure, but thought I would see if anyone had any insights into why this might occur?

`Method not found: '!!0[] System.Array.Empty()'. 
at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) 
at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) 
at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) 
at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) 
at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) Method not found: '!!0[] System.Array.Empty()'`

The stack trace from here into my code just mentions the Build method below. No specific line of client code that is causing the issue.

My configuration is called from Global.asax.cs with:

```cs
public static void Configure(HttpConfiguration config)
{
    // Shared builder so I can register types between Web API project and WebJob Project.
     var container = AutofacContainerBuilder.Build(builder =>
     {
         builder.RegisterApiControllers(Assembly.GetExecutingAssembly());
     });

	config.DependencyResolver = new AutofacWebApiDependencyResolver(container);
}
```

And the AutofacContainerBuilder.Build method is:
```cs
public static IContainer Build(Action<ContainerBuilder> extraConfiguration = null)
{
    var builder = new ContainerBuilder();
    
    if (extraConfiguration != null)
    {
        extraConfiguration(builder);
    }

  // Register everything here.

    var container = builder.Build();

    return container;
}
```

**Comment by tillig** [comment]
Do you have a stack trace showing anything tying to Autofac? Unfortunately, unless you can be more specific about what we should look at or you can maybe post a simple repro or something, there's not much we can do.

**Comment by damienpontifex** [comment]
@tillig updated with my code that eventually has the exception in it. As mentioned, the stack trace mentions the Build function above, but not which line/method inside this method is actually the origin.

**Comment by tillig** [comment]
@damienpontifex I see - you didn't actually post the full stack trace. That confused me. No mention of the Build or Configure methods.

Unfortunately, I don't see anything out of the ordinary, which makes me think there's something else going on that I can't debug or repro from here.

A quick search on `!!0[] System.Array.Empty()` yields some results that show you may not be alone... but also that it's probably not Autofac. The results I see indicate that on your desktop you may have .NET 4.6 but that's not yet available in Azure.

- [MVC 5 Bundle Error](http://stackoverflow.com/questions/29020614/mvc-5-bundle-error)
- [MissingMethodException Additional Information: Method not found: '!!0[] System.Array.Empty()'.](https://connect.microsoft.com/VisualStudio/feedback/details/1097462/missingmethodexception-additional-information-method-not-found-0-system-array-empty)

If you're trying a 4.0.0-beta version of Autofac in Azure, try using the latest release 3.5.2 instead. The 4.0.0-beta should work just fine in .NET 4.5 but if rolling back fixes it, let us know since it means a potential bug in the DNX compiler.

If you're already on 3.5.2, then I'm guessing it's the .NET 4.6 issue.

In any case, it's not necessarily something we can fix for you, so I'm going to close this out. If it turns out rolling back from 4.0.0--beta to 3.5.2 fixes the issue, let me know so we can take it up with the DNX team.

**Comment by damienpontifex** [comment]
@tillig it was .NET 4.6. My apologies, I didn't realise the project was targeting it. And also that it wasn't supported in Azure. I had found some of those same issues online, but didn't associate them with this compilation target. 

Thanks :)
