### ISSUE TITLE
InstancePerRequest not resolved properly

### ISSUE THREAD

**Issue by idevelopir** [autofac/Autofac#661]
I use Autofac , Autofac.Mvc5 , Autofac.Mvc5.Owin and Autofac.Owin.

I register DbContext PerRequest

builder.RegisterType<ApplicationDbContext>().AsSelf().InstancePerRequest();

I want use ApplicationDbContext in Application_BeginRequest , Application_Error and Application_EndRequest. 

    public class MvcApplication : System.Web.HttpApplication
    {
        public ILifetimeScope Container
        {
            get
            {
                return (ILifetimeScope)HttpContext.Current.Items["_Container"];
            }
            set
            {
                HttpContext.Current.Items["_Container"] = value;
            }
        }
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }

        public void Application_BeginRequest()
        {
            Container = DependencyResolver.Current.GetService<ILifetimeScope>();

            var context = Container.Resolve<ApplicationDbContext>();

             // todo
        }

        public void Application_Error()
        {
            var context = Container.Resolve<ApplicationDbContext>();

             // todo
        }

        public void Application_EndRequest()
        {
            try
            {
                var context = Container.Resolve<ApplicationDbContext>();

                // todo
            }
            finally
            {
                Container = null;
            }
        }
    }

but autofac create two instance of ApplicationDbContext . one for Controller and one for Application_ Call.

ApplicationDbContext for controller Dispose after Controller disposing.

InstancePerRequest this will mean when Application_BeginRequest unitll Application_EndRequest
not to life time of contoller.

**Comment by tillig** [comment]
It seems you have a lot of things mixed and matched here.

You're using OWIN, but also ignoring the OWIN pipeline by using the HttpApplication events to handle things.

The `DependencyResolver.Current` dependency resolver can be used (should be used) to resolve services directly, but you're bypassing that mechanism and storing your own lifetime scope.

And, of course, there's the problem where you'll have a race condition in `Application_EndRequest` - the Autofac [RequestLifetimeHttpModule](https://github.com/autofac/Autofac.Mvc/blob/master/src/Autofac.Integration.Mvc/RequestLifetimeHttpModule.cs) is going to try disposing of the container and cleaning things up, but you're keeping the container around and trying to do your own cleanup, resolving things too late in the request lifecycle.

I'm not sure what exactly you're trying to accomplish, but I'd say this:

- **Stop holding onto a container/scope to resolve from.** Only resolve services from `DependencyResolver.Current` or `AutofacDependencyResolver.Current`. This will help break race conditions where you're trying to take over lifecycle events.
- **Stop using `HttpApplication` events if you're in OWIN.** Use [OWIN middleware to handle pipeline events instead.](http://www.asp.net/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline) This will help disambiguate when things are happening and, again, avoid race conditions.
- **Take advantage of the fact that Autofac will automatically dispose of any `IDisposable`** for you when the lifetime scope is disposed at the end of the request. If all you're doing is disposing, you're done. If you need to do more than dispose, take advantage of [`OnRelease` and some of the other lifetime controlling options Autofac provides](http://autofac.readthedocs.org/en/latest/lifetime/disposal.html).

I'm going to go ahead and close this out. If it turns out this is still confusing, I recommend [asking a question on StackOverflow](http://stackoverflow.com) and tagging it `autofac`. There's a vibrant community of folks able to handle usage questions like this and they may be able to respond a little faster.
