### ISSUE TITLE
Threading issue in LifeTimeScope.GetOrCreateAndShare

### ISSUE THREAD

**Issue by hackfaq** [autofac/Autofac#666]
I have WCF service, and on method calls I get exception:

```
An item with the same key has already been added.

System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   в Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
```

as I investigated sources such error can't happen, because it checks before add.

**Comment by tillig** [comment]
Can you please provide a repro and post it somewhere? Given many people are successfully using Autofac with WCF and not seeing this error, we'll need to see it ourselves in order to troubleshoot.

**Comment by hackfaq** [comment]
look at image, I already have TicketController in _sharedInstances with id, but it tries tp insert again.
![image](https://cloud.githubusercontent.com/assets/2344814/8888401/5eac270a-32b4-11e5-985c-c4f5c5815fbf.png)

**Comment by hackfaq** [comment]
I have rewrited method:GetOrCreateAndShare, added check for key, and it it works now.

public object GetOrCreateAndShare(Guid id, Func<object> creator)
		{
			if (creator == null)
			{
				throw new ArgumentNullException("creator");
			}
			lock (_synchRoot)
			{
				object result;
				if (!_sharedInstances.TryGetValue(id, out result))
				{
					result = creator();
					lock (_synchRoot)
					{
						if (!_sharedInstances.ContainsKey(id))
							_sharedInstances.Add(id, result);
					}
				}
				return result;
			}
		}

**Comment by alexmg** [comment]
A unit test showing the issue along with the fix would be best. Wondering what exactly the cause is and a screen capture isn't something we can execute to understand the problem.

**Comment by hackfaq** [comment]
Dictionary is not thread safe, so it should be double checked, I think

**Comment by alexmg** [comment]
I think I see the problem. I'll take a look. I suspect we should also prevent the creator function from being invoked a second time too, even if the second lock prevents the instance from being added to the dictionary.

**Comment by tillig** [comment]
I'm guessing the ContainsKey call is what made the difference (though it escapes me how, since it should have been covered by the try-get). The second/nested lock won't have any effect on the use of the dictionary because no other threads can get into that critical section while the outer lock is held.

**Comment by hackfaq** [comment]
as I see in debug:
1. TryGetValue- null
2. we call creator() -> creator creates same service and call GetOrCreateAndShare
3. trygetvalue - null (because we didnt insert on previos call as we wait for result from creator), so we insert key
4. we get result and insert key again

i dont understand why it creates twice, but i think it's some kind of recursion by delegate


![image](https://cloud.githubusercontent.com/assets/2344814/8890629/0cf3eca2-3310-11e5-8df4-05a5ec817d75.png)

**Comment by hackfaq** [comment]
we experienced problem with dependencies.
OrderController depends on TicketController, TicketController depends on OrderController

so Func<OrderController, TicketController> was added to OrderController 
constructor

thats why it added twice

i dont know how to resolve it now=(

```c#
		public OrderController(
			Entities context,
			IUserDetail user,
			ISeatSalePolicyManager seatSalePolicyManager,
			ReservationPolicyController reservationPolicyController,
			Func<OrderController, TicketController> ticketControllerFactory,
			PartnerRelationsController partnerRelationsController,
			IContainer container,
			DiscountController discountController,
			IPaymentService paymentService,
			IReservationDateRangeService reservationDateRangeService
			)
			: base(context, user)
		{

			_seatSalePolicyManager = seatSalePolicyManager;
			_reservationPolicyController = reservationPolicyController;
			_partnerRelationsController = partnerRelationsController;
			_discountController = discountController;
			_container = container;
			_ticketController = ticketControllerFactory(this);
			_paymentService = paymentService;
			_reservationDateRangeService = reservationDateRangeService;
		}
```

**Comment by hackfaq** [comment]
reproduced in unit test:
https://www.dropbox.com/s/pbccako97rr8h7g/AutofacBugTest.zip?dl=0

**Comment by alexmg** [comment]
This isn't a threading issue at all. The problem is that while creating an instance of A, you are invoking a factory during its construction that creates another instance of A. The factory generated A gets added to the dictionary because its first to complete creation, and when the original A is finally being added to the dictionary is too late. We don't detect this in the circular dependency check because the initial and pending activation of A hasn't yet completed.

Your second unit test passes because when B is created first, it creates the instance of A via the factory, and when it then requests A as its second constructor parameter, the instance already exists and no attempt to create it is made.

The code change you made basically allows a second instance to be created even though you are only supposed to receive one per lifetime scope (A is configured as `InstancePerLifetimeScope`). This is being prevented in the current code through the exception, though a meaningful exception warning you what is happening would be better. I'm attempting to do exactly that but have to battle through the DNX RC2 upgrade first.

**Comment by alexmg** [comment]
I have updated LifetimeScope to throw a DependencyResolutionException with the message below:

```
The constructor of type '{0}' attempted to create another instance of itself. This is not permitted because the service is configured to only allowed a single instance per lifetime scope.
```

That should be more helpful than the dictionary exception.
