### ISSUE TITLE
Loading Dependencies from LibraryManager

### ISSUE THREAD

**Issue by endeffects** [autofac/Autofac#669]
Hallo,

would you please add support for loading Dependencies from the ILibraryManager? The current Implementation of RegisterAssemblyModules() does not make sense on a DNX Enviroment.

Regards

**Comment by endeffects** [comment]
I have created a prototype by my own with some help:
http://stackoverflow.com/questions/31674104/self-registering-libraries-with-autofac-4-and-vnext

But i would still preffer a build in Autofac solution. Let me know if you have some improvements.

**Comment by tillig** [comment]
This looks interesting but we're going to wait until things settle out a bit more with the DNX stuff before diving in here.

**Comment by tillig** [comment]
It looks like this is a moving target at best in .NET Core - for example, [`ILibraryManager` seems to have been deprecated](http://stackoverflow.com/questions/37315419/how-to-load-assemblies-in-asp-net-core-1-0-rc2) in favor of [`DependencyContext`](https://github.com/dotnet/cli/blob/v1.0.0-rc2/src/Microsoft.Extensions.DependencyModel/DependencyContext.cs)... and I think you'd still want to filter which assemblies you're using to register things (not just "all assemblies in the whole app" but "these specific assemblies").

I'll keep this open for now as an enhancement, but I'm not sure if there's anything Autofac specifically should be doing in regards to _locating the assemblies_ so much as _acting on assemblies that have already been located_.

**Comment by tillig** [comment]
Now that .NET Core RTM is out... it seems that there are several ways to locate assemblies, from `DependencyContext` to `Assembly.Load`. In many cases, if you have a "plugin" sort of situation, you'll have to load the assemblies manually since they won't be in the `DependencyContext`.

Since there are a lot of ways to load assemblies, and still more configuration required to determine whether those assemblies are loading modules, registering types, or both... I think for now we'll pass on adding something directly tied to assemblies coming out of a `DependencyContext`.
