### ISSUE TITLE
Resolving services registered as open generics with implemented interfaces throws ArgumentException

### ISSUE THREAD

**Issue by idursun** [autofac/Autofac#688]
``` csharp
interface IDouble<T,R> { }
internal interface ISingle<T> :  IDouble<T, int> { }
class CDerivedSingle<T>: ISingle<T> { }
class Program
{
    static void Main(string[] args)
    {
        var builder = new ContainerBuilder();
        builder.RegisterGeneric(typeof (CDerivedSingle<>)).AsImplementedInterfaces();
        var container = builder.Build();
        var resolved = container.Resolve<ISingle<double>>();
    }
}
```

Resolving service throws the following exception:

```
ArgumentException: The number of generic arguments provided doesn't equal the arity of the generic type definition.
```

**Comment by tillig** [comment]
Thanks! I've added the example [as a unit test](https://github.com/autofac/Autofac/blob/ba576abc1a1c2f3a4287ef5b53647c48d5927af9/test/Autofac.Test/Features/OpenGenerics/ComplexGenericsTests.cs#L186) so we can start figuring out what's up.

**Comment by idursun** [comment]
Thanks. Exception happens at [OpenGenericServiceBinder.cs](https://github.com/autofac/Autofac/blob/master/src/Autofac/Features/OpenGenerics/OpenGenericServiceBinder.cs#L63) 

I have tried to solve it but couldn't find any way of comparing generic parameter count to serviceGenericArguments count because it seems GetGenericArguments or any similar method is not supported in DNX Core.

**Comment by tillig** [comment]
It only took a year and a half but I figured it out. We're now filtering the list of generic interfaces that we _try_ to fulfill by the number of generic parameters provided. Which is to say, if you only provide a single generic parameter (`ISingle<double>` -> `double`) then we don't try to fill in an interface that has two parameters (`IDouble<T, U>`) because, well, we only have one parameter to work with.
