### ISSUE TITLE
Reference conflicts between Autofac and rest of solution (Autofac seems to reference System.Core v 2.0.5.0)

### ISSUE THREAD

**Issue by tlycken** [autofac/Autofac#690]
When building my solution, with a bunch of projects targeted at .NET 4.5.2, I get the following build warning:

> Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

Cranking up the build log verbosity, I get the following:

> There was a conflict between "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". (TaskId:112)
11>      "System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not. (TaskId:112)
> ...
> References which depend on "System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" []. (TaskId:112)
11>          C:\Code\myProject\packages\Autofac.3.5.2\lib\net40\Autofac.dll (TaskId:112)
11>            Project file item includes which caused reference "C:\Code\myProject\packages\Autofac.3.5.2\lib\net40\Autofac.dll". (TaskId:112)
11>              C:\Code\myProject\MessageBus\bin\Debug\MessageBus.dll (TaskId:112)
11>              Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da, processorArchitecture=MSIL (TaskId:112)

Is this a configuration error on my part or on yours? :)

**Comment by alexmg** [comment]
It's annoying but nothing to worry about. The cause is Autofac being a PCL which have a special retargetable reference (you can see the Retargetable=Yes in the signature in the warning). See Travis' post below for some more details.

http://www.paraesthesia.com/archive/2013/03/29/portable-class-library-answers.aspx/

In Autofac 4.0 we will likely have a specific net45 target which should see the warning go away when referencing the package from a .NET 4.5 application.

**Comment by tlycken** [comment]
Ah, thanks for the swift response! :+1:
