### ISSUE TITLE
Resolve from RegisterGeneric not working if resolving a generic with less types than main class

### ISSUE THREAD

**Issue by waynebrantley** [autofac/Autofac#701]
Given this class
```
    public interface ITestDouble<T,TY> { }
    public interface ITestSingle<T> { }
    public class TestClass<T, TY> : ITestSingle<T>, ITestDouble<T, TY>
                    where T : class, ISomeInterface
                    where TY : class, ISomeOtherInterface
    {
    }
```
and this registration:
```
builder.RegisterGeneric(typeof(TestClass<,>)).As(typeof(ITestSingle<>)).As(typeof(ITestDouble<,>));  
```
Gives an error about the number of generic arguments not matching...

```
builder.RegisterGeneric(typeof(TestClass<,>)).As(typeof(ITestSingle<>));  
```
Gives no error, but no resolutions work.
Resolve<ITestSingle<SomeType>>(); //never resolves
```
```
builder.RegisterGeneric(typeof(TestClass<,>)).As(typeof(ITestDouble<>));  
```
Resolve<ITestDouble<SomeType,SomeOtherType>>(); //works as expected
```

Seems like this should/could work.

**Comment by alexmg** [comment]
While it would be possible to cast a constructed instance of `TestClass<T, TY>` to an `ITestSingle<T>`, it's not possible to construct an instance without providing both generic arguments.

When registering and resolving `ITestSingle<T>` as a service, you receive an `ArgumentException` with the message: "The number of generic arguments provided doesn't equal the arity of the generic type definition".

Even though you have registered `ITestSingle<T>` as a service Autofac cannot create the instance because it doesn't know what to provide for the `TY` generic argument as it does for `ITestDouble<SomeType,SomeOtherType>`.
