### ISSUE TITLE
Update contributor documentation to explain how to run unit tests.

### ISSUE THREAD

**Issue by chaitanyagurrapu** [autofac/Autofac#707]
I have cloned the repo and ran the build.ps1 script as suggested in the contributor documentation. I can't seem to be able to run the unit tests in visual studio though (see the screenshots below). It would be nice to be able to run the unit tests in debug mode and step through the code. I am guessing there is some obvious/simple step I am missing that is somehow related to the recent move to the DNX platform?

![image](https://cloud.githubusercontent.com/assets/853059/11921827/f3b97672-a7da-11e5-96fb-3143b4c50906.png)

![image](https://cloud.githubusercontent.com/assets/853059/11921830/0c5b53ee-a7db-11e5-8ff3-6f04d8dccecd.png)

The appropriate directories are created but they are all empty. No dlls in them.

![image](https://cloud.githubusercontent.com/assets/853059/11921842/3f82c194-a7db-11e5-84e7-f225125e7070.png)

**Comment by tillig** [comment]
[Contributor guide added.](https://github.com/autofac/Autofac/blob/master/CONTRIBUTING.md)

Note that you should use the _Visual Studio_ unit test runner, not a ReSharper or CodeRush runner, to be successful in test execution from inside VS. While you may be able to get other runners working, we don't verify they're always working since people have different tools set up.
