### ISSUE TITLE
Accessing IApplicationBuilder

### ISSUE THREAD

**Issue by endeffects** [autofac/Autofac#710]
Hi,

is there any way to access the IApplicationBuilder with Autofac? 
I need to inject the "Use" Logic from an Autofac Module.

public void Configure( IApplicationBuilder app, IHostingEnvironment hostingEnvironment )
{
            app.UseStaticFiles();
            app.UseMvc();
}

**Comment by tillig** [comment]
Out of the box, no, there is no access to `IApplicationBuilder`. You can register it yourself if you want:

`builder.RegisterInstance(app).As<IApplicationBuilder>()`

However, note that if you're trying to "inject" registrations with the `IApplicationBuilder` you may be looking at a chicken/egg situation - calls to add middleware to the application may try to register things with the `IServiceCollection` associated with the application. (For example, calls to configure options actually add service registrations.) If you've already built the application container, you can't readily add those registrations to it - chicken/egg.

If you're looking to "modularize" registrations into your application, I'd recommend looking at a custom solution for that rather than trying to multi-purpose your app container.

One possible solution would be to have _two containers_ - one in which you register your things that add middleware, which you build and run separately to set up the application; and one that is actually the `IServiceProvider` used for DI within the application.

However, that can't be the same container. And, unfortunately, we don't have specific guidance around doing something this custom so you're kinda on your own. Sorry.
