### ISSUE TITLE
Support for default/override implementations

### ISSUE THREAD

**Issue by srogovtsev** [autofac/Autofac#712]
I am having a following setup: a sufficiently large application framework that allows to build business application upon it. Framework core has several services, each one with some kind of implementation (e.g., `IAuthnService` is responsible for maintaining user authentication). From time to time, some application developer wants to replace core service with their own implementation (e.g., they have their own authentication mechanism, incompatible with core implementation).

What I want is to be able to define some kind of "default" implementation for some service, and then allow overriding it with another implementation.

Here are the approaches I've already reviewed:

1. Setup "default" in consumer constructor, override via property injection.

  My main objection is that I'll have to repeat this in every service consumer, which is a lot. I am also not exactly sure that it'd be easy to setup optional property injection for each and every resolved type.

2. Use multiple registrations, use the fact that for single-valued resolution the latest registration overrides all previous ones.

  First of all, my registration order is not defined: I am using modules and assembly scanning. But even if it was defined, I don't like several registrations for one service, and moreover, it won't help for multiple resolution.

Am I missing something?

If I'm not, I've actually already developed a small solution to this problem that uses registration sources. This is still a proof of concept only, but if there's no better way, I will use it in the our framework.

The question is, does Autofac community need this solution as well? And if it does, what is the best way of presenting it - separate package, contribution to Extras or contribution to Autofac itself?

**Comment by alexmg** [comment]
There are plenty of ways for a framework to provide a set of default services and allow the user to override them as desired. I’ve seen a number of different patterns used, from a class with a collection of factory methods, to the [conforming container](http://blog.ploeh.dk/2014/05/19/conforming-container/) pattern such as the dependency resolvers in MVC and Web API.

I think there are a few decisions that need to be made before the best design can be selected.

- Should the framework or override services be dependent on any particular DI container?
- Do you want the override services to be able to register their own dependencies with the container?
- Are there other services registered in the container that should be made available to the override services?
- Are there other services registered in the container that should **not** be made available to the override services?
- Should the override service be able to determine what lifetime is most appropriate for it?
- Does the framework have obvious points for controlling a service’s lifetime such as request begin/end?

Instead of using assembly scanning you could provide a set of factory properties on a configuration class that the user can explicitly override. If you are happy for the services to have access to the container to resolve other services you can provide them with the `IComponentContext` allowing them to resolve their own dependencies.

```
public static class ServiceConfiguration
{
	static ServiceConfiguration()
	{
		LoggerFactory = context => new MyLogger();
		AuthenticationFactory = context => new MyAuthentication(context.Resolve<ILogger>());
	}

	public static Func<IComponentContext, IAuthentication> AuthenticationFactory { get; set; }

	public static Func<IComponentContext, ILogger> LoggerFactory { get; set; }
}
```

In the example above the default services are assigned in the static constructor and the property setter allows the user to override the factories.

```
// User overrides the factory before the container is created.
ServiceConfiguration.LoggerFactory = context => new UserLogger();
	
// Build the container using the factory methods as delegate registrations.
var builder = new ContainerBuilder();

builder.Register(c => ServiceConfiguration.LoggerFactory(c))
    .As<ILogger>()
    .InstancePerDependency();

builder.Register(c => ServiceConfiguration.AuthenticationFactory(c))
    .As<IAuthentication>()
    .InstancePerDependency();
	
var container = builder.Build();
```

You don’t have to use a static configuration class either. It would be possible to create an instance of some user defined class and pass an instance of the configuration instance into it allowing them to add their overrides. The approach would depend on how your framework is bootstrapped.

One advantage of this approach is that the extensibility points are easily discoverable. The user can see a list of all the services that can be overridden in the one place.

If you don't want the services to have access to the container you can simply remove the `IComponentContext` from the factory signature.

```
public static class ServiceConfiguration
{
	public static Func<IAuthentication> AuthenticationFactory { get; set; }

	public static Func<ILogger> LoggerFactory { get; set; }
}
```

You can of course still access the `IComponentContext` for your default service registrations.

```
// User overrides the factory before the container is created.
ServiceConfiguration.LoggerFactory = () => new UserLogger();

// Build the container using the factory methods as delegate registrations.
var builder = new ContainerBuilder();

builder.Register(c =>
{
	if (ServiceConfiguration.LoggerFactory != null)
		return ServiceConfiguration.LoggerFactory();
	else
		return new MyLogger();
})
.As<ILogger>()
.InstancePerDependency();

builder.Register(c =>
{
	if (ServiceConfiguration.AuthenticationFactory != null)
		return ServiceConfiguration.AuthenticationFactory();
	else
		return new MyAuthentication(c.Resolve<ILogger>());
})
.As<IAuthentication>()
.InstancePerDependency();
```

Notice that the `IAuthentication` service registration uses the context to resolve the `ILogger` instance but the invocation of the user defined factory just returns an instance. The user can of course `new` up this object in any way they like and manually provide their own dependencies to the constructor.

Hopefully this has give you some food for thought. I recommend reading Mark Seemann's post on [DI Friendly Framework](http://blog.ploeh.dk/2014/05/19/di-friendly-framework/) for some more inspiration and examples of using abstract factories.

If none of this sits right with you, and you have control over who is using the framework and what their exposure to the container is, then you can certainly go with your registration source approach. Whether or not such an approach is useful to others would depend on what their answers are to the questions I outlined at the start.

**Comment by srogovtsev** [comment]
Thanks for the idea. The thing that bothers me about it is that I have to expose every service I want to be overridable via the `ServiceConfiguration` - and that has both good and bad points about it. Good points are, I explicitly control what can be overridden, but if there's a lot of services that can be, it turns into a bad point.

**Comment by tillig** [comment]
I've previously handled things like this with child lifetime scopes - register the overrides in the child scopes rather than all at once in app startup. There was [a similar sort of question a while ago on StackOverflow](http://stackoverflow.com/questions/32897868/resolving-keyed-subgraphs-with-cascaded-fallback). It does mean you have to control a bit more of registration order, which in the original post you mentioned you don't have that control.

Given this issue has sat for about a month now... unless there's some sort of proposed design showing how some core enhancement might work, I'd like to consider closing this as it sounds like you've solved the issue on your side.

**Comment by srogovtsev** [comment]
Yes, you're right, unfortunately I still don't have control over the order of registrations.

My first attempt at the implementation resulted in something like

    builder.RegisterDefault<Component, IService>() //some more fluent code

And then any other "normal" registration would override this. It can be pretty simply implemented with `RegistrationSource`, so I thought of making it a separate nuget package. Its major drawback is the interface which is inconsistent with Autofac's `Register().As()`, and I can't get my mind to how achieve this order.

A bit later I was advised to drop explicit registration in favor of attribute-based discovery. That, actually, solves the problem of syntax (if we are sure that we don't ever want the explicit registration). Again, that can be done as separate package as well, no problem in that.

I suppose that most natural way now will be to really implement my version, and then return with the the code to discuss. If that's fine with everyone, I think that this thread can be closed until then.

**Comment by tillig** [comment]
Sounds like a plan. Thanks!
