### ISSUE TITLE
Instance Creation Issue with Property injection and lazy instantiation

### ISSUE THREAD

**Issue by blsmithers** [autofac/Autofac#718]
Hi, I stumbled on an issue and think it might be similar to the issue described in https://github.com/autofac/Autofac/issues/666.  The below is failing for me with the error message "An item with the same key has already been added.".  I was hoping this case would be possible, any help you could give me would be appreciated!

```
static void Main(string[] args) {
            var builder = new ContainerBuilder();

            builder.RegisterType<A>().SingleInstance();
            builder.RegisterType<B>().SingleInstance().PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies);

            using (var container = builder.Build())
            {
                var myA = container.Resolve<A>();
            }
        }

        public class A
        {
            public A(Lazy<B> b)
            {
                var myB = b.Value;
            }
        }

        public class B 
        {
            public A A { get; set; }
        }
```

**Comment by tillig** [comment]
Verified. It does seem to be around the use of `Lazy<T>` since removing `Lazy<T>` and using `T` directly doesn't encounter this. We'll have to see if we can track this down. Thanks!

**Comment by tillig** [comment]
While the exception message is different now, this is still an issue. The issue is getting caught in `LifetimeScope.GetOrCreateAndShare` and it seems the use of `Lazy<T>` doesn't carry with it the circular property dependency information. I've added a failing unit test (skipped) to the solution.

Note we also have #798 where we're trying to figure out better circular dependency handling. The use of `Lazy<T>` needs to be considered there.

**Comment by tillig** [comment]
This appears to have been resolved with the overhaul to the internals in v6. The [skipped/failing test for this issue](https://github.com/autofac/Autofac/blob/d20dc415cfeb9b623df2195d8abb9f977591ea68/test/Autofac.Test/Features/LazyDependencies/LazyRegistrationSourceTests.cs#L50) can be marked to run and it now passes.

Fix will be released with v6.
