### ISSUE TITLE
PopulateServices() and hooks for intercepting registration?

### ISSUE THREAD

**Issue by dazinator** [autofac/Autofac#721]
As per https://github.com/autofac/Autofac.Mef/issues/6

Could populate services please allow some ability to intercept the registration such that integration with other extensions that also do things with the registration can be achieved?

**Comment by tillig** [comment]
If we did something like that, you'd just end up getting back an `IEnumerable<[IRegistrationBuilder](https://github.com/autofac/Autofac/blob/36b69bffbdd96cfe8d7a56a62b16f518dd72f590/src/Autofac/Builder/IRegistrationBuilder.cs)>` or something like that. I'm not sure how valuable that would be. Trying to unravel all of that to figure out which registration you're looking at wouldn't be terribly straightforward.

Given the context of this is sort of the MEF integration... the point of the MEF integration is more to get registrations _from_ MEF _into_ Autofac than to try to push Autofac into MEF. The `Exported` extension is convenient, but is only there for a little convenience rather than full-fledged bi-directional integration.

If you need to do this, I might recommend trying to just register services directly with Autofac rather than through the service collection mechanism. Even if you _re-register_ something that's already registered, as long as you're not resolving `IEnumerable<T>` of the thing, you'll get your later registration with the exports and everything.

For example, if you do a call to something like:

```csharp
services.AddMvc();
```

And somewhere in there it registers an `IHttpRequestIdentifierFeature` or whatever, you can always do this:

```csharp
services.AddMvc();
builder.Populate(services);
builder
  .RegisterType<Whatever>()
  .As<IHttpRequestIdentifierFeature>()
  .Exported(x => x.As<IHttpRequestIdentifierFeature>();
```

When services get resolved, Autofac will handle it with that latter registration.
