### ISSUE TITLE
Impossible to get scopes in Register lambda

### ISSUE THREAD

**Issue by AqlaSolutions** [autofac/Autofac#729]
I want `Register(IComponentContext => ...)` to return different things based on current scope. This should work faster than with registering inside `BeginLifetimeScope(builder)`. But there is no way to get current context scopes list! 

Please add this.

**Comment by tillig** [comment]
Can you give an example of what you're trying to do or how you propose a feature like this might work?

**Comment by AqlaSolutions** [comment]
I have scopes `App` and nested `User`. Each user may override configuration.

So now I'm forced to register user personal `IConfigurationContainer` instance when invoking `BeginLifetimeScope`:

    di.RegisterInstance(Application.Instance).As<IConfigurationContainer>();
        
    // ...
    
    AppScope.
           BeginLifetimeScope("User",
               b => b.RegisterInstance(userRoot).As<IConfigurationContainer>());

But I would like to register everything before building a container:

    Register(c => c.Scopes.Reverse().Any(scope=> object.Equals(scope, "User"))
                              ? c.Resolve<UserRoot>() 
                              : Application.Instance)
                  .As<IConfigurationContainer>();

**Comment by tillig** [comment]
Interesting. Already we may run into trouble in that the component context doesn't actually know about lifetime scope, just component registrations (an intentional separation of concerns); and even if it did, child scopes are not actually linked to parent scopes in any way other than having registrations from parent propagated to child. We considered linking them in #397 but ran into challenges with memory leaks and such, so decided instead to avoid that in favor of letting people control their own scope creation, usage, and disposal...

...which means there really wouldn't be any way we could offer what you're looking for in the way in which you're hoping. In fact, I'd say the recommended solution is actually what you're already doing - register the user-specific override at the time you create the scope. That's also how the multitenant integration works - when you register something "instance per tenant" the registration basically executes at the time the tenant-specific scope is created.

Given that, I'm not sure we're going to be able to provide this one. I'm going to close it due to that, though if @alexmg has any better ideas we can maybe reopen. Sorry.
