### ISSUE TITLE
No way to get scopes tags list for MatchingScopeLifetime

### ISSUE THREAD

**Issue by AqlaSolutions** [autofac/Autofac#730]
I want to be able to get scopes tags from `InstancePerMatchingLifetimeScope` when iterating through `ComponentRegistry.Registrations`. E.g. I want to activate everything registered for `Application` scope but I can't access scopes for components.

Please add this.

**Comment by tillig** [comment]
Will have to think about this one. Keep in mind there are things like registration sources that dynamically generate registrations. I worry about solutions or features that rely on iterating through the registrations collection.

On the other hand, I could potentially see something where you may query about information for a specific registration. Hmmm.

**Comment by tillig** [comment]
The initial stated desire here seems to overlap with #731.

**Comment by tillig** [comment]
Reading over these now that we've come up for air a bit from the .NET Core RTM, I think if we can address #567 - the ability for AutoActivate/IStartable to work in nested lifetime scopes - that may be the best we can do. We don't actually figure out what the `InstancePerMatchingLifetimeScope` tags are for things until the component resolves, and even then it's only used to determine which scope owns the component.

Saying something like, "auto-activate everything that was registered just for this matching scope at the time the scope is created" is sort of edge case from an IoC perspective.

One thing you could do to work around the issue is to use events and metadata.

First, when registering things, add metadata to the things you want to auto-activate.

```csharp
builder.RegisterType<MyComponent>()
  .As<IService>()
  .InstancePerMatchingLifetimeScope("child")
  .WithMetadata("scope", "child");
```

Then attach to the container `ChildLifetimeScopeBeginning` event and resolve/activate the things you are interested in:

```csharp
private static void Activate(IEnumerable<Meta<Lazy<IService>>> services)
{
  foreach(var meta in services)
  {
    if(meta["scope"].Equals("child"))
    {
      // The value of Meta<Lazy<T>> is Lazy<T>
      // The value of Lazy<T> is the resolved instance
      meta.Value.Value.DoActivate();
    }
  }
}

var container = builder.Build();

// Handle the child scope beginning event to activate everything.
container.ChildLifetimeScopeBeginning += (sender, args) =>
  Activate(args.LifetimeScope.Resolve<IEnumerable<Meta<Lazy<IService>>>>());

using(var scope = container.BeginLifetimeScope("child"))
{
  // The named lifetime scope will kick off the event handler.
}
```

(Note I wrote that stuff off the top of my head. You may have to tweak it a bit, add error handling, etc.)

Working around it with events seems like more effort, but it means a couple of things:

1. You can do everything you need to right now with stuff that's already supported.
2. It'll work perfectly with registration sources and other dynamically registered things as long as they also include the appropriate metadata.

Something we _could_ add, though, would be a "well known" metadata item on every registration that's registered using `InstancePerMatchingLifetimeScope` to include the set of tags. Then you wouldn't have to add the metadata yourself and would only have to add the event handler.

**Comment by tillig** [comment]
I added an extension method on `IComponentRegistration` to allow retrieval of matching lifetime scope tags for those components that have them. It'll be an empty enumeration if it's a singleton or otherwise doesn't have matching scope tags.
