### ISSUE TITLE
Add netstandard support

### ISSUE THREAD

**Issue by JamesNK** [autofac/Autofac#735]
RC2 is getting close. Autofac should support netstandard.

**Comment by alexmg** [comment]
The RC2 package on our MyGet feed has already been updated to netstandard. 

https://www.myget.org/feed/autofac/package/nuget/Autofac

We push across to NuGet.org after Microsoft pushes their release packages over.

Need to check out what has changed since we did the netstandard update. There's always something. =)

**Comment by tillig** [comment]
Given we're tracking the .NET Core tasks in #594 and this is on the list of things to do, I'm going to close this as a duplicate. If you're interested in tracking progress, that's a good issue to check out.
