### ISSUE TITLE
object constructed at run time by reflection with AsImplementedInterfaces() does not register the type as its interface

### ISSUE THREAD

**Issue by mayuanyang** [autofac/Autofac#736]
```
foreach (var a in _assemblies)
            {
                var reqeusts = a.GetTypes()
                    .Where(
                        x =>
                            x.GetInterfaces()
                                .Any(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IRequestItem<>)));
                foreach (var request in reqeusts)
                {
                    builder.Register(x =>
                    {
                        var baseQueueName = x.Resolve<BaseQueueNameSetting>();
                        IBus bus = x.Resolve<IBus>();
                        TimeSpan requestTimeout = TimeSpan.FromSeconds(30);
                        var rabbitMqUri = x.Resolve<RabbitMqBaseUriSetting>();
                        var addr = new Uri(rabbitMqUri + "/" + baseQueueName + "_Request");

                        var args = new[] { request, request.GetGenericArguments()[0] };
                        var constructed = typeof(MessageRequestClient<,>).MakeGenericType(args);
                        var ctor = constructed.GetConstructors()[0];
                        var client = ctor.Invoke(new object[] { bus, addr, requestTimeout, null, null });
                        return client;
                    }).AsImplementedInterfaces().InstancePerLifetimeScope();
                }
            }
```

object client of type MessageRequestClient<TRequest, TResponse> implements the interface of IRequestClient<TRequest, TResponse> from MassTransit, arguments TRequest and TResponse are being determined at run time and the client object is constructed at run time by using reflection, the container returns nothing when try to resolve to the IRequestClient with a specific TRequest and TResponse

**Comment by tillig** [comment]
Unfortunately, you have sort of a chicken/egg problem.

The lambda registration method [is a generic](https://github.com/autofac/Autofac/blob/master/src/Autofac/RegistrationExtensions.cs#L161-L169) - which is to say, the signature is `Register<T>()`. The lambda you're registering returns an `object` so this is effectively `Register<object>()`. The `AsImplementedInterfaces()` method [uses this generic to determine the "limit type" of the component](https://github.com/autofac/Autofac/blob/master/src/Autofac/RegistrationExtensions.cs#L587-L594) - that is, the actual concrete type being resolved - and uses that type to determine the set of interfaces being implemented. Basically the registration you posted reads as

```csharp
builder.RegisterType<object>().AsImplementedIntefaces();
```

The problem is that we need to know the result type of the lambda in order to add the registrations to the container _without actually having to execute the lambda to instantiate anything_. We don't go through and execute every lambda up front or we'd have other problems - things getting instantiated that shouldn't, etc.

If you need a sort of reflection-based, runtime supplier of registrations, you probably need to implement a registration source. That's how we support things like `Lazy<T>` and `Func<T>` Unfortunately, that's a pretty advanced construct that we haven't gotten documented. The best I could offer is to look at some of the registration sources we have in core Autofac:

- [`IRegistrationSource` interface](https://github.com/autofac/Autofac/blob/master/src/Autofac/Core/IRegistrationSource.cs)
- [Search for `IRegistrationSource` in the repo](https://github.com/autofac/Autofac/search?p=2&q=IRegistrationSource&utf8=%E2%9C%93)
