### ISSUE TITLE
Numeric parameters provided during registration not cast properly

### ISSUE THREAD

**Issue by kayhustle** [autofac/Autofac#738]
I've upgraded to 3.5.2 and have broken my entire project.  Take a look at the code below:

```csharp
    public class Test
    {
        public Test(double data)
        {
            
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            ContainerBuilder  builder = new ContainerBuilder();
            builder.RegisterType<Test>().WithParameters(new[] {new PositionalParameter(0, 1),}).AsSelf();
            var container = builder.Build();
            var colorBucket = container.Resolve<Test>();

        }
    }
```

This code works in 2.5.3.830, but breaks in any version >=3.0.0.0.  It seems the ability to auto cast parameters was completely removed.  My entire project was built using that ability so I have to revert to the old version.  It is amazing that you would intentionally remove that functionality so I'm assuming it has to be a bug.

**Comment by tillig** [comment]
Doing a little testing, it seems you've found an edge case where it's not working. For example, if you change the code to this:

```csharp
public class Test
{
  public Test(Exception data)
  {
  }
}

class Program
{
  static void Main(string[] args)
  {
    var builder = new ContainerBuilder();
    builder.RegisterType<Test>().WithParameters(new[] {new PositionalParameter(0, new DivideByZeroException) }).AsSelf();
    var container = builder.Build();
    var colorBucket = container.Resolve<Test>();
  }
}
```

That works - it does cast the `DivideByZeroException` to `Exception` without issue. It makes me curious if this issue is limited to primitive numbers or if it's an issue with all value types.

Anyway, given we're hard at work on 4.0 and .NET Core support, most likely if/when this gets fixed it'll be in that series.

**In the meantime, the workaround will be to cast numeric values to the appropriate type.** Again, as noted in the above test, it doesn't appear to affect everything, just numbers (or possibly value types).

Additional note: It appears the fix, if there is one, [would probably be in the `ConstructorParameterBinding` class](https://github.com/autofac/Autofac/blob/ca9ec02b5469d2fd61f6209f8b3d79f7e337188d/src/Autofac/Core/Activators/Reflection/ConstructorParameterBinding.cs#L160), where we create the dynamic expression to execute the constructor given the set of bound parameters.

**Comment by kayhustle** [comment]
Yeah this works with enums as well, I used to pass in enums that would get automatically casted to ints as well.  I'm guessing they used some type of TypeConverter or something.Would love to see this added again.
Thanks

**Comment by alexmg** [comment]
The issue with the lambda expression being generated for the constructor. When the compiled expression is invoked it is provided with an object array of arguments. The convert expression does not know that the argument type is actually an int, so the argument value must be unboxed from object to int before being cast to double. I have a unit test and fix for the expression tree but need to find a .NET Core dependency that seems to have disappeared in RC2 before pushing it up.

**Comment by alexmg** [comment]
I've pushed a fix for this to develop but the CI build is failing due to dependency issues. It appears to be working fine locally. Looks like some more CI build fun awaits.

**Comment by tillig** [comment]
Since we have this fixed and we're tracking .NET Core excitement elsewhere, I'm going to mark it closed. The fix will come out with the RC2 release.
