### ISSUE TITLE
Help Converting from StructureMap

### ISSUE THREAD

**Issue by TDK1964** [autofac/Autofac#740]
Does anyone know how to change this code to work with Autofac?

```
private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
{
	var library =
		StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance<HtmlConventionLibrary>();
	return ElementGenerator<T>.For(library, t => StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance(t), model);
}
```

This code originally comes from here
https://github.com/jbogard/ContosoUniversity/blob/master/src/ContosoUniversity/Infrastructure/HtmlHelperExtensions.cs

**Comment by tillig** [comment]
It appears [you've already asked this on StackOverflow](https://stackoverflow.com/questions/36799385/convert-structuremap-to-autofac), which is cool because not only do we (project owners) follow questions there, but we also have a large community of great folks who can help answer questions.

I'm going to close this issue and if folks know the answer, [StackOverflow is the place to go](https://stackoverflow.com/questions/36799385/convert-structuremap-to-autofac).

**Comment by TDK1964** [comment]
It's proving pretty hard to get this working with AF so I might have to give up and go with StructureMap :-(

**Comment by alexmg** [comment]
Looks like you need to replace
StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance with
AutofacDependencyResolver.Current.Resolve.

http://docs.autofac.org/en/latest/integration/mvc.html#using-the-current-autofac-dependencyresolver

**Comment by TDK1964** [comment]
@alexmg It's now working, thank you very much you are a star. Here's what I did in case anyone else needs it.

```
private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
{
	var library = AutofacDependencyResolver.Current.RequestLifetimeScope.Resolve<HtmlConventionLibrary>();
	return ElementGenerator<T>.For(library, t => AutofacDependencyResolver.Current.RequestLifetimeScope.Resolve<HtmlConventionLibrary>(), model);
}
```

**Comment by TDK1964** [comment]
Actually I was wrong it doesn't work :(

**Comment by TDK1964** [comment]
```
private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
        {
            var library =
                StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance<HtmlConventionLibrary>();
            return ElementGenerator<T>.For(library, t => StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance(t), model);
        }
```

I'm still having problems converting this to Autofac. I tried this but it doesn't work.

```
private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
        {
            var library = AutofacDependencyResolver.Current.RequestLifetimeScope.Resolve<HtmlConventionLibrary>();
            return ElementGenerator<T>.For(library, t => AutofacDependencyResolver.Current.RequestLifetimeScope.Resolve(t), model);
        }
```

**Comment by tillig** [comment]
As noted above, StackOverflow is a better bet for getting answers.

**Comment by TDK1964** [comment]
No responses on StackOverflow :(

**Comment by tillig** [comment]
Can you add a link to the question here so folks coming in can cross reference?

**Comment by TDK1964** [comment]
> Can you add a link to the question here so folks coming in can cross reference?

[https://stackoverflow.com/questions/36799385/convert-structuremap-to-autofac](https://stackoverflow.com/questions/36799385/convert-structuremap-to-autofac)

**Comment by tillig** [comment]
Oh, yep, I see it now from earlier. I guess that's what I get for trying to handle things quickly.

"...it doesn't work" isn't terribly descriptive. We have a few challenges in trying to answer your question.

- We're not StructureMap experts. I'm not personally sure what, exactly, the code is trying to accomplish. The stuff @alexmg described should handle it if I'm reading it right, but it's just a guess.
- There's no context (which was also pointed out in the StackOverflow question). You can't really just say "here's the GitHub repo where I lifted this code" - you should know what it does and why and be able to explain that, the explanation of which really should be in the question. If folks are going to spend their time - _for free_ - to provide support, your half of that implicit contract is to do the leg work to ask a detailed question and do the extra research.
- You're telling us "it's not working" but not actually what about it isn't working. Is there an exception? Is there a message? Is something null when it shouldn't be? Not null when it should be?

So here's what I'd say:

- **Let's still keep this on StackOverflow.** I think it's valuable for people who have the same (or similar) questions to be able to find the answers.
- **Update your question on StackOverflow.** Include in that question:
  - What the code _is supposed to do_. It appear's it's trying to resolve a thing out of the request lifetime scope. Is that right? If so, say that in the question.
  - How you go about executing the code. Is it part of a web app page request? Is it called from a view or from a controller class? Are you running it in a background thread/process? Is it async?
  - What you've tried so far. Include the snippet from above where you're saying it doesn't work.
  - What your object registrations into Autofac look like. Be sure to include the parts where you register `HtmlConventionLibrary`.
  - If it's not working, _what's not working_. If there are exceptions, include them - the whole exception, not just the message. If there is some behavior that's wrong, explain that.
- **If you haven't asked the StructureMap folks the same question, [go do that, too](https://github.com/structuremap/structuremap/issues)**. They have just as much chance of getting it right as we do since they know as much about our stuff as we know about theirs.
- **Let us know when the question over on SO is updated** so we can go back and take a look. Again, please post all these details there rather than back in this issue so the whole community can benefit.

Sorry you're having trouble, but hopefully this will help you get things working in a faster way than waiting solely on us for an answer.
