### ISSUE TITLE
An exception in ResolveOperation when trying to Resolve struct by itself

### ISSUE THREAD

**Issue by AqlaSolutions** [autofac/Autofac#749]
`scope.Resolve<SomeStruct>()`

Are structs supported?

**Comment by alexmg** [comment]
Value types are usually used as simple data containers and aren't normally the kind of thing that you would take on as a dependency.

Structs aren't explicitly supported and I'm not surprised that reflection based activation fails as the expression tree will not be expecting to return a value type.

That said, you could still resolve one using a lambda based registration.

`builder.Register(c => new SomeStruct()).AsSelf();`

That seems to compose with relationship types such as Func, Owned, Lazy etc. I can't say that it would work in all cases though.

Was there a specific scenario that you are trying to support?

**Comment by AqlaSolutions** [comment]
@alexmg I extracted all dependencies from class constructor to a struct (which also have its injection constructor) so I can:

1. Pass all dependencies from factory method to target class without messing parameters list up.
2. Pass additional contextual parameters to class constructor without resolving normal parameters separately - only one Resolve<Dependencies>() instead.


```
     class MyClass
     {
        public MyClass(int someValue, bool otherValue, Dependencies deps)
        {
           //...
        }
        public MyClass SmartFactory(string additionalData, Dependencies deps)
        {
              // ...
              return new MyClass(.., deps);
         }
     }
   
```

**Comment by tillig** [comment]
Have you tried the [Aggregate Services](http://autofac.readthedocs.io/en/latest/advanced/aggregate-services.html) support? It doesn't solve the `struct` problem, but may help in this situation of trying to minimize the number of constructor dependencies into a single service.

**Comment by AqlaSolutions** [comment]
@tillig ah, I should try it, thank you! But please do not mark this issue as just a question. You should either make it work for structs or explicitly state in the documentation that value types construction is not supported.

btw does Aggregate Services workaround "How do I pass a parameter to a component in the middle of a resolve chain?" problem? I expect that parameter passing to Aggregate Services doesn't work but it looks like an interesting improvement because it would be quite useful to still be able to pass parameters even when some dependencies are extracted to an Aggregate Service.

**Comment by tillig** [comment]
Right now it's a question about whether structures work or not. Once we figure out the right way to answer it, we can update to bug, enhancement, wontfix, or whatever. Don't worry too much about how we classify the issues, it just helps for organization and isn't a reflection on you.

No, there's no great solution anywhere for "pass a parameter to a component somewhere deep in the stack of what's being resolved." If you run into that problem, generally we find it indicates a design issue with how the dependencies work (e.g., you may need two different dependency interfaces rather than a single one that behaves differently by parameter). A question like that is great to ask on StackOverflow and tag it `autofac` so you can get better community input.

**Comment by alexmg** [comment]
The structs don't work with reflection based registrations, and as this is not a common scenario, I don't think adding support for them is worth the additional complexity. If you really need to resolve structs it is possible using lambda expressions.
