### ISSUE TITLE
Composing in a convention-based manner using async static Factory Methods returning Task<T>

### ISSUE THREAD

**Issue by bartelink** [autofac/Autofac#751]
I've managed to go a long way `AnyConcreteTypeNotAlreadyRegisteredSource` together with delegate factories as my primary building block (OK, golden hammer) for avoiding having explicit reams of registration logic. However, I've run aground in attempting to [ab]use Autofac to do Method Injection (in DI in .NET parlance) into an Async Factory method.

I've described it in detail in my [SO self-answered question on the topic](http://stackoverflow.com/questions/33524706/autofac-registering-an-async-factory-method), including my hack-arounds (I'm OK with my final one for now). Essentially I'm looking for a mechanism to either declaratively or intrinsically have an `async` method be supplied its arguments [effectively] via a `_container.Resolve<TArg>()`.

For example, given:

    class A 
    {
        public A(Dep1 d1, Dep2 d2) { ... }
    }

    class B
    {
         public B(A a, C c, D d) { ... }
    }
 
    var b = container.Resolve<B>(); // works

I can resolve `B`, and I can use delegate factories to supply some of the args for `A`'s ctor. However, when I need to do anything `Async` in the process of  building `A` or `B`, things break down and I'm left with having to do explicit registration / chaining such as :-

    class A 
    {
        public static Task<A> Create(Dep1 d1, Dep2 d2) { ... }
    }

    class B
    {
         public B(A a, C c, D d) { ... }
    }

    var a = await A.Create(container.Resolve<Dep1>(), container.Resolve<Dep2>())
    container.RegisterInstance(a)
    var b = container.Resolve<B>();

or other explicit manouvres such as

- pass `a` as a named parameter to a resolve of `B`
- use Delegate Factories to define a `delegate B Factory(A a)` and then hydrate via `var b = Resolve<B.Factory>()(a)`
- etc.

NB [this is a long-shot](https://twitter.com/nblumhardt/status/734872773714051073) and way off the beaten track for a Container. Please don't hesitate to cull this if this doesnt sound sufficiently relevant or mainstream.

I'm not particularly concerned about performance so e.g. some convention-based mechanism relying on reflection is acceptable for me.

Perhaps something like the general convention Ninject has of using a static Factory Method if there are no public constructors (it doesn't have native support for something of this nature AFAIK). It (all-but) feels like `Task<>` might fit as a Relationship Type?

Any ideas? Does any of this make any sense? Anyone else using a convention/pattern like my `LazyAsyc` as a Relationship Type to accomplish this without any direct support from Autofac?

**Comment by tillig** [comment]
Without going too deep, I'm not sure async resolution of anything is something we'd really jump into since resolution (effectively object creation) should be really, really slim - so slim you'd never do it asynchronously; or optimized such that expensive things are done as little as possible (like registering something as a singleton) so, again, you'd never do it asynchronously.

While I can see some edge case need, I'd be afraid of adding something like this and then having people say, "Oh, well, it's _supported_ so it must also be _recommended_." Sort of the way TypeMock got a bad rap for being "too powerful" of a mocking framework because people just couldn't rein themselves in and abused it rather than just using it correctly.

(And, yeah, I do get the whole "async read some config and do something based on that" use case. I have it myself. I generally set up caches and timers to handle the async out of band and don't involve my factory methods with the actual read operations.)

On supporting it as a relationship type, I've found some interesting and odd behavior when trying to convert sync to async or vice-versa around incorrectly set continuations, lost synchronization contexts, and so on. It would be tricky at best to get it to work correctly and consistently.

I'd personally look at using assembly scanning and modules over the ACTNARS for easier registration. It may help get you out of some of this.

Anyway, again, that's without diving too deep and only giving it a few minutes' thought. I'll have to noodle on this some more, but I'm initially generally inclined to say we probably wouldn't add something like this.

@alexmg may have some additional thoughts.

**Comment by bartelink** [comment]
@tillig Thanks - can't argue with any of this.

Certainly mixing async into something sync which is already full of concepts would certainly be A Bad Idea (and as [`LazyTask`](http://stackoverflow.com/questions/33872588/caching-the-result-from-a-n-async-factory-method-iff-it-doesnt-throw) demonstrates, there's no one-size fits all in `Task<T>` land. While a neat solution may exist, I'll be impressed if it does.

I guess all that remains is to attempt to flailingly pivot my request into a more/constrained granular "Delegate Factory for Factory Method" mechanism, which allows one to put a delegate definition :-

    class X
    {
         public delegate X Factory(args);
         public static X Create(args)
    }

where `args` is the existing manner in which existing delegate factories have arguments selectively furnished to them, with the only real difference being that one is binding to a `static X Create()` instead of a `static X .ctor()`. (And I would then proceed to say "by the way, the X I'm after is in fact `Task<X>`, which is what my `Create` method actually returns).

Were something of that nature to be possible, I'd then be able to do a variety of things such as:
- `Resolve<X.Factory>()`
- `container.Register(c=>LazyTask.Create(c.Resolve<X.Factory>())) (Which would enable `await container.Resolve<AsyncTask<X>>()`)

Anyway, I'm just pondering here and am definitely comfortable with this being Closed unless such a facility actually represents a generally applicable pattern (AutoFixture's `fixture.Get(X.Create)` is the only place I've encountered it and that's obviously far off the beaten track of application logic)

**Comment by tillig** [comment]
After looking through various service locator and dependency injection container interfaces, and thinking pretty hard on this, it doesn't appear that this is really a scenario I think we'll want to enable. Executing async code during object instantiation isn't really a good idea, even if it's a factory doing that execution. At some point it has to become synchronous since things like singletons need to be originally initialized in a synchronous fashion, locks need to be made so things don't get double-instantiated, and so on.

If you need to register an async factory delegate, it'll be up to you to convert that to synchronous by doing something like...

```
builder.Register(ctx =>
  {
    var factory = ctx.Resolve<TheFactory>();
    var obj = factory.Create().GetAwaiter().GetResult();
    return obj;
  }).As<MyThing>();
```

That would also let you configure the awaiter or handle call context as needed without requiring the container also add support for things like cancellation tokens, call context configuration, and so on. (Again, _inside the container_ is where it all has to boil down to synchronous.)

**Comment by bartelink** [comment]
@tillig Definitely agree that the container definitely should not be in the business of doing sync-over-async

Am fine with this being closed.

Your example in the above is definitely _not_ what I'm suggesting - all awaits should **always** be outside of the container _**and**_ the registrations.

To say it another way, the mechanism I was describing was that 

1. delegate factories allow one to supply just the relevant arguments to a ctor _without any registration/container dependency_ - the container merges the supplied arguments and the inferred ones and synthesizes a call to the target constructor, the return type of which is `T`
2. in `*Async` land

  - we still want the container to synthesize a call to a method
  - we still want the container to fill in the gaps a la delegate factories
  - we still want the relevant args to be passed through to a method
  - we still want an instance of the type the method yields (which is a `Task<T>`), and the `delegate` return type will reflect that

In other words, what I'm suggesting that Autofac would need to do to support Async delegate Factories is add a special case to resolving of a `delegate` type when normal delegate factory handling has not been applicable:

  - if the Type within which the `Factory` delegate is nested has a `static` method returning the Type being requested, yield an instance of the delegate type, which delegates to said method and yields its return value.

So where one normally is generating:

    TResult t =newobj T
    push args
    call static specialname T.ctor(argset)
    ('return' t)

One now 'simply' generates a straight call to the Factory method:

    push args
    call static specialname TResult T.Create(argset)
    (return result of previous call)

(Anyway, I'll leave the horse alone now and hope for a swift return to a Pure DI world so no such twisted ideas enter my head again!)
