### ISSUE TITLE
Constructor declaring type null when walking the stack on resolved object

### ISSUE THREAD

**Issue by AqlaSolutions** [autofac/Autofac#753]
When a type is resolved from Autofac, third-party code that attempts to retrieve the declaring type via stack walking fails with a `NullReferenceException`.

    [TestFixture]
    public class AssemblyStackTest
    {
        [Test]
        public void Execute()
        {
            var builder = new ContainerBuilder();
            builder.RegisterType<SomeType>().AsSelf();
            var di= builder.Build();
            di.Resolve<SomeType>();
        }

        public class SomeType
        {
            public SomeType()
            {
                Logger.GetCurrentClassLogger();
            }
        }

        public class Logger
        {
            public static void GetCurrentClassLogger()
            {
                var stackFrame = new StackFrame(2, false);
                MethodBase methodBase = stackFrame.GetMethod();
                Type declaringType = methodBase.DeclaringType;
                Assert.That(declaringType, Is.Not.Null);
            }
        }
    }

In this test, the declaring type ends up being null.

The use case is that a third-party library has the stack-walking code to set up logging. It's not part of application code.

The test fails in both debug and release configurations, but in the app it can only be reproduced with with optimization of _my code_ enabled.

Is there a workaround or a way this can be fixed from an Autofac perspective?

**Comment by tillig** [comment]
I'm not sure I totally understand what you're asking for here - "all generated stuff" is sort of vague. Can you post a repro, preferably in a failing unit test, so we can see what's happening?

A thought off the top of my head (e.g., without diving in, doing research, spelunking code) - with Roslyn and more compiler-as-a-service sorts of evaluation of dynamically generated code, this sort of third-party code looking at stack frames like this may need to be updated. I'm not a Roslyn expert, but I'm guessing from the symptom you're seeing that there may not actually always be an assembly from which code runs... and that being an optimization (probably for memory/app footprint) we probably wouldn't want to de-optimize it or second-guess it.

**Comment by AqlaSolutions** [comment]
Sorry, the problem is with declaringType, not assembly. 

Test:
```
    [TestFixture]
    public class AssemblyStackTest
    {
        [Test]
        public void Execute()
        {
            var builder = new ContainerBuilder();
            builder.RegisterType<SomeType>().AsSelf();
            var di= builder.Build();
            di.Resolve<SomeType>();
        }
        
        public class SomeType
        {
            public SomeType()
            {
                Logger.GetCurrentClassLogger();
            }
        }

        public class Logger
        {
            public static void GetCurrentClassLogger()
            {
                var stackFrame = new StackFrame(2, false);
                MethodBase methodBase = stackFrame.GetMethod();
                Type declaringType = methodBase.DeclaringType;
                Assert.That(declaringType, Is.Not.Null);
            }
        }
    }
```

**Comment by tillig** [comment]
I potentially miscommunicated - I was speaking less of the performance of the generated delegates and more about overall application footprint (size in memory, size on disk) and performance (writing to disk vs. not writing to disk); not whether they're associated with a type.

The point of the statement was that I'm reluctant to turn off some performance optimization provided by the compilation mechanism to accommodate for an edge case in third-party code; I think it'd be worthwhile to raise the issue to the third-party and see if they may be able to provide a fix or workaround.

We'll continue investigating on this end, but I think if the solution ends up being along the lines of "turn off a compiler optimization" or "set a flag to force something to be written to disk that otherwise wouldn't have been" then we may end up not fixing this.

**Comment by AqlaSolutions** [comment]
@tillig, Ok, I just don't really think that fixing this may have a real impact on performance, it's not related to writing to disk or compiler optimization.

**Comment by tillig** [comment]
> When optimization is enabled `repositoryAssembly` becomes null when the constructor is called from Autofac which causes `NullReferenceException`.

Did I misunderstand the circumstances in which the issue was appearing?

**Comment by AqlaSolutions** [comment]
@tillig 

> Sorry, the problem is related to DeclaringType, not Assembly. 

In the test:
                `Assert.That(declaringType, Is.Not.Null);`

In real app:

`Assembly repositoryAssembly = declaringType.Assembly;`

**Comment by AqlaSolutions** [comment]
@tillig about optimization - it's client code optimization, not `AutoFac`

**Comment by tillig** [comment]
OK, I'm going to update the original issue/note then so there's no confusion.

**Comment by AqlaSolutions** [comment]
@tillig the test fails in debug mode too but in the real app I could reproduce it only with optimization of *my code* enabled.

**Comment by tillig** [comment]
Updated the initial issue posting to include the failing test and a more concise description of what's going on. Also updated the title of the issue to reflect the changes. Feel free to modify further if there's an incorrect/incomplete statement.

**Comment by tillig** [comment]
I researched why this is and it boils down to the way the `ConstructorParameterBinding` class works: After reflecting to determine the various available constructors vs. what it can fulfill, [it generates a cache of lambda methods that can be invoked to execute the constructor](https://github.com/autofac/Autofac/blob/1cc36da7b8071c24eef1ee209c2745ccc646c6f0/src/Autofac/Core/Activators/Reflection/ConstructorParameterBinding.cs#L43).

Using a compiled lambda like that [actually does have better performance](http://www.palmmedia.de/Blog/2012/2/4/reflection-vs-compiled-expressions-vs-delegates-performance-comparision) than going with reflection and it has a lower memory and startup overhead than creating types on the fly with Roslyn or compiler services.

Unfortunately, I think this is going to be a "won't fix" since trying to ensure there's a stack trace from every place we resolve something is going to be challenging at best - there is a lot of lambda/closure/functional stuff we're doing to make things easier inside the code and move much faster and I don't see us rolling that out. Sorry.

Potentially related/interesting: [they still don't even have a full StackFrame implementation in .NET Core](https://github.com/dotnet/corefx/issues/1797) so making such a radical change would only be something we could get working on one of many platforms at this point.

**Comment by AqlaSolutions** [comment]
@tillig with dynamically generated lambdas you can attach them to "owner" type, especially DynamicMethod approach will work, look at the `owner` parameter: https://msdn.microsoft.com/en-us/library/0fe7t256%28v=vs.110%29.aspx

**Comment by tillig** [comment]
I appreciate what you're saying, but I'm not sure you get the amount of internal framework churn making a change like this would actually be. I'm also honestly not sure how to assign an owning type to a `Func<T>` created on the fly - like how do you say...

```
Func<string> invoker = () => "Hello World!";

// What do you do here?
invoker.OwnerTypeThing = typeof(ContainerBuilder);
```

Let's say we _could_ do that. I don't think you can, but it's possible I'm missing something.

(And, again, the stack frame example you posted was broken based on a lambda created a lot like that - not through Reflection.Emit or LINQ expression compilation.)

- Every time we use `Func<T>` (which is, like, everywhere) we'd have to modify that with assigning an owner type. You couldn't do it in one or two spots, you'd have to do it everywhere - because who knows how deep in the tree someone's going to try to create a new `StackFrame`?
- That addition would have to happen not only in core Autofac but also in all 23(!) integration libraries to ensure compatibility with the functionality.
- Any time someone passes in a factory delegate to create an object, we'd need to check that passed in delegate and assign it an owner type (somehow) if it's not already assigned.
- Any pull requests or contributions that anyone makes will need to behave in this totally non-standard, non-obvious way to ensure ongoing support.

Truly, I sympathize with the challenge you're running into here, but this isn't something we're going to remedy. If you're really that stuck, I would recommend looking for other workarounds:

- Create your own logging factory that has similar code to the third-party one but doesn't use a stack frame to automatically determine type.
- Request an update to the third-party software to have them be more DI friendly.
- Wrap the logging factory in a small proxy factory so the stack frame will locate the type being instantiated rather than one stack frame too high.
- Use Castle.DynamicProxy in a way such that a proxy gets generated with a stack frame to your liking.

**Comment by AqlaSolutions** [comment]
@tillig ,

> Every time we use Func<T> (which is, like, everywhere) we'd have to modify that with assigning an owner type.

This is totally wrong. In your example with `Func<string> invoker = () => "Hello World!"` the compiler will actually create a static method or a complier generated scope class to hold captured variables and `return "Hello World"` method.

Only dynamically generated in runtime methods can be not attached to an owner type.

**Comment by AqlaSolutions** [comment]
@tillig , can you link where the actual dynamic method or Expression or Reflection.Emit is used to generated construction lambda? Then I could try to find how can such lambda be attached to some type.

**Comment by tillig** [comment]
How about this: If you think you can fix it without breaking anything else, please feel free to submit a PR. We would be happy to investigate it more at that time.

**Comment by AqlaSolutions** [comment]
@tillig , I made a working example how you can convert your dynamic lambdas to static methods. It should work with the same speed but I didn't actually test it. It would take some significant time for me to understand internals of Autofac, can I expect you or someone from contributors to implement this? Mind that this way may be not for all platforms so conditional compilation may be needed!


        [Test]
        public void LambdaTest2()
        {
            var asm = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("test"), AssemblyBuilderAccess.Run);
            var masm = asm.DefineDynamicModule("main");

            var type = masm.DefineType("TestType");
            var mb = type.DefineMethod("TestMethod", MethodAttributes.Public | MethodAttributes.Static, typeof(int), new Type[0]);

            // your lambda
            ConstantExpression expressionTree = Expression.Constant(0);
            Expression.Lambda(typeof(Func<int>), expressionTree).CompileToMethod(mb);

            var m = (Func<int>)Delegate.CreateDelegate(typeof(Func<int>), type.CreateType().GetMethod("TestMethod"));

            Assert.That(m.Method, Is.Not.Null);

            // you can create another in the same module but with another type (because type can't be changed)
            var type2 = masm.DefineType("TestType2");
            var mb2 = type2.DefineMethod("TestMethod2", MethodAttributes.Public | MethodAttributes.Static, typeof(int), new Type[0]);

            // your lambda 2
            ConstantExpression expresisonTree2 = Expression.Constant(1);
            Expression.Lambda(typeof(Func<int>), expresisonTree2).CompileToMethod(mb2);

            var m2 = (Func<int>)Delegate.CreateDelegate(typeof(Func<int>), type2.CreateType().GetMethod("TestMethod2"));

            Assert.That(m2.Method, Is.Not.Null);

            // check correctness
            Assert.That(m(), Is.EqualTo(0));
            Assert.That(m2(), Is.EqualTo(1));
        }

**Comment by tillig** [comment]
We're _really trying to avoid conditional compilation_ and be fully portable in the new .NET Core world... and having this in place isn't really on the priority list - hence why I mentioned if you can PR a complete fix, we'd consider it. Doing a search for `Expression` in the code yields several places where there is expression compilation and all of them would need proper updating. I didn't go through the extension libraries to see where all those would need updating.

BTW, you are right about the compiler assigning ownership to standard lambdas - I was wrong in that above.

Anyway, [being swamped with a lot of other things](http://www.paraesthesia.com/archive/2016/06/29/netcore-rtm-where-is-autofac/) and having far higher priority stuff to implement and fix, we're still not really interested in taking this any further. If you value it enough and would like to implement it, we would be happy to take the PR.
