### ISSUE TITLE
Feature - lambda-based resolution by context, per service

### ISSUE THREAD

**Issue by kierenj** [autofac/Autofac#763]
I'm looking to build an extensible framework as a collection of modules (NuGet packages in this case).

Here's an example scenario:

* Framework provides `ILogger` and `IConfiguration` interfaces, with `LogMessage()` and `GetSetting()` methods
* User app can indicate that it wants to use `YamlConfiguration` and `LogstashLogger` in general
* User app also references the `MyFramework.StripePayments` package (for example)
* This other package also wants `ILogger` and `IConfiguration`, for knowing about private keys, where to log fraud alerts, etc
* User app wants to configure this package to use `EncryptedXmlConfiguration` and `SmsLogger` implementations

The framework will probably abstract the actual DI mechanism away from the user, but it would be great to use something like Autofac to actually do the deed.

I found the excellent guide, http://docs.autofac.org/en/latest/faq/select-by-context.html - but I don't believe there's an appropriate solution there for this use case.  I may be wrong - and would happily welcome some opinion or ideas :)  Here's my rationale for that statement:

* Redesigning interfaces - e.g. `interface IStripePaymentsConfiguration : IConfiguration` - breaks LSP too much for me; it really does just need `IConfiguration`
* Changing registrations - e.g. `builder.Register(ctx => new StripePaymentDispatcher(...);` - `IComponentContext` doesn't seem to give me the context about the injection site
* Use keyed services - e.g. `builder.RegisterType<EncryptedXmlConfiguration>().As<IConfiguration>().Keyed<IConfiguration>("MyFramework.StripePayments")` - would need an external (from Autofac) mechanism to iterate services, build progressive `.WithParameter()` calls using reflection.  Also, the framework would have to register services multiple times, for each module/package (not sure if that adds much overhead)
* Use metadata - looks effectively the same as the keyed approach to me currently

Other than that, I looked into a custom Registration Source (ala http://docs.autofac.org/en/latest/advanced/registration-sources.html).  However, it doesn't look like appropriate context is available there to know about "who" is requesting.

To simply be able to examine the type being injected and the injection site's type within the context of a lambda would seem to add a huge amount of flexibility and extensibility.  At the moment I can't really see the downside.  For example, for something like this to be possible (hardcoded example):

```
class InjectionSite // an Autofac class
{
    public TypeInfo TargetType { get; }
    public MemberInfo TargetMember { get; } // only relevant for property injection..
}

class ComponentSelectionContext // an Autofac class
{
    public Service RequestedService { get; }
    public IEnumerable<IComponentRegistration> Registrations { get; } // many, since may not be a direct dependency
    public IEnumerable<InjectionSite> InjectionSites { get; }
}

Func<ComponentSelectionContext, IComponentRegistration> configSelector = (ctx)
{
    var defaultReg = ctx.Registrations.First();

    // bail out unless we want to override
    var swt = ctx.RequestedService as IServiceWithType;
    if (swt == null || swt.ServiceType != typeof(IConfiguration)) return defaultReg;

    // check to see if Stripe wants this service
    var types = ctx.InjectionSites.Select(s => s.TargetType);
    var isStripe = types.Any(t => t.FullName.StartsWith("MyFramework.StripePayments"));
    return isStripe ? _stripeConfigRegistration : defaultReg; // use specific override if so
};

builder.RegisterSelector<IConfiguration>(configSelector);
```

Please note that I'm not a DI expert, so may have missed an alternative approach.  I'm also not experienced with the Autofac API, so this may be in the wrong style.  I would welcome feedback - but still think this is an idea worth putting forward / discussing!

**Comment by tillig** [comment]
If it's two different things needing two different configurations from two different configuration sources, I actually would recommend going with two interfaces, even if they're "marker" interfaces. I've done this many times in my own projects and it has always proven out - the simple fact that they literally can't be interchanged indicates they aren't the same thing - much like the way the select-by-context example explains.

I have on occasion used metadata to indicate something like "purpose," which it sounds like you've touched on. Something like this works pretty well.

```csharp
builder
  .RegisterType<FirstConfiguration>()
  .As<IConfiguration>()
  .WithMetadata("Purpose", "first");
builder
  .RegisterType<SecondConfiguration>()
  .As<IConfiguration>()
  .WithMetadata("Purpose", "second");

// Then in the constructor...
public ConfigConsumer(IEnumerable<Meta<Lazy<IConfiguration>>> providers)
{
  // Get the correct implementation and lazy-resolve it so we don't
  // actually new-up literally every provider if we don't need to.
  _myProvider = providers.First(p => p.Metadata["Purpose"].Equals("first")).Value;
}
```

You can obviously get much fancier with it than that. You can even [use the `[WithMetadata]` attribute to automate a good majority of that.](http://autofac.readthedocs.io/en/latest/advanced/metadata.html)

```csharp
public ConfigConsumer([WithMetadata("Purpose", "first")] IConfiguration configuration)
```

Another thing I've done is use an abstraction like [Microsoft.Extensions.Configuration](https://github.com/aspnet/Configuration) and pass around the _whole configuration collection_ to things. Individual components know about their own sections of configuration and request keys accordingly. For example, one component might get keys from the `system:data:firstComponent` section of configuration and another might come from `environment:connections:secondComponent` section. _Technically_ each component could request information from configuration about stuff coming from the other component... but it means that the configuration is treated the same everywhere, much like application settings or anything else where _the application_ is configured and not _individual components_.

Finally, another option might be to adapt something like [the log4net module example](http://autofac.readthedocs.io/en/latest/examples/log4net.html) to your needs, centralizing the one place that dynamically adds the parameter to the resolution.

I'm not a big fan of "pick a different service implementation based on context" for a few reasons, most of which are outlined on that select-by-context page. I understand some devs like that (or at least don't think it's a big deal), but I think adding formal support for such a thing is akin to the challenges the community has raised with profiler-based mocking frameworks: because those sort of frameworks _enable_ folks to design in a way that may not be the best, it can be implied that they also _encourage_ that mode of design instead of requiring the design itself to address the challenges.

I could potentially be swayed, but I'd probably need to see a really good concrete use case where changing the design just couldn't get around such an issue.

**Comment by kierenj** [comment]
Thanks, I didn't appreciate the metadata system could quite work like that.

The configuration and logging examples were to be illustrative, in reality things are a little different.  That said, I don't have a strong counter-argument - I can think of a workable alternative way in each case that I think up.

I think I just have the idea and design of a hierarchy/namespace-based module hook-up-and-configure system in mind, and thought having a hook right at the point of selecting an implementation would do the trick.

I guess it comes down to whether the modules themselves should be annotated as "special cases" which can be reconfigured (i.e. throw metadata labels on them), or its up to the container configuration to do so.  Dare I go crazy and suggest abstracting IoC frameworks too, that might add to my gut feeling that it's the job of container config in my case.

The log4net module example looks to show an appropriate place to hook - and a `Module` seems a nice place to wrap up system-bucking hacks - thank you.  I think the only gap is the context provided - if a module has an indirect dependency on something (e.g. maybe `StripePaymentDispatcher` uses `ITemplatedLogger`, which in turn reads resource strings and uses `ILogger`), I don't think I can configure which implementation to use there, since I only have access to the specific `ParameterInfo` delcaring type, so the context is lost?

(Thanks for taking the time to chat around this - very much appreciated)

**Comment by tillig** [comment]
If you get into a weird situation where you have a chain like `A -> B -> C` the way you hypothesize with your logger and `C` needs to know about `A`... **you're definitely into design-problem land.** Things like that are great times to use generics. Instead of `ILogger` you'd have `ILogger<MyThing>` that takes an `ITemplatedLogger<MyThing>` or whatever.

I don't find I run into situations like this very often unless I'm converting a system that _wasn't_ designed with IoC in mind into a system that _uses_ IoC. When I do find those rare times, I like to stop and take a step back and ask, "If I wasn't manually constructing all of this - if I had to instruct a computer to do it - not using any sort of auto-wiring container, but just walking through the steps of what it would take to write a factory for this... how much do I have to 'know' about what's going on vs. how much can I just pass parameters in and call it a day?" Then expand to a second case - "Oh, wait, it turns out this thing needs to 'know' about the type of that other thing in order to work properly... looks like an interface design change needs to be made."

There are lots of things that abstract the container - from ASP.NET Core to the classic CommonServiceLocator. I wouldn't worry about that. If thinking about how you are _resolving_ the types or how you're abstracting out the container comes into the picture, you may be overthinking it. Yes, you probably need to address some of your issues with container configuration, from using `ResolvedParameter` to modules to metadata... but you also probably need to take a think about your interfaces and consider whether "just having the same methods" really means they are interchangeable from a usage standpoint. This touches on that "select-by-context" page.

I'm going to go ahead and close this up since I think you have enough to go on to get you unblocked. I don't think there's really any other general advice I can offer. If you're still stuck, we have a vibrant community of people [on StackOverflow](http://stackoverflow.com) (tag your question `autofac`) who can help you with concrete implementation questions; and we also have a [discussion group](https://groups.google.com/forum/#forum/autofac) for chatting about more general/wide ranging topics that may be less appropriate on StackOverflow. Both of those places will probably get you more viewpoints (and faster responses) than the issues list here, especially since a lot of our time in recent days has been struggling to keep up with .NET Core changes.

Good luck!
