### ISSUE TITLE
The requested service has not been registered - but it has?

### ISSUE THREAD

**Issue by dazinator** [autofac/Autofac#774]
I am using the following packages, within in `asp.net core` application targeting `net452`

```
    "Autofac": "4.0.0-rc3-309",
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc3-309",
    "Autofac.Mef": "4.0.0"
```

The problem I am facing is that I am registering a service into the container called `IThemeService` and I can see the registration on the containers `ComponentRegistry`.

![image](https://cloud.githubusercontent.com/assets/3176632/16955701/91d788c4-4dcd-11e6-8f48-e2e078fc2743.png)

However when I do:

```
 IServiceProvider provider = _container.Resolve<IServiceProvider>();
 var themeService = serviceProvider.GetRequiredService<IThemeService>();
```

I get this exception:

![image](https://cloud.githubusercontent.com/assets/3176632/16955851/1b0f635a-4dce-11e6-93d4-cef2ffde3265.png)

I have no idea how to debug this issue, would appreciate any pointers from Autofac guru's!

**Comment by tillig** [comment]
Have you asked this on StackOverflow? That's a good place to start for questions like this since we have limited time and there's a huge community over there that can help.

When I run into things like this I think about:
- Am I doing any sort of dynamic registration?
- Is it possible that there are two versions of the same assembly ("ABC.dll" v1 and v2) both loaded in the AppDomain such that the _name of the type_ is the same but it's not matching because the _version_ is wrong?
- Did I do a clean build, removing everything - cached files, cached NuGet packages, bin/obj folders, my .user files, the .vs folder, etc?

If that doesn't help get you started, again, I _strongly encourage_ you to ask on StackOverflow and tag it `autofac`. When you do, post a link to the question here. We can then close this issue and take the answering to the community. We project owners also monitor StackOverflow, it's just that [especially recently, we have a lot to do so you could be waiting a long time for an answer](http://www.paraesthesia.com/archive/2016/06/29/netcore-rtm-where-is-autofac/). Allowing the community to take a stab at answering could get you something sooner.

You may need to include a lot more in your question when you ask - a repro, some additional code showing how you register your types, etc.

**Comment by dazinator** [comment]
Ok cheers, think it was to do with loading assemblies from a byte array. Loading from disk works. Thanks for the response.
