### ISSUE TITLE
How to inject IContainer into each module?

### ISSUE THREAD

**Issue by denghejun** [autofac/Autofac#775]
hi, I want to inject IContainer(it is a global one) into each modules, and **_the reason I do this was that each modules may be use the same global container to Resolve() some dependency (services) later._**
I tried below: _(**two pieces codes are in different assemblies**_.)

```
    var builder = new ContainerBuilder();

    var container = builder.Build();

    var builder1 = new ContainerBuilder();

    builder1.Register((c, t) => container).As<IContainer>().SingleInstance();

    builder1.RegisterModule(new ConfigurationSettingsReader());

    builder1.Update(container);
```

and one of the modules:

``` 
public class ModuleIdentify : Autofac.Module
    {
        public static IContainer Contanier;

        public ModuleIdentify(IContainer containner)
        {
            Contanier = containner;
        }

        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterType<App>().As<IApp>();
        }
    }
```
but it failed. can you help me?

**Comment by tillig** [comment]
Before I answer this, _some huge disclaimers_:

**You are way, way outside the supported path with what you're trying to do here.**

There is a lot of complexity that I'm sure it appears your app needs but if you are trying to use one container to help build another container and you're using modules to update that second container based on contents of the first container... You should stop and try to unwind this.

**Generally try to consider containers immutable.** Modules are used to register things directly into the container rather than taking a module and updating a container after the fact.

Now, the answer:

**Modules don't go through DI.** They're not components like when you call `builder.RegisterType<T>()`. When you call `RegisterModule()` all that's doing is saying, "Open up this module and run the registrations inside." It's not resolved from the container, it doesn't pass through the pipeline. It's just a configuration mechanism. You can prove this out by trying to _resolve_ the module later - you'll find it's not registered.

If you want to pass something into a module as a parameter, you have to do that manually.

`builder.RegisterModule(new ModuleIdentify(container));`

I'll update our documentation to clarify that modules don't go through DI and that a best practice is to consider a container immutable.
