### ISSUE TITLE
Wrong property injection in AutoFac 4.0.0 (3.5.2 works correct)

### ISSUE THREAD

**Issue by Kostusev** [autofac/Autofac#789]
**Why in code below property "Name" is being injected by autofac?**
```c#
using System;
using Autofac;

namespace AutoFacBug
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var containerBuilder = new ContainerBuilder();
            containerBuilder.RegisterType<A>();
            var container = containerBuilder.Build();

            var a = container.Resolve<A>(TypedParameter.From("TEST"));
            Console.WriteLine(a.Name);
        }
    }


    internal class A
    {
        public A(string id){ }
        public string Name { get; set; }
    }
}
```

**Comment by tillig** [comment]
Yow! Nice find. Let's see if we can figure this out.

**Comment by tillig** [comment]
OK, this happens now because of the fix for #289. The previous implementation of parameter usage wouldn't allow you to pass parameters in at resolve time and have them considered for property injection unless you had already explicitly configured property injection.

There's some potentially confusing behavior with the update where _all_ passed in parameters are considered for property injection.

Some options I can think of for fixing this include...

- **Add a flag to parameter objects that indicate whether the parameter itself supports property injection.** The `NamedPropertyParameter` would have this enabled by default. Other parameter types would have it turned off by default. In a resolve operation you could do something like `c.Resolve<A>(TypedParameter.From("a").IncludeProperties())` when you want the parameter to act on properties; otherwise it'd only act on constructor parameters.
- **Remove the current behavior and enable `InjectProperties` to take parameters.** The `AutowiringPropertyInjector.InjectProperties` method would be updated to allow parameters to be provided. The default resolution mechanism would be reverted (`ReflectionActivator.InjectProperties`) to do what it was doing before, but overloads for `InjectProperties` and `InjectUnsetProperties` extensions would be added to take parameters for consideration. This would allow `PropertiesAutowired()` to consider passed parameters _or_ you could manually call `scope.InjectProperties(obj, parameters);` if you wanted to inject properties on an object that didn't already have property wiring set up. Going this route would mean that `Resolve<T>(...)` passing in a `NamedPropertyParameter` wouldn't work, but it might be a better overall solution.

@alexmg, what do you think? I like the second option, but if you have a third option...?

**Comment by Kostusev** [comment]
I don't know what will be better, but I have  a few thoughts in general:

- I think property injection should be always configured explicitly and should be used as less as possible.
- If configuration isn't contains PropertiesAutowired() - property injection shouldn't be used.
- This popular product like Autofac should first of all maintain backward compatibility with the already written code.

**Comment by Kostusev** [comment]
And I don't sure this bug happened because of the fix for #289. As I say before,  version 3.5.2  works correct and bug appeared after I updated Autofac to version 4.0.0

**Comment by tillig** [comment]
It's #289. Looking at the history of commits, [the change is in this commit](https://github.com/autofac/Autofac/commit/25a8cf5162097414cdc750d16a15df1c897dfd48#diff-9a6bd7dab1118a5d5bfad3dd6f6cb7b6) which was done specifically to address #289. That change didn't come out until 4.0.

We will do our best to be as backward-compatible as possible, but given this was a major release, it implies there may be some breaking behaviors. There's always some risk (as we're seeing here) that as we try to add features and make things better that the new stuff will necessitate changes that aren't backwards compatible. Again, we're not _trying_ to break anything, but there's no _guarantee_ things won't be slightly different after a major upgrade... semantic versioning and all.

In this case, what's happening is a little odd and needs fixing, so we'll see what we can do to fix it.

**Comment by Kostusev** [comment]
Yes, you are right.
But I don't like the idea to inject property without `builder.RegisterType<R>().PropertiesAutowired();` like here: 
```c#
public void PropertySpecifiedAsResolveParameterNoRegistrationPropertySpecified()
{
	var builder = new ContainerBuilder();
        builder.RegisterType<R>();
        var container = builder.Build();

        var instance = container.Resolve<R>(new NamedPropertyParameter("P1", 5));
        Assert.Equal(5, instance.P1);
}      
```
And I am concerned that this error can result to big problems in many projects, and not all will be easy to determine what the cause is Autofac.

**Comment by Kostusev** [comment]
And as for me, the fix will be very simple:
replace back 
`if (!_configuredProperties.Any() && !parameters.Any())` 
to 
`if (!_configuredProperties.Any())`
 in file src/Autofac/Core/Activators/Reflection/ReflectionActivator.cs

**Comment by alexmg** [comment]
The second option definitely sounds better. I don't like the idea of property injection finding its way into all the parameter types. It should be treated as the uncommon case and isolated as much as possible.

**Comment by tillig** [comment]
[Try out the 4.1.0 build on MyGet.](https://www.myget.org/feed/autofac/package/nuget/Autofac) I've updated it such that:

- If you don't specify `PropertiesAutowired` then parameters passed in at `Resolve` time only affect the constructor injection.
- If you specify `PropertiesAutowired` then parameters passed in at `Resolve` time affect both constructor and property injection.
- If you don't specify `PropertiesAutowired` but still want property injection, the `InjectProperties` and `InjectUnsetProperties` extensions now have overloads that allow you to pass parameters.

If this fixes the issue, I can push it as 4.1.0 to NuGet.

**Comment by Kostusev** [comment]
Thanks, works for me

**Comment by tillig** [comment]
Pushed 4.1.0 to NuGet.
