### ISSUE TITLE
ArgumentNullException: Value cannot be null. Parameter name: context

### ISSUE THREAD

**Issue by silkfire** [autofac/Autofac#797]
Suddenly I'm getting this error every time I'm trying to resolve a class. Has anyone else encountered this error recently? The answers at SO did not help me. This is a console application.

` var scheduledJob = Startup.Container.Resolve<IScheduledJob>();`

Strangely enough, this happens to any class I'm tryng to resolve. I've tried with versions 3.5.2 and 4.1.0 - same problem...

**Comment by tillig** [comment]
Unfortunately this isn't enough to allow us to help.

- Link to the SO question (where we'll probably answer instead of here)?
- Full stack trace?
- List of things you've tried to solve it?
- Repro so we can see it in action?

(Ideally those should all be in your SO question so you can just provide the link.)

**Comment by silkfire** [comment]
Sorry for my slightly lazy post.

Here's the question in more detail at SO: http://stackoverflow.com/questions/39549136/value-cannot-be-null-parameter-name-context-when-trying-to-resolve-a-class

**Comment by alexmg** [comment]
Answered on SO.
