### ISSUE TITLE
Versioning scheme has change?

### ISSUE THREAD

**Issue by SimonCropp** [autofac/Autofac#800]
Versioning scheme has change

in v3.x the assembly version was locked at minor. so the 3.5.2 dll had an assembly version of 3.5.0

in v4.x the assembly version was locked at patch. so in the 4.1.1 dll the assembly version 4.1.1

This means more friction due to a higher likelihood of having to manage binding redirects

Just wondering if this change was intentional?

**Comment by tillig** [comment]
This is more an artifact of how the dotnet CLI build tooling handles versioning with respect to build and package than anything else - the package version and the assembly version are unified.

So, half unintentional. Half somewhat intentional. The way the newer Microsoft libraries are being released, this is also how those work. So the landscape is changing somewhat away from that slower-version-change thing to actually matching the versions.

Given the majority case today is NuGet packages and NuGet manages the binding redirects for you, that's not usually a big issue. Yes, if you have a complex project where you're not using NuGet to manage things but instead are manually handling it (or if you have a project where you're doing something like lazy loading where the runtime needs the binding redirect but not the build time)... you're probably going to have more challenge.

(If that _is_ the case, I might recommend you, also, look at the dotnet CLI build tooling since even with .NET 4.x full framework targeting it manages the binding redirects for you.)

In any case, yeah, this is how it is now. Sorry if it causes friction. There's a high likelihood if you're having trouble with this with Autofac that as time goes on you'll see a lot more of it with other libraries that start adding .NET Core support as well.

**Comment by SimonCropp** [comment]
@tillig thanks for the clarification

**Comment by bording** [comment]
> This is more an artifact of how the dotnet CLI build tooling handles versioning with respect to build and package than anything else - the package version and the assembly version are unified.

@tillig I'm not sure I'm following this logic. If you have an `AssemblyVersion` attribute defined, the dotnet CLI tools still respect that version when they build your assembly.

Take a look at the RabbitMQ.Client [nuget package](https://www.nuget.org/packages/RabbitMQ.Client/4.1.0) for a great example of this. Even though the package is version 4.1.0, the AssemblyVersion is still 4.0.0.0.

**Comment by alexmg** [comment]
This was something I wanted to look at before releasing 4.0.0 but it slipped through the cracks. We could return to the previous versioning approach from 4.2.
