### ISSUE TITLE
Autofac can not register Controllers From customized probing path

### ISSUE THREAD

**Issue by stantoxt** [autofac/Autofac#825]
I add probing path to web.config
```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="sharedbin"/>
```
then at application start 
```
//var stringPath = HostingEnvironment.MapPath("~/sharedbin/Module.JustTest.dll");
                //var newAssembly1 = Assembly.LoadFrom(stringPath);
                var newAssembly = Assembly.Load("Module.JustTest");
                builder.RegisterControllers(newAssembly)
                   .InstancePerLifetimeScope();
```
the newAssembly is not null but I Can not get access the controller action in Module.JustTest.dll

so I try to preapplicationstart to build assembly

```
var pluginFolder = new DirectoryInfo(HostingEnvironment.MapPath("~/sharedbin"));
            var pluginAssemblies = pluginFolder.GetFiles("*.dll", SearchOption.AllDirectories);
            foreach (var pluginAssemblyFile in pluginAssemblies)
            {
                var asm = Assembly.LoadFrom(pluginAssemblyFile.FullName);
                BuildManager.AddReferencedAssembly(asm);
            }
```
after that I start the code previous the controller action worked fine.

I want to make it working at runtime .

Please Help me!
Thanks.

**Comment by tillig** [comment]
Here's what I'd recommend: 

First, do an experiment by taking Autofac out of the picture. Do all your assembly loading, then do a foreach over all of your controller types and write the type names out using `Debug.WriteLine`. Since Autofac has nothing to do with type loading or visibility you should be able to do this.

Verify you can see all of your controllers as expected. If not, that's the problem to solve... And, again, that's not an Autofac question. Ask this on StackOverflow and tag the question with `assembly` and `reflection` and put the code in showing the calls to `Debug.WriteLine`, _omitting any Autofac usage_ to keep the use case as simple as possible for people to answer. 

If it turns out you can see the controller types using `Debug.WriteLine` but Autofac isn't picking them up, please re-file the question on the Autofac.Mvc repo since the use case here has to do with MVC integration rather than core Autofac usage

**Comment by stantoxt** [comment]
@Tillig Thanks For your help.I would do what have you recommend.That's really helpful to me.

**Comment by stantoxt** [comment]
@Tillig Debug.WriteLine worked greate. By the way ,the post of you [](http://www.paraesthesia.com/archive/2013/01/21/putting-controllers-in-plugin-assemblies-for-asp-net-mvc.aspx/) Give me a lot of help, I just want to load dll at runtime not preappstart or appstart then use autofac to process the ioc.
