### ISSUE TITLE
Autofact not working in windows server 2012 R2

### ISSUE THREAD

**Issue by ahsanjaffri** [autofac/Autofac#851]
I have developed my website and working fine in local Dev & QA environments (not windows server) but once I deployed on UAT (Windows server 2012 R2) it's throwing null exceptions.
It's not injecting unset properties so service is null, although we have same IIS version in both environments which is **8.5.9600.16384**.
It seems compatibility issue ...

**Comment by tillig** [comment]
Autofac is a  managed.NET library, not native code. It doesn't include any PInvoke functions. As such, it doesn't behave differently across OS versions. If it's behaving differently for you across environments, it's going to be because of an app or environment configuration issue, not an Autofac issue.

Verify all of the assemblies in your app are deployed as you expect, make sure your web.config is set the way you expect, and ensure that IIS is configured correctly to allow the right version of ASP.NET to run. Basically, check your app and server setup.
