### ISSUE TITLE
Autofac 4+ With Xamarin.Forms in iOS failed to build

### ISSUE THREAD

**Issue by Jerome2606** [autofac/Autofac#864]
Versions:
package id="Autofac" version="4.6.1" targetFramework="xamarinios10"
in iOS project

TargetFramework=netstandard1.4
PackageTargetFallback=portable-win+net45+wp8+win81+wpa8
PackageReference Include="Autofac" Version="4.6.1"
PackageReference Include="HockeySDK.Xamarin" Version="4.1.5"
PackageReference Include="ReactiveProperty" Version="3.6.0"
PackageReference Include="Xamarin.Forms" Version="2.3.4.267"
PackageReference Include="Xamarin.Forms.Theme.Base" Version="1.0.0.43-pre1"
PackageReference Include="Xamarin.Forms.Theme.Dark" Version="1.0.0.43-pre1"
PackageReference Include="Xamarin.Forms.Theme.Light" Version="1.0.0.43-pre1"
In Core project

I'm using this template (work out of the box with PCL and Autofac 3.5.2):
https://github.com/NowBI/Xamarin-Forms-Mobile-Template

I update my core to netstandard and update all package.

Droid project is running fine and dependencies injections works fine.
But it's not working on iOS:

Build success but I get an exception on:
`Container = builder.Build();`
`System.ArgumentException: The type 'MobileTemplate.Core.Services.MenuItemService' is not assignable to service 'MobileTemplate.Core.Services.IMenuItemService'.`

The class is ok and verified as it is working on Android. This Ioc dependency is part of the Core project.

I'm looking on Internet for a while and have no idea what to do to fix that.
I can revert my changes and leave netstandard and autofac 4+ to get back to PCL and autofac 3.5.2 but it's a new project and want to be up to date.

Thanks for your help

**Comment by tillig** [comment]
This may be a better question to ask on StackOverflow with tags for `autofac` and `xamarin`. We're good with Autofac, but I'm not a Xamarin user and I don't have any iOS devices on which I could repro this.

I do know we've had another issue with Xamarin and iOS come up where the problem turned out to be the linker being too aggressive at removing what it believed to be unused types. [We put some docs together for that.](http://autofac.readthedocs.io/en/latest/advanced/cross-platform-apps.html) If that doesn't help... I'm not sure there's anything we can do for you here.

- If you do end up asking on StackOverflow, put a link to the question here.
- You might want to post the issue to the NowBI repo where you got the template. If it's not working with the latest Autofac, they may actually know why or have run into it before.
- If there's something specific we can do without an iOS device, let us know.

For now, since there's pretty much literally nothing we can do, I'm going to close the issue. Again, if there's something you find that we can do - or if you figure out the issue and it requires some additional fix on the Autofac side, let us know.

**Comment by Jerome2606** [comment]
I don't use Link as I'm still in debug so it shouldn't link to the linker.

I posted my question on stackoverflow as well on the NowBI template github:
https://stackoverflow.com/questions/45954054/autofac-4-with-xamarin-forms-in-ios-failed-to-build

I hope to find a better solution than revert my update to netstandard ... :)
