### ISSUE TITLE
Allow resolving in the 'OnRelease' eventhandler of an object

### ISSUE THREAD

**Issue by MenikX** [autofac/Autofac#865]
You should be able to resolve a type from the parent/root scope on release of an instance.

**My scenario**
I have an objectpool registered as a singleinstance. My object pool contains similar logic to [this](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-create-an-object-pool).
When I need an instance of the object, I resolve the objectpool and request an instance from the pool.
Now on release of this instance I want to give the instance back to the pool.

The object is my example is a connection to MS CRM which is very expensive to create. Hence the use of an ConnectionPool in order to reuse them.

Example of registration:
```
           builder.RegisterType<MyObjectPool>().SingleInstance();
            builder.Register((ctx, param) =>
            {
                return ctx.Resolve<MyObjectPool>().GetObject();
            }).As<IObject>().OnRelease((ctx, obj) =>
            {
                ctx.Resolve<MyObjectPool>().PutObject(obj);
            });
```
I currently have this implementation in place but I'm unsure if this is properly Implemented:

        public static IRegistrationBuilder<TLimit, TActivatorData, TRegistrationStyle> OnRelease<TLimit, TActivatorData, TRegistrationStyle>(
                this IRegistrationBuilder<TLimit, TActivatorData, TRegistrationStyle> registration,
                Action<IComponentContext, TLimit> releaseAction)
        {
            if (registration == null) throw new ArgumentNullException(nameof(registration));
            if (releaseAction == null) throw new ArgumentNullException(nameof(releaseAction));

            // Issue #677: We can't use the standard .OnActivating() handler
            // mechanism because it creates a strongly-typed "clone" of the
            // activating event args. Using a clone means a call to .ReplaceInstance()
            // on the args during activation gets lost during .OnRelease() even
            // if you keep a closure over the event args - because a later
            // .OnActivating() handler may call .ReplaceInstance() and we'll
            // have closed over the wrong thing.
            registration.ExternallyOwned();
            registration.RegistrationData.ActivatingHandlers.Add((s, e) =>
            {
                var lifeTimeScope = e.Context.Resolve<ILifetimeScope>() as LifetimeScope;
                var parentLifeTimeScope = lifeTimeScope.ParentLifetimeScope;
                var ra = new ReleaseAction<TLimit>(releaseAction, () => new ReleasedEventArgs<TLimit>(parentLifeTimeScope, (TLimit)e.Instance));
                lifeTimeScope.Disposer.AddInstanceForDisposal(ra);
            });
            return registration;
        }

        /// <summary>
        /// Adapts an action to the <see cref="IDisposable"/> interface.
        /// </summary>
        internal class ReleaseAction<TLimit> : Disposable
        {
            private readonly Action<IComponentContext, TLimit> _action;
            private readonly Func<IReleasedEventArgs<TLimit>> _factory;

            /// <summary>
            /// Initializes a new instance of the <see cref="ReleaseAction{TLimit}"/> class.
            /// </summary>
            /// <param name="action">
            /// The action to execute on disposal.
            /// </param>
            /// <param name="factory">
            /// A factory that retrieves the value on which the <paramref name="action" />
            /// should be executed.
            /// </param>
            public ReleaseAction(Action<IComponentContext, TLimit> action, Func<IReleasedEventArgs<TLimit>> factory)
            {
                if (action == null) throw new ArgumentNullException(nameof(action));
                if (factory == null) throw new ArgumentNullException(nameof(factory));

                _action = action;
                _factory = factory;
            }

            protected override void Dispose(bool disposing)
            {
                // Value retrieval for the disposal is deferred until
                // disposal runs to ensure any calls to, say, .ReplaceInstance()
                // during .OnActivating() will be accounted for.
                if (disposing)
                {
                    var eventArgs = this._factory();
                    _action(eventArgs.Context, eventArgs.Instance);
                }

                base.Dispose(disposing);
            }
        }

        public interface IReleasedEventArgs<T>
        {
            IComponentContext Context { get; }
            T Instance { get; }
        }

**Comment by tillig** [comment]
I don't think this is something we'd want to add to the framework because it could pretty easily cause trouble. Let me explain:

When other event handlers like `OnActivating` get run, the context you get is the lifetime scope actually doing the resolution, not the top-level container. `OnRelease` gets run _when that lifetime scope is disposing_, so you could pretty easily get into a situation where you resolve something from the lifetime scope being disposed that, itself, needs disposal after use... but then it's too late to actually get disposed.

[When you call `OnRelease` it does two things](https://github.com/autofac/Autofac/blob/v4.6.1/src/Autofac/RegistrationExtensions.cs#L1343):

- Tells the container your component is `ExternallyOwned` (so it doesn't get queued up for `IDisposable` calls)
- Adds a small action that _is_ `IDisposable` and runs your specified code when the owning `ILifetimeScope` is disposed.

[The thing that tracks object disposal within a lifetime scope is a `Disposer`.](https://github.com/autofac/Autofac/blob/v4.6.1/src/Autofac/Core/Disposer.cs) It handles the multithreaded locking around the list of things that need to be disposed and so on. Like, you can't add something to be disposed _while things are already in the process of disposing_. That'd be bad and end you up in weird memory/resource leak territory.

Say you have two things registered and we allowed you to resolve things during release:

```csharp
// Database context that is `IDisposable` and on disposal releases a connection.
builder.RegisterType<DbContext>().InstancePerLifetimeScope();
// Some object type that uses the database context during disposal to,
// say, track an instance count or something.
builder.RegisterType<DemoType>()
  .OnRelease((ctx, i) =>
    {
      var db = ctx.Resolve<DbContext>();
      db.DoSomething(i);
      i.DoSomethingElse();
    });
```

Now say you have something that uses your `DemoType` there. Maybe it's an ASP.NET MVC controller or something.

```csharp
public class ConsumerController
{
  public ConsumerController(DemoType dt) { ... }
}
```

...and you do something in your app that equates to creating a lifetime scope, resolving the consumer, and then disposing of it all. This happens behind the scenes in ASP.NET MVC, but it equates to this:

```csharp
using(var scope = container.BeginLifetimeScope())
{
  var ctlr = scope.Resolve<ConsumerController>();
  ctlr.DoStuff();
}
```

The order of operations is:

1. Create lifetime scope and start tracking disposals.
2. Start resolving `ConsumerController`.
  a. Resolve `DemoType`.
  b. Add `OnRelease` handler to the lifetime scope.
  c. Return `DemoType` instance to be used by `ConsumerController`.
3. Finish resolving `ConsumerController`.
4. Do work with `ConsumerController` and reach the end of the `using` statement.
5. Dispose of the lifetime scope.
  a. Locate the `Disposer` disposal tracker in the scope.
  b. **Lock the list of things that need disposing.**
  c. Start the `OnRelease` action for `DemoType`.
  d. Start resolving `DbContext` from the lifetime scope currently being disposed.
  e. Note `DbContext` is `IDisposable` and try adding it to the `Disposer` for the scope currently being disposed. 💥 **DEADLOCK**

It would actually be so easy to get into a deadlock situation here it would likely generate more problems than it solves. Folks trying to resolve things would have to follow a whole bunch of weird rules that you'd only run into at runtime. Like...

- If the object is disposable it must be `SingleInstance`.
- If your object is `SingleInstance` and has an `OnRelease` you can't resolve anything disposable from the context.
- Anything you do resolve that isn't `SingleInstance` needs to not be disposable and not have any `OnRelease` actions of its own. Further, it can't _depend_ on anything that is disposable in that scope and/or has an `OnRelease` action of its own.

**Instead, consider working around the issue.**

There are a few ways you can do that.

**OPTION: Register an instance of the object pool instead of passing it through DI.** Sometimes the easiest thing to do when you get into weird DI chicken/egg situations is to stop trying to over-DI things. Happens a lot in app startup scenarios, too.

```csharp
this.Pool = new MyObjectPool(param1, param2);
builder.RegisterInstance(this.Pool).As<MyObjectPool>();
builder.Register(ctx => this.Pool.GetObject())
  .As<IObject>()
  .OnRelease(i => this.Pool.PutObject(i));
```

Note the closure over the pool instance rather than resolving it.

**OPTION: Use service location rather than event parameters.** Seems a little more complicated but doable.

```csharp
this.Container = null;
builder.RegisterType<MyObjectPool>().SingleInstance();
builder.Register(ctx => this.Container.Resolve<MyObjectPool>().GetObject())
  .As<IObject>()
  .OnRelease(i => this.Container.Resolve<MyObjectPool>().PutObject(i));
this.Container= builder.Build();
```

Again, closures to the rescue. You could use `CommonServiceLocator` or one of the other service locators, too, if closing over the container isn't to your liking.

**Point being, there are ways to work around the issue** that don't require any additional complexity and won't open up potential pitfalls for other Autofac users. I would recommend looking for a workaround, and I hope the ideas here help.
