### ISSUE TITLE
castle aop implement is a little bit old fasion,try aspectcore,this implement support async aop

### ISSUE THREAD

**Issue by hiwjcn** [autofac/Autofac#883]
castle aop implement is a little bit old fasion,try aspectcore,this implement support async aop
change castle to aspectcore in autofac.extra.dynamicproxy

thanks a lot

**Comment by tillig** [comment]
You can intercept and handle async methods just fine using Castle. It may feel old fashioned or tedious to use the Task mechanism rather than the syntactic async/await sugar, changing the underlying mechanism here would be really, really breaking to all of our consumers. The benefits don't outweigh the drawbacks. Sorry.
