### ISSUE TITLE
How do I host multiple separate services in ASP.NET Core and enable isolation of the registrations associated with each service while using a single container?

### ISSUE THREAD

**Issue by fh-sholodak** [autofac/Autofac#884]
I'm trying to get around a limitation which has been discussed in #811 where ASP.NET Core's `WebHostBuilder` insists on being the composition root.  In my application, I have a configured container with some root-level services.  I would like to use `BeginLifetimeScope` for ASP.NET Core to add registrations, but their API doesn't allow it.  

My workaround is to make a `Startup` class that extends from `StartupBase<ContainerBuilder>` and then use `cb.RegisterSource(rootContainersComponentRegistry)` in the `ConfigureContainer` method.  I'm basically trying to get ASP.NET Core to check its own component registry and also check the root-level container's (separate, but linked).  I'd like to have the same semantics around lifetime management, `IEnumerable` resolution, etc. as the `BeginLifetimeScope` approach.

The closest I've come to achieving this is to copy and paste the code from `ExternalRegistrySource` into my project along with the `IsAdapting` extension method from ComponentRegistrationExtensions.cs.  

I'm wondering if you'd consider one of these alternatives:

- making these non-internal
- adding a ContainerBuilder extension method to link to another container
- create an overload on the `AutofacServiceProviderFactory` constructor that accepts one or more parent-level containers to link using the `ExternalRegistrySource` mechanism internally

**Comment by tillig** [comment]
If we make this more general, it sounds like this is less about ASP.NET Core and more about the desire to somehow have a single meta-container that can resolve things across other containers. Does that sound like it describes the issue?

I'm trying to understand the use case for not just using a single container and following the path of least resistance when it comes to using Autofac with .NET Core apps.

**Comment by fh-sholodak** [comment]
To generalize a bit, I'm trying to be able to host multiple startable/stoppable things in a single process.  There are some things I want to expose at the root level (accessible from any startable/stoppable thing) and then each startable/stoppable thing has an isolated set of service registrations.

`BeginLifetimeScope` solves this perfectly for every use case except ASP.NET Core.  The only clarification I would make to generalizing the question @tillig is that their framework only gives me the ability to supply an `Action<ContainerBuilder>`.  I can't provide an instance of a `ContainerBuilder`, I can't construct one, and I can't `Build()` one due to API restrictions imposed by that particular framework.  There may be other (non-ASP.NET Core) situations with these constraints but I haven't found any.  I've tried a lot of ugly workarounds to no avail (see below). 

The only thing I can do in the context of an `Action<ContainerBuilder>` that achieves the resolution scenario that I'm looking for is to link the root-level container via an `IRegistrationSource`.  I'm not sure whether `ExternalRegistrySource` handles every scenario in the same way as a child scope does, but it passes all of ServiceWithType test scenarios I put it through.

This is inspired by:
- https://stackoverflow.com/a/33213708
- https://github.com/autofac/Autofac/blob/develop/src/Autofac/Core/Registration/ExternalRegistrySource.cs

Struck out trying to get ASP.NET to accept an externally configured container:
- https://github.com/scottt732/AspNetCoreExternalDiRepro
- https://github.com/autofac/Autofac/issues/811
- https://www.strathweb.com/2017/04/running-multiple-independent-asp-net-core-pipelines-side-by-side-in-the-same-application/
- https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L101
- https://github.com/aspnet/Hosting/issues/1129#issuecomment-314026120
- http://docs.autofac.org/en/latest/advanced/registration-sources.html
- davidfowl: We didnt' design the host to accept another service provider

**Comment by tillig** [comment]
My initial thought is that it sounds like you're really going against the grain with what you're trying to do. If you weren't using Autofac and were just using the default .NET Core service provider, you wouldn't be able to even begin down this road.

The reason I say that is that exposing things in our public API that will increase our overall support footprint just to allow something that isn't generally done... may not be in the best interests of the project. For that reason, I might recommend looking at other ways to accomplish your goals.

That said, if you look at the [ASP.NET Core quick start without `ConfigureContainer`](http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#quick-start-without-configurecontainer) you can see that you could technically give the `AutofacServiceProvider` a specific lifetime scope from which to spawn child/request scopes, so you could build up your container, do a `BeginLifetimeScope` to register the additional ASP.NET Core stuff, and return an `AutofacServiceProvider` from that child scope rather than the root container. Combine that with a new [override we added that allows you to specify a particular lifetime scope tag for singletons](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L85) and you could combine the two things to do some pretty powerful stuff.

(Admittedly, that latter extension isn't documented but is also really only there for some pretty crazy advanced stuff. [Check out the unit tests for an example.](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/test/Autofac.Extensions.DependencyInjection.Test/AutofacRegistrationTests.cs#L81))

Would that get you what you need?

**Comment by tillig** [comment]
I updated the title of the issue to reflect the desired goal rather than a specified answer. That is, rather than "I want to put a bigger antenna on my mobile phone" specifying "I'd like my mobile phone to have better reception." I hope I characterized things accurately; feel free to edit if not.

Note it's been a couple of weeks since we've heard back here. I know it's holiday times so I'll leave it open another couple of weeks. If we don't hear back we can close it and, if needed, reopen (or open a new/different issue).

**Comment by fh-sholodak** [comment]
Apologies for the long delay.  Feel free to close this.  I appreciate it if you don't mind potentially reopening down the road (there's a lot of detail here).

My issue with your ASP.NET Core Quick Start approach was that I was trying to have Autofac create my Startup class so I could give ASP.NET Core an ILoggerFactory and IConfigurationRoot created outside of ASP.NET Core.  This put me in a chicken/egg situation (can't create the container inside of the thing that needs to have its dependencies injected).  I've managed to roll my own IRegistrationSource that unblocks me w/all tests passing for now, though I'm still not happy with the solution.  I had to switch gears to other parts of the project.

I think there are some big changes on the horizon in ASP.NET Core 2.1 that relate to DI.  I'll try to take a look at what's coming and see if I've got any better options.  I'll let you know if there's anything you should be aware of.
