### ISSUE TITLE
.net core not found the dll

### ISSUE THREAD

**Issue by ICE2017** [autofac/Autofac#888]
i add autofac service to the project,i copy the type dll to bin path,when i start the project i catch exception liek this:

`System.InvalidOperationException:“The type 'ClassLibrary1.Class1,ClassLibrary1' could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".”`

the autofac.json:
```
{
    "components": [
      {
        "type": "ClassLibrary1.Class1,ClassLibrary1",
        "services": [
          {
            "type": "ParamsInject.IParams,ParamsInject"
          }
        ]
      }
    ]
  }
```

**Comment by tillig** [comment]
My first thought is that assembly loading in .NET Core isn't the same as in full .NET. There are several StackOverflow questions out there about this - it's not an Autofac thing, you just see it when you introduce modularity and IoC into a project.

Try doing `Type.GetType("ClassLibrary1.Class1,ClassLibrary1")` in your project and see if it's found. Guessing it won't be.

I'd recommend searching StackOverflow. If you still can't figure it out, asking there is your best bet since you'll have not only the Autofac maintainers following but also a much larger audience of folks to help.

**Comment by MarcoPochettino** [comment]
After two days turning mad about this, i've tried StackOverflow as suggested...
Here it is the workaround that is working for me:

            //https://stackoverflow.com/questions/43918837/net-core-1-1-type-gettype-from-external-assembly-returns-null
            AssemblyLoadContext.Default.Resolving += (AssemblyLoadContext context, System.Reflection.AssemblyName assembly) =>
            {
                return context.LoadFromAssemblyPath(Path.Combine(path, $"{assembly.Name}.dll"));
            };
