### ISSUE TITLE
Only set major version in AssemblyVersion

### ISSUE THREAD

**Issue by skovsende** [autofac/Autofac#893]
Right now you seem to set your AssemblyVersion to the same as package version, which leads to all kinds of problems for packages depending on Autofac, which can only be solved by using BindingRedirects. If instead you always kept the AssemblyVersion to the major version(like all .Net framework dll's does) we could avoid that behavior. 

There is a lengthy discussion about the problem [here](https://github.com/castleproject/Core/issues/288)

While doing this change for Castle.Core and Moq, the experience have been that it may make sense with waiting on doing this until the next major release, and as a temporary bump to 4.7.0.0 and keep that assembly version for the rest of the 4.x lifetime.

**Comment by tillig** [comment]
Since the advent of Autofac 4 and .NET Core we've started following the patterns of the Microsoft .NET Core libraries and other .NET Core libraries, which is, that the semantic version of the package _matches_ the version of the library inside. NuGet takes care of binding redirect creation and maintenance. Visual Studio brings up build warnings you can simply click on to fix redirect issues it detects. And for some project types, you can even put `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` right in the .csproj file.

[There's a lot of doc on this.](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection)

Point being, the path forward for Autofac is to continue following the best practices established by the larger community and Microsoft in this space, which means we'll not be fixing the assembly version as we did in the 3.x releases.

**Comment by skovsende** [comment]
That saddens me a little. In the particular case I have, writing a Cake Addin, I don't have an app.config where I can put binding redirects, so that solution won't work. The link you link to just documents how to do that, but I have tried to see if I can find any official docs that suggest what you have started doing is the correct way, but I'm failing. If you could somehow point me in the correct direction and help me find the docs I'd be very grateful.

**Comment by tillig** [comment]
If you're looking for "official docs on when to change assembly version vs file certain vs package version" there aren't any. That's up to the project, and based on a sampling of packages from various products during the outset of .NET Core along with conversations with Microsoft and other projects, we landed where we landed. It's different than .NET full framework and that can be a shock to the system, that's for sure.

If you're looking for docs on how to deal with binding redirects in Cake addins, that's not us. I don't use Cake. I'd recommend [asking the Cake people](https://github.com/cake-build/cake/issues).

**Comment by skovsende** [comment]
It just saddens me a little bit that you have chosen a strategy that makes binding redirects necessary at all. There are situations where a binding redirects aren't as easy, my cake addin is an example, another is Visual Studio extensions(But there is a manual workaround there). I had just hoped that I could convince you that the way used by the framework is not really appropriate, in my opinion, for 3rd party libraries and frameworks.
