### ISSUE TITLE
Issue with multiple parameters of the same type 

### ISSUE THREAD

**Issue by KWodarczyk** [autofac/Autofac#896]
If we have a class that takes in two parameters of the same type in the constructor and we resolve it with TypedParameter the object that are actually passed to the constructor are in different order than at resolve:

//resolving
```
var  someClass = context.Resolve<ISomeClass>(
                        new TypedParameter(typeof(IOtherClass), otherClassA),
                        new TypedParameter(typeof(IOtherClass), otherClassB));
```
//object creation

```
 public SomeClass(IOtherClass otherClassA, IOtherClass otherClassB)
        {
            //here otherClassA  is ok but otherClassB is a reference of otherClassA instead of otherClassB
        }
```

**Comment by tillig** [comment]
I'm going to go with "functions as designed" here because if you _also_ had an `IOtherClass` registered in the container then it'd throw this whole scenario for a loop - which two of the three instances would you get? It also overlaps with the notion that [auto-generated function factories like `Func<X, Y, B>` relationships cannot have duplicate types in the input parameter list](http://autofac.readthedocs.io/en/latest/resolve/relationships.html#parameterized-instantiation-func-x-y-b). I'd recommend redesigning your class to resolve `IEnumerable<IOtherClass>`; take in two _different_ parameter types; or manually order them by registering `ISomeClass` as a lambda.

**Comment by KWodarczyk** [comment]
I didn't get first part of you answer, can you provide example of what you mean with three parameters ?
I would assume it works the same as if I had created class with multiple parameters of the same type manually where I am expected to pass them in correct order.
I'm explicit with regards order of parameters in the above code. Regarding auto generated functions I am not using this kind of function here, am I ?

**Comment by tillig** [comment]
```csharp
var builder = new ContainerBuilder();
builder.RegisterType<FirstOther>().As<IOtherClass>();
builder.RegisterType<SecondOther>().As<IOtherClass>();
builder.RegisterType<SomeClass>().As<ISomeClass>();
var container = builder.Build();

// ...later...
var someClass = context.Resolve<ISomeClass>(
  new TypedParameter(typeof(IOtherClass), otherClassA),
  new TypedParameter(typeof(IOtherClass), otherClassB));
```

In this scenario, there are four possible things that could show up in the `SomeClass` constructor, which only uses two of them. Not only do you start hitting precedence problems (which two should be used?) but _also_ ordering problems.

The point is, having two typed parameters and assuming order here isn't going to work - it's a design problem. It assumes you _know_ what's backing the `ISomeClass` interface, which breaks the Liskov substitution principle and couples the calling/resolving code _very tightly_ to the backing class. There's no reason to use an IoC container if this is the level of control you require - the call to `Resolve` could just as easily just call the constructor of `SomeClass` directly.

You aren't using the auto-generated functions, no, but I linked to that to illustrate the point that Autofac is consistent in its behavior - types are largely identifiers for parameters and if you need more than one of the same thing _injected_ then the way to go is `IEnumerable<T>` and order them as needed in your class. You likely won't get exactly the control you're looking for in a consistent way from any IoC framework, and if you do it's likely by accident because wiring by _type_ and not by _order_ like this is very common.

Another alternative would be to use `NamedParameter` since that is just as tight a coupling as order; or `ResolvedParameter` with a more complex "location" lambda in there to only allow paramters to inject into the right position ([see docs here](http://autofac.readthedocs.io/en/latest/resolve/parameters.html#available-parameter-types)).

As I mentioned earlier, though, I would recommend redesigning the class to remove the ordering requirement.

Note: You may be hitting [this situation](http://autofac.readthedocs.io/en/latest/faq/select-by-context.html) where you have two implementations of an interface that it _seems_ like they do the same thing but they very much don't. [The FAQ here](http://autofac.readthedocs.io/en/latest/faq/select-by-context.html) talks about that with examples.
