### ISSUE TITLE
How do I deal with error about autofac without System.Core, Version=2.0.5.0l,but have install KB2468871

### ISSUE THREAD

**Issue by junwangwj** [autofac/Autofac#899]
How do I deal with error about autofac without System.Core, Version=2.0.5.0l,but have install KB2468871

I use autofac RegisterInstance,but have error, .NetFramework 4.0 and have install (KB2468871).
but still have error;
I insatll the (KB2468871) in server 2008 r2 and without network
I need a help
Thanks very match !

code：
var builder = new ContainerBuilder();
builder.RegisterModule(new MappingModule() { IsMultiThread = MappingRule.IsMultiThread });
builder.RegisterInstance(MappingContext);

Stack Error：
at Autofac.Builder.RegistrationData..ctor(Service defaultService)
at Autofac.Builder.RegistrationBuilder`3..ctor(Service defaultService, TActivatorData activatorData, TRegistrationStyle style)
at Autofac.RegistrationExtensions.RegisterInstance[T](ContainerBuilder builder, T instance)

error：
Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)

**Comment by junwangwj** [comment]
use .netFramework 4.0  and   have intalled KB2468871

**Comment by junwangwj** [comment]
the server system is  winServer 2008 r2  and   the server without network

**Comment by tillig** [comment]
Any time you ever see a failure to load System.Core 2.0.5.0 it is [always a problem with a missing patch somewhere.](http://autofac.readthedocs.io/en/latest/faq/pcl.html) I have a [blog article with some additional information and pointers.](http://www.paraesthesia.com/archive/2013/03/29/portable-class-library-answers.aspx/) Here's a [Microsoft reference on PCL.](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library)

Unfortunately, though, given the problem is _always based on the machine_ and isn't something anyone here can reproduce or troubleshoot without literally having the actual machine on which the issue is being seen... there's nothing we can do.

I would recommend:

- Make sure you have _all the latest Windows Update patches_. Not just the one you mentioned, but _all of them_. It is very possible that one patch somewhere accidentally overwrote the fix that some other patch made.
- Try installing a newer .NET framework. You can still target .NET 4.0 with your project but have, like, .NET 4.5.2 or higher installed on the machine. They're runtime compatible.
- Try it on a different machine. If you're seeing the problem on a specific machine (or a set of machines that is configured identically) try on a different machine. It could be that the machine seeing the problem has some bad setting somewhere not allowing the binding redirection required by portable class libraries.

If you still can't make it work... unfortunately, again, this isn't something we can troubleshoot or help with. On machines that have all the appropriate patches, this can't be reproduced. I haven't seen this error _for years_.
