### ISSUE TITLE
Unregistered services are resolved

### ISSUE THREAD

**Issue by sam-wheat** [autofac/Autofac#900]
I long ago boycotted StackOverflow however I posted my question there because of the directions on the new question page.  As expected I got the usual flak and downvotes so I just deleted the question and came back here.  I appreciate your understanding.

My question is: What configuration or circumstance would allow IsRegistered to return true for a service that is in fact not registered?
The following calls to IsRegistered return true however no functions with matching signatures have been registered in my app.

	// following two signatures are nonsensical - no chance whatsoever I would have registered anything like this
	bool isregistered2 = Scope.IsRegistered<Func<string, string, string, int, char, IDataProviderService>>(); // true - should be false, zero chance I registered this
	bool isregistered3 = Scope.IsRegistered<Func<int, string, string, string, int, char, IDataProviderService>>(); // true - should be false, zero chance I registered this

**Comment by tillig** [comment]
Despite the challenges you may see with SO it helps _us_ because there are only two project owners here and we really need all the help we can get from the community with support. An hour spent here answering questions is an hour I don't have to fix bugs or add features.

`Func<T>` is one of the [implicit relationship types](http://autofac.readthedocs.io/en/latest/resolve/relationships.html#supported-relationship-types) so will always be seen as registered.
