### ISSUE TITLE
No accessible constructors were found ...

### ISSUE THREAD

**Issue by 1iveowl** [autofac/Autofac#915]
I have a Xamarin Forms project using .NET Standard 2.0. The project is for Android, iOS and UWP.

When I run the project with iOS or UWP everything works as expected.

When running it in Android i get a "*No accessible constructors were found ...*" exception when trying to resolve `MainViewModel`.

Registration: 
```csharp
builder.RegisterType<MainViewModel>().AsSelf();
```

Resolve (ViewModelLocator):
```csharp
public MainViewModel MainPage
{
    get
    {
        using (var scope = _container.BeginLifetimeScope())
        {
            return _container.Resolve<MainViewModel>();
        }
    }
}
```

MainViewModel constructor:
```csharp
public MainViewModel(
    ISecureDatabaseService secureDb, 
    IReceiptQueuedSenderHandler receiptQueuedSenderHandler)
```
Both `ISecureDatabaseService` and `IReceiptQueuedSenderHandler` is registered with Autofac prior to registering `MainViewModel`.

Any idea what is going on here and why things work smoothly with iOS and UWP and breaks on Android? 

I'm using Autofac 4.8.

**Comment by tillig** [comment]
Questions like this are much better suited to StackOverflow (as noted in the issue template) because you have a larger community of people that can help. Especially in cases like this where neither of the two project owners here are Xamarin experts.

[We do have some docs based on experiences reported by other users](http://autofac.readthedocs.io/en/latest/advanced/cross-platform-apps.html) that can hopefully help. If not, please try StackOverflow.

**Comment by 1iveowl** [comment]
Apologies. I sort of assumed it was a bug, since it worked on the two other platforms. I never considered the Linker to be the culpit. I don't know much about linking so will need to read up on that piece then. 

Anyhow, I've moved it to Stackoverflow. [Autofac, Android and Xamarin Forms == No accessible constructors were found](https://stackoverflow.com/q/50190698/4140832)
