### ISSUE TITLE
Is there have something like StructureMap's WhatDoIHave()

### ISSUE THREAD

**Issue by seanmars** [autofac/Autofac#928]
I want to check all of my register, but i cat not find easy way to do that.
And i find the StructureMap's WhatDoIHave(), is Autofac has some feature like that?

**Comment by tillig** [comment]
As noted in the issue template, it's best if you ask usage questions on StackOverflow to get a more timely response.

You can try iterating through the set of registrations, but that's not going to be complete because of the number of dynamically-supplied things that are available (`IEnumerable<T>` for example). We can't offer a 100% complete list for the same reason we can't provide automated container analysis.

See #853 for details.
