### ISSUE TITLE
Keyed Services and Delegate Factory

### ISSUE THREAD

**Issue by SuricateCan** [autofac/Autofac#935]
Hi, first of all, great job on the library. It's the best one out there.
Second, I was messing around with my application and I've stumbled across a situation:

I have, in my application, a dependency on a ```Func<MyEnum, IService>```, where I pass the enum and the container give back the implementation.
When registering the component, I did like so:

```C#
builder.Register<IService>((c, p) => {
    var type = p.TypedAs<MyEnum>();
    switch (type)
    {
        case MyEnum.First:
            return c.Resolve<MyFirstService>();
        case MyEnum.Second:
            return c.Resolve<MySecondService>();
        default:
            throw new ArgumentException("Type not recognized");
    }
})
.As<IService>();
```
And it works as intended. The factory function gives me back the correct service.

The thing I was questioning myself is: why can't I register these services as Keyed and have the same results?
When I tried like this:
```C#
builder.RegisterType<MyFirstService>()
    .Keyed<IService>(MyEnum.First);
builder.RegisterType<MySecondService>()
    .Keyed<IService>(MyEnum.Second);
```
the delegate factory stopped working, and returned the second service, even if I requested the first.

However, on the fiddle I set up, I get an exception for not registering the factory delegate at all.

https://dotnetfiddle.net/1Zs15s

What bothered me was that the second approach is much cleaner and easy to understand, so why did the delegate factory did not work?
Is there a way to make it work by registering as Keyed?

Thanks in advance

PS.: I opened an issue instead of a question on stack overflow, because I believe the second approach should work, and this is a better place to discuss it.

**Comment by alexmg** [comment]
Hi @SuricateCan. I'm glad you're enjoying Autofac. It's nice to get the feedback. 😄 

The second example doesn't work because the parameters to the `Func<T,TResult>` are assumed to be parameters of the `TResult` service implementation and are mapped based on their `Type`. There is no way based on the signature alone for the generator to know that you want to take one of the parameters (and there can of course be more than one) and use that as the key to create a `KeyedService` and then perform a key based resolve operation.

I think what you have with the delegate registration is perfectly reasonable. Alternative approaches are to resolve through the [IIndex](https://autofaccn.readthedocs.io/en/latest/advanced/keyed-services.html?highlight=iindex#resolving-with-an-index) relationship type, [KeyFilter attributes](https://autofaccn.readthedocs.io/en/latest/advanced/keyed-services.html?highlight=iindex#resolving-with-attributes), or by including [metadata](https://autofaccn.readthedocs.io/en/latest/advanced/metadata.html) (possibly combined with `Lazy<T>`). Note those will introduce a framework dependency into your implementation code but they're additional tools in the tool belt should you need them.

**Comment by SuricateCan** [comment]
Hi @alexmg , thanks for the fast response.
I understand now why it does not work. It was not clear to me that the parameters to ```Func<T,TResult>``` were expected to be for the service implementation constructor.

Anyway, I still think we can improve the registration/consumption of such factories.

I'll give it some more tought, and if come up with anything, I'll post here for discussion.

Thanks

**Comment by SuricateCan** [comment]
@alexmg I know my idea is super simplistic, and with an easy workaround (why go to so much trouble?), but I was thinking something like this fiddle:

https://dotnetfiddle.net/TAdgqO

Any thoughts?

**Comment by AlexBrownShi** [comment]
@SuricateCan Wow, nice solution.  I will give this a try - I think it should be incorporated into the library and documentation if it works well.

**Comment by praschl** [comment]
Thread may be a bit old, but how about this extension:
```
public static class BuilderExtensions
{
    public static void RegisterFunc<TKey, TService>(this ContainerBuilder builder)
    {
        builder.Register<Func<TKey, TService>>(c =>
            {
                var cc = c.Resolve<IComponentContext>();
                return s => cc.ResolveKeyed<TService>(s);
            });
    }
}
```
which would be used like this:
```
// register all the recipes
builder.RegisterType<ChickenRecipe>().As<IRecipe>().Keyed<IRecipe>(DayOfWeek.Monday);
builder.RegisterType<SpinachRecipe>().As<IRecipe>().Keyed<IRecipe>(DayOfWeek.Tuesday);
// register the factory
builder.RegisterFunc<DayOfWeek, IRecipe>();
```
works the same for me.
