### ISSUE TITLE
contention using autofac in multi-threaded high throughput applications

### ISSUE THREAD

**Issue by oshvartz** [autofac/Autofac#941]
Hi
We have asp.net application with high load ~5000 rps. we use orchard cms that uses autofac under the hood. recently our web application is utilizing the the machine to ~100% CPU and after reviewing the dump we discover that most of the threads had the same call stack (~95%):
System.Threading.Monitor.Enter(System.Object)
Autofac.Core.Registration.ComponentRegistry.RegistrationsFor(Autofac.Core.Service)
System.Threading.Monitor.Enter(System.Object)
Autofac.Core.Registration.ComponentRegistry.TryGetRegistration(Autofac.Core.Service, Autofac.Core.IComponentRegistration ByRef)

This all are waiting for the monitor.Enter - (i found the code has simple lock)
does it means autofac is not build to be used in high throughput application ? isn't it a common use case ?
Thanks
Offir

**Comment by tillig** [comment]
Duplicate #906. See that issue for more details.

Short version: We need to lock when resolving things to ensure thread safety on resolve. If you can find additional ways to improve locking and throughput without removing the existing level of thread safety, we are absolutely open to pull requests.

Autofac is being successfully run in many high-throughput apps, but sometimes app code may need to be tweaked to handle things. I'd recommend gathering some hot-path data from your profiler to see what's causing all the resolutions to happen and see if you can optimize. If you are resolving tons and tons and tons of things, your overall app performance may improve by reducing resolutions - which will also reduce memory allocations, garbage collections, and a lot of other things, making your overall app perform better.

**Comment by oshvartz** [comment]
Hi @tillig 
I know that is asp.net application common DI life cycle is "Scoped" - lifetime services are created once per request.
so if i have web API with DI using autofac - my request per second is throttled because only one resolve can happen in a given time using the same container
what am i missing here ?

**Comment by tillig** [comment]
If a component isn't getting resolved from the root container then the root container isn't locked. What you're missing is that if you have a scope - either the root container or a child scope - that resolving from _that scope_ should be thread safe. Which is to say, you can only do one resolve from _that scope_ at a time, and generally the locking only happens for shared components (e.g., InstancePerLifetimeScope). You are not as limited as you think.

But, again, I have to stress this: You're hitting the lock, but what is the hot path of code _in your app or in ASP.NET Core_ that is causing the hot path to be hit? Look at that path. Can that path be optimized? Are you resolving a lot of `IEnumerable<T>` but then only using one of them? Without more detailed data, there's nothing we can do... and even then, things we change need to maintain the thread safety, so just "removing the lock" isn't an option. We need more concrete suggestions that both improve the perf but also maintain the thread safety.

**Comment by eugbaranov** [comment]
@tillig but when you are resolving from child scope will it not still lock parent scope/container because `CopyOnWriteRegistry` will go to parent's `ComponentRegistry.Resolve` (and thus locking) _unless_ something was changed to trigger `CreateScopeRestrictedRegistry` logic?

@oshvartz I actually did some analysis with concurrency visualizer yesterday trying different ways of synchronization and came up to a conclusion that without considering massive overhauls to how dependencies are built (e.g. making entire component registry immutable, somehow) the current implementation is _very_ fast comparing to other alternatives I could came us with.
Given that you share your container between thread the longest locking occurs at the very few first call when dependency tree being build first. After that behind the lock is very fast dictionary lookup.

That's said it would be great to have some concrete sample rather my simplistic test.
