### ISSUE TITLE
BeginLifetimeScope(tag) working incorrectly

### ISSUE THREAD

**Issue by uranium59** [autofac/Autofac#950]
public static void Main()
        {
            var builder = new ContainerBuilder();
            builder.RegisterType<Settings1>().InstancePerMatchingLifetimeScope("1").As<ISettings>();
            builder.RegisterType<Settings2>().InstancePerMatchingLifetimeScope("2").As<ISettings>();
            var container = builder.Build();
            using (var lifetimeScope = container.BeginLifetimeScope("1"))
            {
                lifetimeScope.Resolve<ISettings>().Run();
            }
            using (var lifetimeScope = container.BeginLifetimeScope("2"))
            {
                container.Resolve<ISettings>().Run();
            }
        }
this code throws DependencyResolutionException at   using (var lifetimeScope = container.BeginLifetimeScope("1")).

'Unable to resolve the type 'testing.Settings2' because the lifetime scope it belongs in can't be located. The following services are exposed by this registration: - testing.ISettings
I think resolve doesn`t check resolved type has valid tag when multiple interface is registered.

**Comment by alexmg** [comment]
The example is written as though these are two distinct registrations but that is not what is actually happening under the hood.

The first and second services are both considered `TypedService` registrations because they are resolved by providing only the `Type` of the required service (e.g. `Resolve<ISettings>()`). Because a single `Resolve` call cannot return two instances the second registration replaces the first. To prevent the second registration from overriding the first it would be necessary to register it with `PreserveExistingDefaults()` or a conditional registration like `IfNotRegistered(typeof(ISettings))`. Regardless, when resolving `ISettings` either the first or second registration needs to win in order to return the single instance.

If you swap the order of the `Resolve` calls in your example above you will see that the call inside the lifetime scope tagged with `"2"` actually works. This is because the second registration has replaced the first and become the default.

If no lifetime scope tag was applied to either registration it would be possible to resolve both services using `Resolve<IEnumerable<ISettings>>()`. In your example each service is given a distinct lifetime scope tag so there would never be a single lifetime scope from which both services could be resolved so you couldn't resolve them using `IEnumerable<ISettings>`. The case of registering multiple implementation types (with one of them being the default) while still allowing all to be resolved using `IEnumerable<T>` is a more common requirement than having multiple implementation types each registered with a unique lifetime scope tag. So while this looks reasonable on the surface supporting it would actually break the more common `IEnumerable<T>` scenario.

You can register the services as `Keyed` or `Named` to create unique registrations that can be resolved without the lifetime scope ambiguity.

```c#
var builder = new ContainerBuilder();
builder.RegisterType<Settings1>().Named<ISettings>("1").InstancePerLifetimeScope();
builder.RegisterType<Settings2>().Named<ISettings>("2").InstancePerLifetimeScope();
var container = builder.Build();

using (var lifetimeScope = container.BeginLifetimeScope())
{
	lifetimeScope.ResolveNamed<ISettings>("1").Run();
}
using (var lifetimeScope = container.BeginLifetimeScope())
{
	lifetimeScope.ResolveNamed<ISettings>("2").Run();
}
```

You could also register the specific implementation type at the time of creating the new lifetime scope as well.

```c#
var builder = new ContainerBuilder();
var container = builder.Build();

using (var lifetimeScope = container.BeginLifetimeScope(
	b => b.RegisterType<Settings1>().As<ISettings>().InstancePerLifetimeScope()))
{
	lifetimeScope.Resolve<ISettings>().Run();
}
using (var lifetimeScope = container.BeginLifetimeScope(
	b => b.RegisterType<Settings2>().As<ISettings>().InstancePerLifetimeScope()))
{
	lifetimeScope.Resolve<ISettings>().Run();
}
```

In both examples a lifetime scope tag can still be provided for other services if necessary. Hopefully that clears things up and gives you a few alternatives for your scenario.
