### ISSUE TITLE
IfNotRegistered() does not behave as expected with open generic types

### ISSUE THREAD

**Issue by prochnowc** [autofac/Autofac#958]
Using open generic services a call to `IfNotRegistered()` does not behave like expected.
I would expect that the implementation of `IService<T>` is registered only once.

Autofac version: 4.8.1

```
    public class RegistrationTests
    {
        interface IService<T>
        {
        }

        class Service<T> : IService<T>
        {
        }

        [Fact]
        public void IfNotRegisteredShouldRegisterOpenGenericOnlyOnce()
        {
            var builder = new ContainerBuilder();
            builder.RegisterGeneric(typeof(Service<>))
                .As(typeof(IService<>))
                .IfNotRegistered(typeof(IService<>));

            builder.RegisterGeneric(typeof(Service<>))
                .As(typeof(IService<>))
                .IfNotRegistered(typeof(IService<>));


            var container = builder.Build();
            var services = container.Resolve<IEnumerable<IService<string>>>();
            services.Should().HaveCount(1);
        }
    }
```

Is there anything i can do about it? I need to make sure that open generic's are implemented only once. I tried to go with `OnlyIf()` but unfortunately i did not find a way how to resolve the open generic registrations because `RegistrationsFor()` returns an empty enumerable when used with open generic types.

**Comment by tillig** [comment]
When you register an open generic, it doesn't register a specific typed service; instead, it [registers a `RegistrationSource`](https://github.com/autofac/Autofac/blob/6dde84e5b0a3f82136a0567a84da498b04e1fa2d/src/Autofac/Features/OpenGenerics/OpenGenericRegistrationExtensions.cs#L50) that [dynamically generates registrations for closed types of the generic](https://github.com/autofac/Autofac/blob/master/src/Autofac/Features/OpenGenerics/OpenGenericRegistrationSource.cs). When you ask if something is registered, it's effectively asking, "If I tried to resolve this thing, is it in the container?"

The thing about open generics is... you couldn't resolve an open generic. Like, this isn't a thing:

```csharp
container.Resolve<IService<>>();
```

You have to resolve a closed generic.

```csharp
container.Resolve<IService<string>>();
```

Which makes sense in the resolve sense of things, but seems possibly confusing in the `IsRegistered` sense of things, since it looks like you _just registered that open generic_.

The TLDR here is that if you change your `IfNotRegistered` to be a _closed generic_ this works.

```csharp
        [Fact]
        public void IfNotRegisteredShouldRegisterOpenGenericOnlyOnce()
        {
            var builder = new ContainerBuilder();
            builder.RegisterGeneric(typeof(Service<>))
                .As(typeof(IService<>))
                .IfNotRegistered(typeof(IService<string>));

            builder.RegisterGeneric(typeof(Service<>))
                .As(typeof(IService<>))
                .IfNotRegistered(typeof(IService<string>));

            var container = builder.Build();
            var services = container.Resolve<IEnumerable<IService<string>>>();
            services.Should().HaveCount(1);
        }
```

I'll leave this open because at a minimum we should document this, but ideally we could make it more intuitive. I don't know exactly how we'd change that at the moment without changing some pretty low-level Autofac internals... but I can see that this isn't super intuitive.

Perhaps as a breaking change in 5.0+ of Autofac we could address this. It'd mean [modifying what `IsRegistered` means](https://github.com/autofac/Autofac/blob/acb742d0341540fe27c6daaf3a4b67335565dde0/src/Autofac/Core/Registration/ServiceRegistrationInfo.cs#L128) so it's not just checking for concrete implementations from places, but instead actually querying individual registrations/sources for a response. Unclear how that would affect perf, if at all, but it'd be a breaking change for the `RegistrationSource` interface, at a minimum.

**Comment by prochnowc** [comment]
@tillig Thanks for the explanation. The point is that other DI containers (to be specific Microsoft.Extensions, StructureMap) do support querying if an open generic service has been registered. Would be really great if Autofac could support this scenario.
Anyways, I managed to implement some "hack" to query for open generics, based on concrete types.

**Comment by tillig** [comment]
Given the age of this issue and the non-trivial solution that would be required to change the internals to adjust for this, I've [updated the documentation](https://autofac.readthedocs.io/en/latest/register/registration.html#conditional-registration) to show an example and explain that conditional registration for an _open_ generic means checking for registration of a _closed_ generic.

I do think it should be more intuitive, but I also don't think this is something we can fix without a lot of pain. If someone wants to submit a PR for it, we'd love to check it out; otherwise the docs will have to suffice.
