### ISSUE TITLE
Cannot override decorated interfaces in tests

### ISSUE THREAD

**Issue by blalonde** [autofac/Autofac#964]
Not sure if this is a bug or expected behavior, but when recalling RegisterType in tests or RegisterInstance, the class gets decorated anyway.

```
public interface IExternalDependency
{
}

public interface IDecorable
{

}

public class Decorator : IDecorable
{
	public Decorator(IDecorable decorated, IExternalDependency externalDependency)
	{
	}
}

public class Service : IDecorable
{
}

[Fact]

public void Test()
{
	var builder = new ContainerBuilder();
        
       // somewhere in unmodifiable code called by application
	builder.RegisterType<Service>().As<IDecorable>();
	builder.RegisterDecorator<Decorator, IDecorable>();

       // Test override
	var mock = new Mock<IDecorable>();
	builder.RegisterInstance<IDecorable>(mock.Object);

	var container = builder.Build();
	container.Resolve<IDecorable>(); // Throws Cannot resolve parameter 'IExternalDependency
}
```
Actual Behavior : Decorator decorates mock
Expected Behavior : Decorator doesn't decorate mock

**Comment by tillig** [comment]
This is functioning as designed.

Your "unmodifiable code" is registering a decorator. All `IDecorable` instances need to be decorated. Even if they're registered later, the decorator is associated with anything registered as `IDecorable`.

The decorator has an `IExternalDependency` that must be injected. If it's not provided, the decorator can't be created. That's the exception you're seeing.

If this were to just not decorate things at runtime if the dependency couldn't be satisfied, it would be equally odd (and hard to debug) why you expect the decorator to work but it's just not working. Instead, if the decorator is registered, it'll either be satisfied or fail and tell you why.

There is no concept of "unregister a registered decorator" just as there's no "unregister a registered type." The registration mechanism in Autofac is a series of callbacks in a builder rather than something like a literal collection of registrations that get put into a container, so there's nothing to iterate against or work around in this case.

To solve the issue, you'll can do one of these things...

- Register an `IExternalDependency`
- Add some app code that [allows you to conditionally register the decorator](https://autofac.readthedocs.io/en/latest/advanced/adapters-decorators.html). Maybe it's an environment variable or something.

```c#
builder.RegisterDecorator<Decorator, IDecorable>(
  context => String.IsNullOrEmpty(Environment.GetEnvironmentVariable("IsTest")));
```

There may be a way to get even fancier using property injection on the decorator and a manual instantiation or something, but I haven't tried it and don't have a snippet. I'd leave that as an exercise for the reader. But [the docs have some good examples showing how flexible the new syntax is](https://autofac.readthedocs.io/en/latest/advanced/adapters-decorators.html) so try out some of the lambda syntaxes to help you unlock the flexibility you need.

**Comment by blalonde** [comment]
If I remove the decorator line, I can successfully "unregister a registered type".

```
[Fact]
        public void Test()
        {
            var builder = new ContainerBuilder();

            builder.RegisterType<Service>().As<IDecorable>();

            var mock = new Mock<IDecorable>();
            builder.RegisterInstance<IDecorable>(mock.Object);

            var container = builder.Build();
            var resolved = container.Resolve<IDecorable>();
        }
```
I still feel like this is counter-intuitive. Maybe since I come from a structuremap background...
I ended up registering IExternalDependency,

**Comment by tillig** [comment]
If you remove the decorator line, sure, it's not registering the decorator... but in your code snippet that was in a section marked as `// somewhere in unmodifiable code called by application` so I took you at face value on that - the code was not modifiable by your test. Sorry if I misunderstood.

Autofac is pretty different than StructureMap. It may take some time to get used to. If you have more usage questions, it'd probably be good to try hitting up StackOverflow first since there's a lot larger group of folks that can help there. There are only two people who watch issues on Autofac (the project owners) so questions can sometimes get deprioritized for quite some time in favor of bugs and other issues.
