### ISSUE TITLE
LifetimeScope.BeginLifetimeScope is working differently if a builder is passed

### ISSUE THREAD

**Issue by weelink** [autofac/Autofac#980]
I would expect `LifetimeScope.BeginLifetimeScope(object)` to work as if I used `LifetimeScope.BeginLifetimeScope(object, builder => { })`, but these overloads are implemented differently.

`BeginLifetimeScope(object)` uses the `CopyOnWriteRegistry` where the write registry is a `ScopeRestrictedRegistry`, but `BeginLifetimeScope(object, Action<ContainerBuilder>)` is creating a `ScopeRestrictedRegistry` directly without `CopyOnWriteRegistry`.

So I'm wondering if there is a reason to keep these two implementations different. I can replace the implementation of `BeginLifetimeScope(object)` with `return BeginLifetimeScope(object, NoConfiguration);` and all the tests are passing.

Is a test missing? Or can the implementations be made consistent? Or both?

**Comment by tillig** [comment]
It may be possible to consolidate it, but IIRC the difference is around isolating new registrations that get made during that registration action and about handling startable (`AutoActivate`, `IStartable`) things that get registered as part of that action.

Something to look at when changing something like this is the benchmarks. Folks get super concerned about the tiniest performance issues in DI containers, from adding a couple of milliseconds onto creating a new lifetime scope to memory allocation for things that don't need to be allocated. For example, if the 90% case for creating a new lifetime scope is that there aren't additional registrations being added, optimizing to reduce operations (e.g., not scanning to try to run startable things) is valuable in those microperf scenarios. Pay-for-play, as it were.

Some of the tests that hit this stuff are more around, again, things like startables - "If I register new startables in a child lifetime scope, do they run?" [Tests like this.](https://github.com/autofac/Autofac/blob/f2e3d88cba6f707b538b0a38121553cfdebec68b/test/Autofac.Test/StartableTests.cs#L15) Admittedly, we've got varying levels of coverage - many tests are more about how we expect things to behave than enforcing hard code execution paths, and intentionally so - it allows, as you've noticed, some freedom in refactoring the internals. The downside is that we don't have much to test that certain things _don't_ happen, like, "If a new child scope is started and there _aren't_ any new registrations, then we _don't_ scan for additional startables." I'm not sure we'd want that level of test because it gets pretty fragile and locks down some of the internals a bit much.

If you can keep the perf and memory allocations roughly the same, standardizing would be fine. I know having the difference there has been a source of challenge in the past.
