### ISSUE TITLE
Unable to inject dependencies into private properties

### ISSUE THREAD

**Issue by daoqiang** [autofac/Autofac#983]
Thank you very much for your help. Attribute injection is too important for me.
Private attributes should be accessible through reflection, and I recommend that private attributes be injected correctly as well.

**Comment by alexmg** [comment]
@daoqiang Can you please provide an example of what is not working?

**Comment by daoqiang** [comment]
[AutofacDemo.zip](https://github.com/autofac/Autofac/files/3101863/AutofacDemo.zip)
private attribute

**Comment by tillig** [comment]
To clarify, it appears the problem is that you're trying to inject values into private _properties_. This is true and is functioning as designed. In order for Autofac to know about and allow property injection, [you need a public set method](https://github.com/autofac/Autofac/blob/02c5c10d09dfed97d0da8f26bb11afc8808f8c90/src/Autofac/Core/Activators/DefaultPropertySelector.cs#L50). You may override this on a per-registration basis by [providing your own property selector](https://github.com/autofac/Autofac/blob/f3adb9b7aa3bfe26e4c9f68c5717ba267e7faf9a/test/Autofac.Specification.Test/Features/PropertyInjectionTests.cs#L39) like the [`DelegatePropertySelector`](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Core/Activators/DelegatePropertySelector.cs). This will take some extra work on your part.

That said, it is probably not a good design from an OO / data hiding perspective to assume that DI would happen on non-public entities in your objects. It is better if dependencies are in the constructor so they are explicit; and if they can't be in the constructor, making the dependency properties public is a better solution to allowing folks to understand what your class needs. Without these as public, there's no way to plug in test values or anything, which is part of the whole point of DI.
