### ISSUE TITLE
Should it be an error that you can combine Named<> with As<>?

### ISSUE THREAD

**Issue by kbilsted** [autofac/Autofac#986]
In the autofact configuration, you can define a registration by combining both `.As<>` and `.Name<>`. I was wondering, since you register something by a name, I'm not sure it would be your intention to also have it be the default registration of a given type as well. Eg.

            builder.Register(c => new AA())
                .Named<IA>("Foo")
                .SingleInstance();

can be placed anywhere in your registration code, whereas

            builder.Register(c => new AA())
                .As<IA>()
                .Named<IA>("Foo")
                .SingleInstance();

if placed before other `IA` registrations, it will be the default registration of that type.

**Comment by tillig** [comment]
This is functioning as designed.

Order has always been important in registrations. Last in wins. However, registering multiple things with the same interface can help for IEnumerables.

```c#
var builder = new ContainerBuilder();
builder.RegisterType<First>().As<IService>();
builder.RegisterType<Second>().As<IService>();
var container = builder.Build();
Assert.IsType<Second>(container.Resolve<IService>());
Assert.Equals(2, container.Resolve<IEnumerable<IService>>().Count());
```

Imagine a system where you have several handlers that send notifications and you use DI to control which one is the default.

```c#
var builder = new ContainerBuilder();
builder.RegisterType<VoiceHandler>()
      .Named<INotifier>("voice");
builder.RegisterType<EmailHandler>()
       .As<INotifier>()
      .Named<INotifier>("email");
builder.RegisterType<SmsHandler>()
      .Named<INotifier>("sms");
```

Some things may always just want whatever the default is.

```c#
public class ConsumesDefaultNotifier
{
  public ConsumesDefaultNotifier(INotifier notifier){ /*...*/ }
}
```

Other things may want a specific one for some reason.

```c#
builder.Register(ctx => new MustUseVoiceCalls(ctx.ResolveNamed<INotifier>("voice")));
```

and 

```c#
public class MustUseVoiceCalls
{
  public MustUseVoiceCalls(INotifier voiceNotifier) { /* ... */ }
}
```

Allowing a single registration to represent both named and unnamed services provides a lot of flexibility that you wouldn't otherwise normally be able to accomplish. Conversely, with great power comes great responsibility - as with anything, if you're not careful you can shoot yourself in the foot and get unexpected results. It's up to the developer of the individual app to make sure they're designing and developing correctly. We can give you the hammer, it's up to you to not hit yourself in the thumb with it.

**Comment by kbilsted** [comment]
Many thanks for taking time to answer
