### ISSUE TITLE
Autofac Keyed/Named methods do not provide overload with service mapping func

### ISSUE THREAD

**Issue by bugged84** [autofac/Autofac#993]
The `As` method provides an overload with a `Func<Type, Type> serviceMapping` parameter, but the `Keyed` and `Named` methods do not. They only provide `Func<Type, object> serviceKeyMapping` and `Func<Type, string> serviceNameMapping` parameters, respectively.

However, I want to register a set of types with `RegisterAssemblyTypes` using the same key for all of the types, but using a different interface determined by the type itself. I was expecting to find a method overload such as `Keyed(object serviceKey, Func<Type, Type> serviceMapping)` or `Keyed(Func<Type, object> serviceKeyMapping, Func<Type, Type> serviceMapping)`.

Is this an oversight in the API design? Or am I missing something?

**Comment by tillig** [comment]
Can you give an example of what you expect to see? For example, I do see [a `Named` overload](https://github.com/autofac/Autofac/blob/ca70059aca7f9cbf6f64f0efa03567b75168ed9f/src/Autofac/RegistrationExtensions.cs#L513) that should let you provide a name for scanned assembly types. I see [`Keyed` also](https://github.com/autofac/Autofac/blob/ca70059aca7f9cbf6f64f0efa03567b75168ed9f/src/Autofac/RegistrationExtensions.cs#L534) The service key mapping function could just return a hard-coded value instead of doing anything with the type. There are also unit tests [showing how you can manually create your own `KeyedService` in any way you want](https://github.com/autofac/Autofac/blob/ac840a25dd82b0db3429cd15403411e963bb2102/test/Autofac.Test/Features/Scanning/ScanningRegistrationTests.cs#L103) if you'd rather do it that way.

Do those features not cover what you're trying to do? (Or do they otherwise not allow you to write your own extension method that does what you need?)

**Comment by bugged84** [comment]
@tillig the OP has examples.

**Comment by bugged84** [comment]
@tillig it looks like `KeyedService` combined with the `As` method was the part I was missing. Thanks.

**Comment by tillig** [comment]
No, I mean, show it in a hypothetical usage. I want to understand more about what you think you need that is missing and how you expect to use it. I can't help if I can't understand.

I'd also like to hear more about what you think of the things I pointed out and what you've tried to solve your own problem.

**Comment by tillig** [comment]
Glad it's working. Done and done.

**Comment by bugged84** [comment]
@tillig what I needed was a way to provide the container builder with service keys in a dynamic way based on the specific type being registered. I think the `KeyedService` class you mentioned is exactly what I need in order to accomplish that. I wish it were mentioned in the [docs](https://autofaccn.readthedocs.io/en/latest/advanced/keyed-services.html).

Before you provided that info, I had resorted to looping over my own collection of types and registering them individually using an existing `Keyed` method overload.
